Repository NOAA-EMC/global-workflow, pull requests merged in 2021-05, with the labels that each got.

#317 Updates to support EMC_verif-global major release
  Externals.cfg
  jobs/rocoto/metp.sh
  parm/config/config.metp
  sorc/checkout.sh
  ush/rocoto/setup_workflow.py
  ush/rocoto/setup_workflow_fcstonly.py
Labels: maintenance

#329 Fix module load order on Hera
  modulefiles/module_base.hera
Labels: coupled

#327 Operations updates for GFSv16.1.1
  Externals.cfg
  docs/Release_Notes.gfs.v16.1.0.txt
  jobs/rocoto/arch.sh
  jobs/rocoto/earc.sh
  parm/config/config.base.nco.static
  sorc/build_gsi.sh
  sorc/checkout.sh
Labels: production update
