Repository NOAA-EMC/global-workflow, pull requests merged in 2021-06, with the labels that each got.

#340 Fix ww3 pre-post modules
  modulefiles/modulefile.ww3.hera
  modulefiles/modulefile.ww3.orion
  modulefiles/modulefile.ww3.wcoss_dell_p3
  sorc/build_ww3prepost.sh
Labels: bug, coupled

#342 Free-forecast integration with chgres_cube and resolve know mode bugs
  env/HERA.env
  env/JET.env
  env/ORION.env
  env/WCOSS_C.env
  env/WCOSS_DELL_P3.env
  jobs/JGLOBAL_WAVE_PREP
  jobs/rocoto/arch.sh
  jobs/rocoto/fv3ic.sh
  jobs/rocoto/getic.sh
  jobs/rocoto/init.sh
  parm/config/config.base.emc.dyn
  parm/config/config.fv3
  parm/config/config.getic
  parm/config/config.init
  parm/config/config.nsst
  parm/config/config.resources
  scripts/exgfs_wave_post_pnt.sh
  sorc/build_all.sh
  sorc/build_fv3.sh
  sorc/build_ufs_utils.sh
  sorc/checkout.sh
  sorc/link_fv3gfs.sh
  sorc/machine-setup.sh
  ush/hpssarch_gen.sh
  ush/rocoto/setup_expt.py
  ush/rocoto/setup_expt_fcstonly.py
  ush/rocoto/setup_workflow.py
  ush/rocoto/setup_workflow_fcstonly.py
Labels: bug, feature

#349 Fix module base for Hera
  modulefiles/module_base.hera
Labels: bug, coupled

#350 Fix NST_SPINUP being ignored by CROW
  workflow/config/nsst.yaml
Labels: bug, coupled

#335 GFSv16.1.2 - Update EMC_post tag to upp_gfsv16_release.v1.1.4 and GSI tag to gfsda.v16.1.1a
  Externals.cfg
  sorc/checkout.sh
Labels: production update

#268 CMake for reg2grb2
  modulefiles/workflow_utils.hera
  modulefiles/workflow_utils.orion
  modulefiles/workflow_utils.wcoss_dell_p3
  sorc/CMakeLists.txt
  sorc/build_all.sh
  sorc/build_reg2grb2.sh
  sorc/build_workflow_utils.sh
  sorc/cpl_build.cfg
  sorc/link_fv3gfs.sh
  sorc/reg2grb2.fd/CMakeLists.txt
  sorc/reg2grb2.fd/Makefile
Labels: coupled

#358 Bug fix for module files
  modulefiles/module_base.hera
Labels: bug, coupled
