Repository NOAA-EMC/global-workflow, pull requests merged in 2021-11, with the labels that each got.

#489 GFSv16.1.5 - GSI update to include IASI Metop-C in operations
  Externals.cfg
  docs/Release_Notes.gfs.v16.1.5.txt
  env/WCOSS_DELL_P3.env
  parm/config/config.anal
  sorc/checkout.sh
Labels: production update

#488 Add coupled tasks to workflow and fix dependencies
  jobs/rocoto/coupled_ic.sh
  jobs/rocoto/ocnpost.sh
  jobs/rocoto/post.sh
  modulefiles/module_base.hera
  modulefiles/module_base.orion
  modulefiles/module_base.wcoss_dell_p3
  parm/config/config.coupled_ic
  parm/config/config.defaults.s2sw
  parm/config/config.fv3ic
  parm/config/config.ocnpost
  parm/config/config.resources
  parm/config/config.wave
  scripts/run_regrid.sh
  ush/forecast_postdet.sh
  ush/icepost.ncl
  ush/ocnpost.ncl
  ush/rocoto/setup_workflow.py
  ush/rocoto/setup_workflow_fcstonly.py
  ush/rocoto/workflow_utils.py
Labels: feature, coupled

#469 Handle NSSTBufr file creation/copying in parallels.
  jobs/rocoto/prep.sh
  parm/config/config.prep
Labels: bug, uncoupled

#492 Cycled IAU updates part 1
  parm/config/config.fv3
  ush/parsing_namelists_FV3.sh
Labels: coupled

#493 Feature/gw launcher flag - Closes #454
  env/HERA.env
  env/JET.env
  env/ORION.env
  env/WCOSS_DELL_P3.env
Labels: feature

#494 Update restart_interval in forecast configs
  parm/config/config.efcs
  parm/config/config.fcst
Labels: coupled

#514 Sync merge with operations branch for GFSv16.1.5
  Externals.cfg
  docs/Release_Notes.gfs.v16.1.4.txt
  docs/Release_Notes.gfs.v16.1.5.txt
  env/WCOSS_DELL_P3.env
  parm/config/config.anal
Labels: production update
