Repository NOAA-EMC/global-workflow, pull requests merged in 2021-08, with the labels that each got.

#390 Create a case file to be used for prototype 7
  workflow/cases/prototype7.yaml
Labels: coupled

#408 Add README for running atmos-only C192 test on Orion
  README_run_orion.md
Labels: feature

#411 Add ocnpost scripts from feature/coupled-crow
  jobs/rocoto/ocnpost.sh
  scripts/run_reg2grb2.sh
  scripts/run_regrid.sh
  ush/icepost.ncl
  ush/ocnpost.ncl
Labels: feature, coupled

#410 UFS_UTILS tag update - gdas_init support on Jet and HPSS path update for GFSv16 real-time parallel
  Externals.cfg
  parm/config/config.getic
  sorc/checkout.sh
Labels: maintenance, port

#412 Update workflow_utils build modules and remove ncio module hack
  modulefiles/workflow_utils.hera
  modulefiles/workflow_utils.jet
  modulefiles/workflow_utils.orion
  modulefiles/workflow_utils.wcoss_dell_p3
  sorc/build_workflow_utils.sh
Labels: maintenance

#414 Update vrfy/metp jobs to use jobid in their DATAROOT folders
  jobs/rocoto/metp.sh
  jobs/rocoto/vrfy.sh
  parm/config/config.post
Labels: bug, uncoupled

#422 GFSv16.1.2.1 - Update obsproc package versions for TAC2BUFR implementation
  parm/config/config.base.emc.dyn
  parm/config/config.base.nco.static
Labels: production update

#423 Update obsproc package versions for TAC2BUFR implementation
  parm/config/config.base.emc.dyn
  parm/config/config.base.nco.static
Labels: production update, uncoupled

#421 Add rstprod support to Orion
  sorc/checkout.sh
  ush/rocoto/setup_expt.py
  ush/rocoto/setup_expt_fcstonly.py
Labels: maintenance, uncoupled

#428 Add ocean model resolution case block in config.efcs
  parm/config/config.efcs
Labels: coupled

#432 Update SEND block in forecast_postdet.sh to populate RESTART folder
  ush/forecast_postdet.sh
Labels: bug, coupled
