Repository NOAA-EMC/global-workflow, pull requests merged in 2022-08, with the labels that each got.

#949 Add ocean post to archive dependencies
  workflow/rocoto/workflow_tasks.py
Labels: bug

#953 GFSv16.2.2 - RTOFSv2.3 upgrade
  docs/Release_Notes.gfs.v16.2.2.md
  ecf/versions/gfs.ver
  versions/run.ver
Labels: production update

#954 Fix GLDAS j-job link
  sorc/link_workflow.sh
Labels: bug

#958 RTOFSv2.3 upgrade changes
  docs/Release_Notes.gfs.v16.1.8.txt
  docs/Release_Notes.gfs.v16.2.2.md
  ecf/versions/gfs.ver
  versions/run.ver
Labels: maintenance

#959 Sync GFSv16.2.2/RTOFSv2.3 changes from operations into GFSv16.3.0 package
  docs/Release_Notes.gfs.v16.1.8.txt
  docs/Release_Notes.gfs.v16.2.2.md
  ecf/versions/gfs.ver
  versions/run.ver
Labels: production update

#961 Remove SDATE=CDATE IAU block in NCO config.base
  parm/config/config.base.nco.static
Labels: bug

#962 Sync bug fix for SDATE=CDATE block in config.base.nco.static into GFSv16.3.0 package
  parm/config/config.base.nco.static
Labels: bug

#963 Remove SDATE=CDATE IAU settings block in config.base.nco.static
  parm/config/config.base.nco.static
Labels: bug

#968 Update WAFS tag to gfs_wafs.v6.3.1 with associated resource and settings changes
  Externals.cfg
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_blending_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/jgfs_atmos_wafs_gcip.ecf
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
  parm/config/config.wafsblending0p25
  parm/config/config.wafsgcip
  parm/config/config.wafsgrib2
  parm/config/config.wafsgrib20p25
  sorc/checkout.sh
Labels: maintenance

#972 Update EMC_verif-global tag to verif_global_v2.10.0 (dev_v16.2.x)
  Externals.cfg
  sorc/checkout.sh
Labels: maintenance

#973 Update EMC_verif-global tag to verif_global_v2.10.0 in GFSv16.3.0 package
  Externals.cfg
  sorc/checkout.sh
Labels: maintenance

#983 GFSv16.3.0 updates for GSI tag, resources, versions, and WAFS CFP
  Externals.cfg
  ecf/versions/obsproc.ver
  env/HERA.env
  env/ORION.env
  env/WCOSS2.env
  jobs/rocoto/wafsgrib2.sh
  jobs/rocoto/wafsgrib20p25.sh
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
  sorc/checkout.sh
  versions/build.ver
  versions/hera.ver
  versions/orion.ver
  versions/run.ver
  versions/wcoss2.ver
Labels: maintenance

#988 Fix product generation at some fcst hrs
  ush/fv3gfs_downstream_nems.sh
Labels: bug

#969 Add GSI monitor scripts
  .gitignore
  jobs/JGDAS_ATMOS_VERFOZN
  jobs/JGDAS_ATMOS_VERFRAD
  jobs/JGDAS_ATMOS_VMINMON
  jobs/JGFS_ATMOS_VMINMON
  scripts/exgdas_atmos_verfozn.sh
  scripts/exgdas_atmos_verfrad.sh
  scripts/exgdas_atmos_vminmon.sh
  scripts/exgfs_atmos_vminmon.sh
  sorc/link_workflow.sh
  ush/minmon_xtrct_costs.pl
  ush/minmon_xtrct_gnorms.pl
  ush/minmon_xtrct_reduct.pl
  ush/ozn_xtrct.sh
  ush/radmon_diag_ck.sh
  ush/radmon_err_rpt.sh
  ush/radmon_verf_angle.sh
  ush/radmon_verf_bcoef.sh
  ush/radmon_verf_bcor.sh
  ush/radmon_verf_time.sh
  ush/rstprod.sh
Labels: maintenance

#998 Add missing "atmos" into job dependencies in workflow_tasks.py
  workflow/rocoto/workflow_tasks.py
Labels: bug

#1001 Update UFS_UTILS tag to `ufs_utils_1_8_0`
  Externals.cfg
  sorc/checkout.sh
Labels: feature

#1002 Build updates for WCOSS2
  modulefiles/module-setup.csh.inc
  modulefiles/module-setup.sh.inc
  modulefiles/module_base.wcoss2.lua
  modulefiles/modulefile.ww3.wcoss2.lua
  modulefiles/workflow_utils.wcoss2.lua
  sorc/link_workflow.sh
  sorc/machine-setup.sh
  ush/load_fv3gfs_modules.sh
Labels: feature

#1007 Add shell linter Github action for pull requests
  .github/workflows/linters.yaml
  .shellcheckrc
  ush/preamble.sh
Labels: feature
