Repository NOAA-EMC/global-workflow, pull requests merged in 2022-07, with the labels that each got.

#882 Sync merge GFSv16.2.1 updates into dev_v16
  docs/Release_Notes.gfs.v16.2.1.md
  ecf/scripts/gfs/atmos/post_processing/bufr_sounding/jgfs_atmos_postsnd.ecf
  ecf/scripts/gfs/atmos/post_processing/bulletins/jgfs_atmos_fbwind.ecf
  env/WCOSS2.env
  modulefiles/gfs_bufr.wcoss2.lua
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
  parm/transfer/transfer_rdhpcs_gfs_nawips.list
  scripts/exglobal_forecast.sh
  sorc/gfs_bufr.fd/calpreciptype.f
  sorc/gfs_bufr.fd/meteorg.f
Labels: production update

#890 Add module reset hack and postsnd resource adjustment for R&D
  parm/config/config.resources.emc.dyn
  sorc/machine-setup.sh
Labels: maintenance

#894 Sync merge from dev_v16 - bug fixes and obsproc update
  jobs/JGFS_ATMOS_CYCLONE_TRACKER
  parm/config/config.fv3.emc.dyn
  versions/hera.ver
  versions/orion.ver
  versions/wcoss2.ver
Labels: maintenance

#899 GFSv16.2.1
  docs/Release_Notes.gfs.v16.2.1.md
  ecf/scripts/gfs/atmos/post_processing/bufr_sounding/jgfs_atmos_postsnd.ecf
  ecf/scripts/gfs/atmos/post_processing/bulletins/jgfs_atmos_fbwind.ecf
  env/WCOSS2.env
  modulefiles/gfs_bufr.wcoss2.lua
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
  parm/transfer/transfer_rdhpcs_gfs_nawips.list
  scripts/exglobal_forecast.sh
  sorc/gfs_bufr.fd/calpreciptype.f
  sorc/gfs_bufr.fd/meteorg.f
Labels: production update

#901 Update EMC_verif-global to verif_global_v2.9.5 (dev_v16)
  Externals.cfg
  jobs/rocoto/metp.sh
  parm/config/config.metp
  sorc/checkout.sh
Labels: maintenance

#903 Sync EMC_verif-global.v2.9.5 updates into GFSv16.3.0
  Externals.cfg
  jobs/rocoto/metp.sh
  parm/config/config.metp
  sorc/checkout.sh
Labels: maintenance

#820 Refactor of ecfNode logic and updated documentation
  workflow_generator/README.md
  workflow_generator/ecflow_build.yml
  workflow_generator/ecflow_setup/ecflow_definitions.py
  workflow_generator/ecflow_setup/ecflow_setup.py
  workflow_generator/prod.yml
Labels: feature

#926 Add postsnd job when bufrsnd it on
  workflow/applications.py
Labels: bug

#920 WCOSS2 gempak ush scripts updates and cleanup of old release notes
  docs/Release_Notes.gfs.v15.2.0.txt
  docs/Release_Notes.gfs.v15.2.2.txt
  docs/Release_Notes.gfs.v16.0.0.md
  docs/Release_Notes.gfs.v16.1.0.txt
  docs/Release_Notes.gfs_downstream.v15.2.0.txt
  docs/Release_Notes.gfs_downstream.v16.0.0.txt
  gempak/ush/gdas_ukmet_meta_ver.sh
  gempak/ush/gfs_meta_comp.sh
  gempak/ush/gfs_meta_crb.sh
  gempak/ush/gfs_meta_hur.sh
  gempak/ush/gfs_meta_mar_comp.sh
  gempak/ush/gfs_meta_sa2.sh
Labels: production update, maintenance, port

#932 Changes to resources and upstream/downstream jobs from low res testing on supported platforms (dev_v16)
  jobs/rocoto/metp.sh
  jobs/rocoto/prep.sh
  modulefiles/module_base.hera.lua
  modulefiles/module_base.orion.lua
  modulefiles/module_base.wcoss2.lua
  parm/config/config.base.emc.dyn
  parm/config/config.fcst
  parm/config/config.fv3.emc.dyn
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
  sorc/machine-setup.sh
  ush/rocoto/workflow_utils.py
Labels: maintenance

#939 Move workflow_generator under ush and rename to ecflow
  ush/ecflow/README.md
  ush/ecflow/__init.py__
  ush/ecflow/ecflow_build.yml
  ush/ecflow/ecflow_setup/__init.py__
  ush/ecflow/ecflow_setup/ecflow_definitions.py
  ush/ecflow/ecflow_setup/ecflow_setup.py
  ush/ecflow/prod.yml
  ush/ecflow/setup_workflow.py
Labels: maintenance

#942 Remove MPICH_MPIIO_HINTS analcalc setting
  parm/config/config.resources.nco.static
Labels: maintenance

#940 Sync merge dev_v16 into GFSv16.3.0 package (low res testing updates)
  jobs/rocoto/metp.sh
  jobs/rocoto/prep.sh
  modulefiles/module_base.hera.lua
  modulefiles/module_base.orion.lua
  modulefiles/module_base.wcoss2.lua
  parm/config/config.base.emc.dyn
  parm/config/config.fcst
  parm/config/config.fv3.emc.dyn
  parm/config/config.resources.emc.dyn
  sorc/machine-setup.sh
  ush/ecflow/README.md
  ush/ecflow/__init.py__
  ush/ecflow/ecflow_build.yml
  ush/ecflow/ecflow_setup/__init.py__
  ush/ecflow/ecflow_setup/ecflow_definitions.py
  ush/ecflow/ecflow_setup/ecflow_setup.py
  ush/ecflow/prod.yml
  ush/ecflow/setup_workflow.py
  ush/rocoto/workflow_utils.py
  workflow_generator/README.md
Labels: maintenance

#944 Remove gfsmetp gfsarch dependency in dev_v16, release/gfs.v16.3.0
  ush/rocoto/setup_workflow.py
  ush/rocoto/setup_workflow_fcstonly.py
Labels: bug

#934 Initial commit of directory comparison tools
  test/README.md
  test/coordinates.lst
  test/diff_ROTDIR.sh
  test/diff_UFS_rundir.sh
  test/diff_grib_files.py
  test/netcdf_op_functions.sh
  test/test_utils.sh
Labels: feature
