Repository NOAA-EMC/global-workflow, pull requests merged in 2022-10, with the labels that each got.

#1038 Rename post scripts
  .shellcheckrc
  jobs/JGLOBAL_ATMOS_POST
  jobs/rocoto/post.sh
  parm/config/config.post
  scripts/exgdas_atmos_post.sh
  scripts/exgfs_atmos_post.sh
  sorc/link_workflow.sh
  ush/gfs_nceppost.sh
  ush/gfs_post.sh
Labels: maintenance

#1012 Replace preamble variable commands with functions
  jobs/rocoto/arch.sh
  jobs/rocoto/earc.sh
  scripts/exgfs_atmos_awips_20km_1p0deg.sh
  scripts/exgfs_atmos_fbwind.sh
  scripts/exgfs_atmos_grib2_special_npoess.sh
  scripts/exgfs_atmos_grib_awips.sh
  scripts/exgfs_wave_init.sh
  scripts/exgfs_wave_nawips.sh
  scripts/exgfs_wave_post_gridded_sbs.sh
  scripts/exgfs_wave_post_pnt.sh
  scripts/exgfs_wave_prdgen_bulls.sh
  scripts/exgfs_wave_prdgen_gridded.sh
  scripts/exgfs_wave_prep.sh
  ush/fv3gfs_downstream_nems.sh
  ush/load_fv3gfs_modules.sh
  ush/parsing_namelists_WW3.sh
  ush/preamble.sh
  ush/syndat_getjtbul.sh
  ush/syndat_qctropcy.sh
  ush/tropcy_relocate.sh
  ush/tropcy_relocate_extrkr.sh
  ush/wave_grib2_sbs.sh
  ush/wave_grid_interp_sbs.sh
  ush/wave_grid_moddef.sh
  ush/wave_outp_cat.sh
  ush/wave_outp_spec.sh
  ush/wave_prnc_ice.sh
  ush/wave_tar.sh
Labels: maintenance

#1048 Update gfs-utils hash for WCOSS2 support
  Externals.cfg
  sorc/checkout.sh
Labels: feature

#1053 Fix group number being treated as octal in gdas arch
  jobs/rocoto/earc.sh
Labels: bug

#1050 Add GDAS to the partial build list
  sorc/gfs_build.cfg
  sorc/partial_build.sh
Labels: bug

#1049 Update to obsproc.v1.0.2 and prepobs.v1.0.1
  env/HERA.env
  env/ORION.env
  jobs/rocoto/prep.sh
  modulefiles/module_base.hera.lua
  modulefiles/module_base.orion.lua
  parm/config/config.base.emc.dyn
  parm/config/config.base.nco.static
  parm/config/config.prep
  parm/config/config.prepbufr
  parm/config/config.resources
Labels: feature

#1057 Fix eupd trace
  scripts/exgdas_enkf_update.sh
  ush/forecast_postdet.sh
Labels: bug

#1061 Limit number of CPU for post
  parm/config/config.resources
Labels: bug

#1064 Add trailing slash for gldas topo path
  scripts/exgdas_atmos_gldas.sh
Labels: bug

#1066 Fix companion ocean resolution for C48
  parm/config/config.base.emc.dyn
  parm/config/config.efcs
  parm/config/config.ocn
Labels: bug

#1082 GFS-UTILS update for build and ush scripts
  Externals.cfg
  gempak/ush/gempak_gfs_f00_gif.sh
  parm/config/config.gldas
  scripts/exgfs_atmos_fbwind.sh
  sorc/build_gfs_utils.sh
  sorc/checkout.sh
  sorc/link_workflow.sh
Labels: bug

#1088 gfs utils update
  modulefiles/modulefile.ww3.hera.lua
  modulefiles/modulefile.ww3.orion.lua
  modulefiles/modulefile.ww3.s4.lua
  modulefiles/modulefile.ww3.wcoss2.lua
  sorc/build_all.sh
  sorc/build_gdas.sh
  sorc/build_ww3prepost.sh
  sorc/checkout.sh
Labels: bug

#1092 Set COMPILER in link for detect machine
  .gitignore
  sorc/link_workflow.sh
Labels: bug

#1070 Resource updates to support WCOSS2
  ecf/scripts/enkfgdas/analysis/recenter/jenkfgdas_sfc.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_blending_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/jgfs_atmos_wafs_gcip.ecf
  parm/config/config.coupled_ic
  parm/config/config.fv3
  parm/config/config.resources
  sorc/build_ufs.sh
  workflow/hosts/wcoss2.yaml
Labels: feature

#1094 Change GLDAS USE_CFP to NO on Hera
  env/HERA.env
Labels: bug

#1101 Correct errors with gdas and monitoring symlinks
  sorc/link_workflow.sh
Labels: bug

#1022 Add Early Cycle EnKF workflow
  jobs/JGDAS_ENKF_ECEN
  jobs/JGDAS_ENKF_FCST
  jobs/JGDAS_ENKF_SFC
  parm/config/config.anal
  ush/calcanl_gfs.py
  ush/forecast_predet.sh
  workflow/applications.py
  workflow/rocoto/workflow_tasks.py
Labels: feature
