Repository NOAA-EMC/global-workflow, pull requests merged in 2022-06, with the labels that each got.

#836 GFSv16.1.8 updates (Switch to Meteosat-9 AMVs) into operations branch
  Externals.cfg
  docs/Release_Notes.gfs.v16.1.8.txt
  sorc/checkout.sh
Labels: production update

#766 Consolidate post scripts to eliminate coupled mode of link script
  .gitignore
  scripts/exgfs_atmos_nceppost.sh
  scripts/exgfs_nceppost_cpl.sh
  sorc/link_workflow.sh
  ush/fv3gfs_downstream_nems.sh
  ush/fv3gfs_downstream_nems_cpl.sh
Labels: maintenance

#845 Updates from testing dev_v16 on Hera
  env/HERA.env
  modulefiles/module_base.hera.lua
  parm/config/config.base.emc.dyn
  parm/config/config.resources.emc.dyn
  versions/hera.ver
Labels: maintenance

#846 Sync merge Hera low res testing updates into v16.3.0 workflow
  env/HERA.env
  modulefiles/module_base.hera.lua
  parm/config/config.base.emc.dyn
  parm/config/config.resources.emc.dyn
  versions/hera.ver
Labels: maintenance

#813 Add "atmos" COMPONENT subfolder to DMPDIR paths (dev_v16)
  jobs/JGLOBAL_WAVE_PREP
  jobs/rocoto/prep.sh
  parm/config/config.anal
  ush/drive_makeprepbufr.sh
  ush/getdump.sh
  ush/rocoto/setup_workflow.py
Labels: feature

#771 Move remaining global post scripts over from UPP
  .gitignore
  jobs/JGLOBAL_ATMOS_NCEPPOST
  jobs/JGLOBAL_ATMOS_POST_MANAGER
  parm/post/global_1x1_paramlist_g2
  parm/post/global_1x1_paramlist_g2.anl
  parm/post/global_1x1_paramlist_g2.f000
  parm/post/global_master-catchup_parmlist_g2
  scripts/exgdas_atmos_nceppost.sh
  scripts/exglobal_atmos_pmgr.sh
  sorc/link_workflow.sh
  ush/fv3gfs_dwn_nems.sh
  ush/gfs_nceppost.sh
  ush/gfs_transfer.sh
  ush/global_nceppost.sh
  ush/link_crtm_fix.sh
  ush/mod_icec.sh
  ush/trim_rh.sh
Labels: maintenance

#848 Retire VSDB
  jobs/rocoto/vrfy.sh
  parm/config/config.base.emc.dyn
  parm/config/config.base.nco.static
  parm/config/config.vrfy
  scripts/vsdbjob_submit.sh
Labels: maintenance

#852 Update GLDAS tag to gldas_gfsv16_release.v.2.1.0
  Externals.cfg
  sorc/checkout.sh
Labels: maintenance

#853 Add `atmos` subfolder to workflow `DMPDIR` paths
  Externals.cfg
  jobs/JGLOBAL_WAVE_PREP
  jobs/rocoto/prep.sh
  parm/config/config.anal
  sorc/checkout.sh
  ush/drive_makeprepbufr.sh
  ush/getdump.sh
  ush/rocoto/setup_workflow.py
Labels: feature, maintenance

#855 Updated ufs-weather-model tag for GFSv16.3.0
  Externals.cfg
  sorc/checkout.sh
Labels: maintenance

#860 Fit2Obs workflow-side updates and new `newm.1.5` tag
  jobs/rocoto/vrfy.sh
  parm/config/config.vrfy
  versions/hera.ver
  versions/orion.ver
  versions/wcoss2.ver
Labels: maintenance

#862 Resource adjustments and updated obsproc/prepobs packages for tcvitals bug fix
  ecf/scripts/enkfgdas/analysis/recenter/jenkfgdas_sfc.ecf
  ecf/scripts/gdas/atmos/gempak/jgdas_atmos_gempak.ecf
  ecf/scripts/gdas/atmos/gempak/jgdas_atmos_gempak_meta_ncdc.ecf
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_gempak.ecf
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_gempak_meta.ecf
  ecf/scripts/gfs/atmos/post_processing/awips_20km_1p0/jgfs_atmos_awips_master.ecf
  ecf/scripts/gfs/atmos/post_processing/awips_g2/jgfs_atmos_awips_g2_master.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_blending_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/grib_wafs/jgfs_atmos_wafs_master.ecf
  ecf/scripts/gfs/wave/gempak/jgfs_wave_gempak.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_postsbs.ecf
  ecf/scripts/gfs/wave/prep/jgfs_wave_prep.ecf
  parm/config/config.fv3.emc.dyn
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
  versions/hera.ver
  versions/orion.ver
  versions/wcoss2.ver
Labels: maintenance

#864 Bug fix to enkf_chgres_recenter_nc.fd
  sorc/enkf_chgres_recenter_nc.fd/utils.f90
Labels: nco-bug

#866 Fixes to the enkf_chgres_recenter_nc code from GDIT
  sorc/enkf_chgres_recenter_nc.fd/utils.f90
Labels: maintenance

#870 Update `FIX_DIR` paths to fix_nco_gfsv16.3.0 set
  sorc/link_fv3gfs.sh
Labels: maintenance

#873 update dust input files to not include _FillValue = NaN
  parm/chem/ExtData.other
  parm/config/config.aero
Labels: bug

#879 Fix to gfs_bufr code and job
  docs/Release_Notes.gfs.v16.2.1.md
  ecf/scripts/gfs/atmos/post_processing/bufr_sounding/jgfs_atmos_postsnd.ecf
  ecf/scripts/gfs/atmos/post_processing/bulletins/jgfs_atmos_fbwind.ecf
  env/WCOSS2.env
  modulefiles/gfs_bufr.wcoss2.lua
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
  parm/transfer/transfer_rdhpcs_gfs_nawips.list
  sorc/gfs_bufr.fd/calpreciptype.f
  sorc/gfs_bufr.fd/meteorg.f
Labels: production update

#881 Update buoy locations
  parm/wave/wave_gfs.buoys
  parm/wave/wave_gfs.buoys.dat
  parm/wave/wave_gfs.buoys.full
Labels: maintenance
