Repository NOAA-EMC/global-workflow, pull requests merged in 2022-03, with the labels that each got.

#659 Add single forecast GOCART support
  env/HERA.env
  env/JET.env
  env/ORION.env
  env/WCOSS_DELL_P3.env
  jobs/rocoto/arch.sh
  modulefiles/module_base.jet
  parm/chem/AERO.rc
  parm/chem/AERO_HISTORY.rc
  parm/chem/AGCM.rc
  parm/chem/CA2G_instance_CA.bc.rc
  parm/chem/CA2G_instance_CA.br.rc
  parm/chem/CA2G_instance_CA.oc.rc
  parm/chem/CAP.rc
  parm/chem/DU2G_instance_DU.rc
  parm/chem/ExtData.gbbepx
  parm/chem/ExtData.none
  parm/chem/ExtData.other
  parm/chem/ExtData.qfed
  parm/chem/GOCART2G_GridComp.rc
  parm/chem/NI2G_instance_NI.rc
  parm/chem/SS2G_instance_SS.rc
  parm/chem/SU2G_instance_SU.rc
  parm/config/config.aero
  parm/config/config.base.emc.dyn
  parm/config/config.efcs
  parm/config/config.fcst
  parm/config/config.resources
  parm/parm_fv3diag/diag_table.aero
  parm/parm_fv3diag/diag_table_aer
  parm/parm_fv3diag/field_table.aero
  scripts/exgfs_nceppost_cpl.sh
  scripts/exglobal_forecast.sh
  sorc/build_ufs.sh
  ush/cplvalidate.sh
  ush/forecast_postdet.sh
  ush/hpssarch_gen.sh
  ush/nems.configure.atm_aero.IN
  ush/nems.configure.cpld_aero_wave.IN
  ush/nems_configure.sh
  ush/parsing_namelists_FV3.sh
  ush/rocoto/setup_expt.py
Labels: feature, coupled

#689 Add needed gempak subfolder to gempak ush scripts
  gempak/ush/gdas_ukmet_meta_ver.sh
  gempak/ush/gfs_meta_comp.sh
  gempak/ush/gfs_meta_crb.sh
  gempak/ush/gfs_meta_hur.sh
  gempak/ush/gfs_meta_mar_comp.sh
  gempak/ush/gfs_meta_sa2.sh
Labels: production update

#696 Update prep job functionality to use new WCOSS2-port obsproc/prepobs packages
  jobs/rocoto/prep.sh
  parm/config/config.base.emc.dyn
  parm/config/config.base.nco.static
  versions/wcoss2.ver
Labels: feature, production update

#697 Sync merge feature/ops-wcoss2 into dev_v16 (gempak/prep)
  gempak/ush/gdas_ukmet_meta_ver.sh
  gempak/ush/gfs_meta_comp.sh
  gempak/ush/gfs_meta_crb.sh
  gempak/ush/gfs_meta_hur.sh
  gempak/ush/gfs_meta_mar_comp.sh
  gempak/ush/gfs_meta_sa2.sh
  jobs/rocoto/prep.sh
  parm/config/config.base.emc.dyn
  parm/config/config.base.nco.static
  versions/wcoss2.ver
Labels: production update

#699 Code update to syndat_getjtbul.fd for v16.1.7
  sorc/syndat_getjtbul.fd/getjtbul.f
Labels: production update

#702 Sync final GFSv16.1.6 updates into GFSv16.2.0 package
  docs/Release_Notes.gfs.v16.1.6.txt
  parm/config/config.anal
  sorc/checkout.sh
Labels: production update
