Repository NOAA-EMC/global-workflow, pull requests merged in 2022-04, with the labels that each got.

#700 dev_v16 build and versions updates to support Hera/Orion
  modulefiles/fv3gfs/enkf_chgres_recenter.hera.lua
  modulefiles/fv3gfs/enkf_chgres_recenter.orion.lua
  modulefiles/fv3gfs/enkf_chgres_recenter_nc.hera.lua
  modulefiles/fv3gfs/enkf_chgres_recenter_nc.orion.lua
  modulefiles/fv3gfs/gaussian_sfcanl.hera.lua
  modulefiles/fv3gfs/gaussian_sfcanl.orion.lua
  modulefiles/gfs_bufr.hera.lua
  modulefiles/gfs_bufr.orion.lua
  modulefiles/gfs_fbwndgfs.hera.lua
  modulefiles/gfs_fbwndgfs.orion.lua
  modulefiles/module_base.hera.lua
  modulefiles/module_base.orion.lua
  modulefiles/modulefile.fv3nc2nemsio.hera.lua
  modulefiles/modulefile.fv3nc2nemsio.orion.lua
  modulefiles/modulefile.regrid_nemsio.hera.lua
  modulefiles/modulefile.regrid_nemsio.orion.lua
  modulefiles/modulefile.storm_reloc_v6.0.0.hera.lua
  modulefiles/modulefile.storm_reloc_v6.0.0.orion.lua
  sorc/build_fv3.sh
  sorc/build_fv3nc2nemsio.sh
  sorc/build_regrid_nemsio.sh
  sorc/build_tropcy_NEMS.sh
  sorc/checkout.sh
  sorc/enkf_chgres_recenter_nc.fd/makefile
  sorc/link_fv3gfs.sh
  sorc/supvit.fd/makefile
  sorc/syndat_getjtbul.fd/makefile
  sorc/syndat_maksynrc.fd/makefile
  sorc/syndat_qctropcy.fd/makefile
  sorc/tave.fd/makefile
  sorc/vint.fd/makefile
  versions/hera.ver
  versions/orion.ver
Labels: port

#707 Resolve issue of `config.base.emc.dyn` in `$EXPDIR`
  sorc/link_workflow.sh
  ush/rocoto/setup_expt.py
Labels: bug

#716 Add WCOSS2 operational GFS defs files
  ecf/defs/gfs_00.def
  ecf/defs/gfs_06.def
  ecf/defs/gfs_12.def
  ecf/defs/gfs_18.def
Labels: production update

#727 WCOSS2 GFS ops updates to address two issues (anal_calc & gfs_forecast)
  ecf/scripts/gdas/atmos/analysis/jgdas_atmos_analysis_calc.ecf
  ecf/scripts/gfs/jgfs_forecast.ecf
  parm/config/config.fv3.nco.static
  parm/config/config.resources.nco.static
Labels: production update

#734 GFSv16.1.7 updates and changes from NCO for GFSv16.2.0
  docs/Release_Notes.gfs.v16.1.7.txt
  docs/Release_Notes.gfs.v16.2.0.md
  ecf/scripts/enkfgdas/analysis/recenter/jenkfgdas_sfc.ecf
  ecf/scripts/gdas/wave/prep/jgdas_wave_prep.ecf
  ecf/scripts/gfs/atmos/post/jgfs_atmos_post_master.ecf
  ecf/scripts/gfs/wave/prep/jgfs_wave_prep.ecf
  modulefiles/module_base.wcoss2.lua
  parm/config/config.resources.nco.static
  sorc/syndat_getjtbul.fd/getjtbul.f
  versions/build.ver
  versions/run.ver
Labels: production update

#735 Update UPP tag to upp_v8.1.2
  Externals.cfg
  docs/Release_Notes.gfs.v16.2.0.md
  sorc/checkout.sh
Labels: production update

#755 Update WCOSS2 env file cpu-bind flags: core to depth
  env/WCOSS2.env
Labels: production update

#756 Convert module files from Tcl to Lua
  modulefiles/module_base.hera
  modulefiles/module_base.hera.lua
  modulefiles/module_base.jet
  modulefiles/module_base.jet.lua
  modulefiles/module_base.orion
  modulefiles/module_base.orion.lua
  modulefiles/module_base.wcoss_dell_p3
  modulefiles/module_base.wcoss_dell_p3.lua
  modulefiles/modulefile.ww3.hera
  modulefiles/modulefile.ww3.hera.lua
  modulefiles/modulefile.ww3.orion
  modulefiles/modulefile.ww3.orion.lua
  modulefiles/modulefile.ww3.wcoss_dell_p3
  modulefiles/modulefile.ww3.wcoss_dell_p3.lua
  modulefiles/workflow_utils.hera
  modulefiles/workflow_utils.hera.lua
  modulefiles/workflow_utils.jet
  modulefiles/workflow_utils.jet.lua
  modulefiles/workflow_utils.orion
  modulefiles/workflow_utils.orion.lua
  modulefiles/workflow_utils.wcoss_dell_p3
  modulefiles/workflow_utils.wcoss_dell_p3.lua
  sorc/build_workflow_utils.sh
  sorc/build_ww3prepost.sh
  sorc/machine-setup.sh
Labels: maintenance

#763 Sync dev_v16 with feature/ops-wcoss2
  Externals.cfg
  docs/Release_Notes.gfs.v16.1.6.txt
  docs/Release_Notes.gfs.v16.1.7.txt
  docs/Release_Notes.gfs.v16.2.0.md
  ecf/defs/gfs_00.def
  ecf/defs/gfs_06.def
  ecf/defs/gfs_12.def
  ecf/defs/gfs_18.def
  ecf/scripts/enkfgdas/analysis/recenter/jenkfgdas_sfc.ecf
  ecf/scripts/gdas/atmos/analysis/jgdas_atmos_analysis_calc.ecf
  ecf/scripts/gdas/wave/prep/jgdas_wave_prep.ecf
  ecf/scripts/gfs/atmos/post/jgfs_atmos_post_master.ecf
  ecf/scripts/gfs/jgfs_forecast.ecf
  ecf/scripts/gfs/wave/prep/jgfs_wave_prep.ecf
  env/WCOSS2.env
  parm/config/config.anal
  parm/config/config.fv3.nco.static
  parm/config/config.resources.nco.static
  sorc/checkout.sh
  sorc/syndat_getjtbul.fd/getjtbul.f
  versions/build.ver
Labels: documentation, production update, maintenance

#762 Remove unneeded/outdated modulefiles
  modulefiles/OznMonBuild.orion
  modulefiles/OznMonBuild.wcoss_dell_p3
  modulefiles/RadMonBuild.orion
  modulefiles/RadMonBuild.wcoss_dell_p3
  modulefiles/module_base.wcoss_c
Labels: maintenance
