Repository NOAA-EMC/global-workflow, pull requests merged in 2022-11, with the labels that each got.

#1104 Add GSI background error covariance as an option for UFS DA variational assimilation
  parm/config/config.atmanal
  scripts/exgdas_global_atmos_analysis_run.sh
  sorc/link_workflow.sh
  versions/fix.ver
Labels: feature

#1107 GFSv16.2.3 - annual CO2 fix file update for 2023
  docs/Release_Notes.gfs.v16.2.3.md
  ecf/versions/obsproc_global.ver
  versions/run.ver
Labels: production update

#1118 Update MODULEPATH for gfs_bufr build on Orion
  modulefiles/gfs_bufr.orion.lua
Labels: maintenance

#1124 MPMD variable updates and fix
  env/JET.env
  env/S4.env
  env/WCOSS2.env
  jobs/JGLOBAL_WAVE_INIT
Labels: bug, feature

#1126 Update MODULEPATH for Orion
  modulefiles/module_base.orion.lua
Labels: maintenance

#1136 Address shellcheck warnings in env files
  env/HERA.env
  env/JET.env
  env/ORION.env
  env/S4.env
  env/WCOSS2.env
  env/gfs.ver
Labels: maintenance

#1137 Sync with NCO v16.3.3 install
  docs/Release_Notes.gfs.v16.3.3.md
  versions/run.ver
Labels: production update

#1138 Remove prod_envir module load from WCOSS2
  modulefiles/module_base.wcoss2.lua
Labels: maintenance
