Repository NOAA-EMC/global-workflow, pull requests merged in 2022-01, with the labels that each got.

#544 Series of small WCOSS2 updates - round 3
  env/WCOSS2.env
  jobs/rocoto/vrfy.sh
  modulefiles/fv3gfs/enkf_chgres_recenter.wcoss2
  modulefiles/fv3gfs/enkf_chgres_recenter.wcoss2.lua
  modulefiles/fv3gfs/gaussian_sfcanl.wcoss2
  modulefiles/fv3gfs/gaussian_sfcanl.wcoss2.lua
  modulefiles/gfs_bufr.wcoss2
  modulefiles/gfs_bufr.wcoss2.lua
  modulefiles/gfs_fbwndgfs.wcoss2
  modulefiles/gfs_fbwndgfs.wcoss2.lua
  modulefiles/modulefile.fv3nc2nemsio.wcoss2
  modulefiles/modulefile.fv3nc2nemsio.wcoss2.lua
  modulefiles/modulefile.regrid_nemsio.wcoss2
  modulefiles/modulefile.regrid_nemsio.wcoss2.lua
  modulefiles/modulefile.storm_reloc_v6.0.0.wcoss2
  modulefiles/modulefile.storm_reloc_v6.0.0.wcoss2.lua
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
  parm/config/config.vrfy
  sorc/build_enkf_chgres_recenter.sh
  sorc/build_fv3nc2nemsio.sh
  sorc/build_gaussian_sfcanl.sh
  sorc/build_gfs_bufrsnd.sh
  sorc/build_gfs_fbwndgfs.sh
  sorc/build_regrid_nemsio.sh
  sorc/build_tropcy_NEMS.sh
  ush/rocoto/rocoto.py
  ush/rocoto/setup_workflow.py
  ush/rocoto/setup_workflow_fcstonly.py
  ush/rocoto/workflow_utils.py
Labels: port

#545 Series of small WCOSS2 updates - round 4
  env/WCOSS2.env
  parm/config/config.efcs
  parm/config/config.fcst
  sorc/checkout.sh
  versions/run.ver
Labels: port

#546 Series of small WCOSS2 updates - round 5
  parm/config/config.fv3.nco.static
  parm/config/config.resources.nco.static
  sorc/checkout.sh
  sorc/link_fv3gfs.sh
  ush/rocoto/workflow_utils.py
Labels: port

#550 Series of small WCOSS2 updates - round 6
  parm/config/config.base.emc.dyn
  parm/config/config.base.nco.static
  scripts/exglobal_forecast.sh
  sorc/build_gfs_util.sh
  sorc/checkout.sh
  util/modulefiles/gfs_util.wcoss2
  util/modulefiles/gfs_util.wcoss2.lua
  util/sorc/compile_gfs_util_wcoss.sh
  util/sorc/mkgfsawps.fd/compile_mkgfsawps_wcoss.sh
  util/sorc/overgridid.fd/compile_overgridid_wcoss.sh
  util/sorc/rdbfmsua.fd/compile_rdbfmsua_wcoss.sh
  util/sorc/webtitle.fd/compile_webtitle_wcoss.sh
Labels: port

#552 Remove KMP variables from WCOSS2.env and adjust run.ver
  env/WCOSS2.env
  versions/run.ver
Labels: port

#554 GFSv16.2.0 release notes and updated WAFS tag
  docs/Release_Notes.gfs.v16.2.0.md
  env/WCOSS2.env
  sorc/checkout.sh
Labels: port

#556 Update Release_Notes.gfs.v16.2.0.md - more markdown syntax
  docs/Release_Notes.gfs.v16.2.0.md
Labels: port

#557 Add OMP_STACKSIZE to WCOSS2.env for forecast
  env/WCOSS2.env
Labels: port

#565 Updates to ROTDIR/COMIN definitions related to compath.py and new GLDAS tag
  docs/Release_Notes.gfs.v16.2.0.md
  driver/product/run_JGDAS_ATMOS_GEMPAK_META_NCDC_wcoss2.sh_00
  driver/product/run_JGFS_ATMOS_GEMPAK_META_wcoss2.sh_00
  driver/product/run_JGFS_ATMOS_GEMPAK_META_wcoss2.sh_12
  jobs/JGDAS_ATMOS_GEMPAK
  jobs/JGDAS_ATMOS_GEMPAK_META_NCDC
  jobs/JGFS_ATMOS_AWIPS_20KM_1P0DEG
  jobs/JGFS_ATMOS_AWIPS_G2
  jobs/JGFS_ATMOS_CYCLONE_GENESIS
  jobs/JGFS_ATMOS_CYCLONE_TRACKER
  jobs/JGFS_ATMOS_FBWIND
  jobs/JGFS_ATMOS_FSU_GENESIS
  jobs/JGFS_ATMOS_GEMPAK
  jobs/JGFS_ATMOS_GEMPAK_META
  jobs/JGFS_ATMOS_GEMPAK_NCDC_UPAPGIF
  jobs/JGFS_ATMOS_GEMPAK_PGRB2_SPEC
  jobs/JGFS_ATMOS_PGRB2_SPEC_NPOESS
  jobs/JGFS_ATMOS_POSTSND
  jobs/JGLOBAL_ATMOS_EMCSFC_SFC_PREP
  jobs/JGLOBAL_ATMOS_TROPCY_QC_RELOC
  jobs/JGLOBAL_FORECAST
  jobs/JGLOBAL_WAVE_GEMPAK
  jobs/JGLOBAL_WAVE_INIT
  jobs/JGLOBAL_WAVE_POST_BNDPNT
  jobs/JGLOBAL_WAVE_POST_BNDPNTBLL
  jobs/JGLOBAL_WAVE_POST_PNT
  jobs/JGLOBAL_WAVE_POST_SBS
  jobs/JGLOBAL_WAVE_PRDGEN_BULLS
  jobs/JGLOBAL_WAVE_PRDGEN_GRIDDED
  jobs/JGLOBAL_WAVE_PREP
  jobs/rocoto/vrfy.sh
  parm/config/config.base.nco.static
  sorc/checkout.sh
Labels: port

#575 Update ecf scripts for memory and exclusivity; update release notes
  docs/Release_Notes.gfs.v16.2.0.md
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_gempak.ecf
  ecf/scripts/gfs/atmos/post_processing/awips_20km_1p0/jgfs_atmos_awips_master.ecf
  ecf/scripts/gfs/atmos/post_processing/awips_g2/jgfs_atmos_awips_g2_master.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_blending.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_blending_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/grib_wafs/jgfs_atmos_wafs_master.ecf
  ecf/scripts/gfs/jgfs_forecast.ecf
Labels: port

#576 Series of small WCOSS2 updates - round 7
  docs/Release_Notes.gfs.v16.2.0.md
  ecf/scripts/gdas/atmos/post/jgdas_atmos_post_anl.ecf
  ecf/scripts/gdas/atmos/post/jgdas_atmos_post_master.ecf
  ecf/scripts/gfs/atmos/post/jgfs_atmos_post_master.ecf
  parm/config/config.resources.nco.static
  ush/rocoto/workflow_utils.py
  versions/run.ver
Labels: port

#569 Update config missed in last GSI update
  parm/config/config.anal
Labels: bug

#579 Remove redundant toggle for gldas build
  sorc/cpl_build.cfg
  sorc/fv3gfs_build.cfg
  sorc/partial_build.sh
Labels: bug

#591 Update component tags based on NCO feedback 20220118
  docs/Release_Notes.gfs.v16.2.0.md
  sorc/checkout.sh
Labels: port

#570 Fix lfrac entry in diag table
  parm/parm_fv3diag/diag_table_cpl
Labels: bug, coupled

#605 Series of small WCOSS2 updates - round 8
  env/WCOSS2.env
  jobs/JGLOBAL_WAVE_POST_SBS
  parm/config/config.base.emc.dyn
  ush/rocoto/setup_workflow.py
  ush/rocoto/setup_workflow_fcstonly.py
  ush/rocoto/workflow_utils.py
Labels: port

#608 Remove obsproc tasks from ecflow suite.
  ecf/defs/prod00.def
  ecf/defs/prod06.def
  ecf/defs/prod12.def
  ecf/defs/prod18.def
  ecf/scripts/gdas/atmos/obsproc/dump/jgdas_atmos_dump.ecf
  ecf/scripts/gdas/atmos/obsproc/dump/jgdas_atmos_dump_alert.ecf
  ecf/scripts/gdas/atmos/obsproc/dump/jgdas_atmos_dump_post.ecf
  ecf/scripts/gdas/atmos/obsproc/prep/jgdas_atmos_prep.ecf
  ecf/scripts/gdas/atmos/obsproc/prep/jgdas_atmos_prep_post.ecf
  ecf/scripts/gfs/atmos/obsproc/dump/jgfs_atmos_dump.ecf
  ecf/scripts/gfs/atmos/obsproc/dump/jgfs_atmos_dump_alert.ecf
  ecf/scripts/gfs/atmos/obsproc/dump/jgfs_atmos_dump_post.ecf
  ecf/scripts/gfs/atmos/obsproc/prep/jgfs_atmos_prep.ecf
  ecf/scripts/gfs/atmos/obsproc/prep/jgfs_atmos_prep_post.ecf
Labels: port

#606 WCOSS2 resource updates
  parm/config/config.fv3.emc.dyn
  parm/config/config.fv3.nco.static
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
Labels: port

#616 Series of small WCOSS2 updates - round 9
  docs/Release_Notes.gfs.v16.2.0.md
  ecf/scripts/enkfgdas/analysis/create/jenkfgdas_select_obs.ecf
  ecf/scripts/gdas/atmos/analysis/jgdas_atmos_analysis.ecf
  ecf/scripts/gdas/wave/prep/jgdas_wave_prep.ecf
  ecf/scripts/gfs/wave/prep/jgfs_wave_prep.ecf
  env/WCOSS2.env
  jobs/JGDAS_ATMOS_GEMPAK
  jobs/JGFS_ATMOS_GEMPAK
  jobs/JGFS_ATMOS_GEMPAK_PGRB2_SPEC
  jobs/JGLOBAL_WAVE_POST_BNDPNTBLL
  jobs/rocoto/gempak.sh
  parm/config/config.gempak
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
  scripts/exgdas_atmos_nawips.sh
  scripts/exgfs_atmos_gempak_meta.sh
  scripts/exgfs_atmos_goes_nawips.sh
  scripts/exgfs_atmos_nawips.sh
  ush/rocoto/setup_workflow.py
  ush/rocoto/setup_workflow_fcstonly.py
Labels: port

#617 Update GLDAS tag to gldas_gfsv16_release.v1.28.0
  docs/Release_Notes.gfs.v16.2.0.md
  sorc/checkout.sh
Labels: port

#620 Series of small WCOSS2 updates - round 10
  docs/Release_Notes.gfs.v16.2.0.md
  ecf/scripts/enkfgdas/analysis/create/jenkfgdas_select_obs.ecf
  ecf/scripts/enkfgdas/analysis/create/jenkfgdas_update.ecf
  ecf/scripts/gdas/atmos/analysis/jgdas_atmos_analysis.ecf
  ecf/scripts/gdas/atmos/analysis/jgdas_atmos_analysis_diag.ecf
  parm/config/config.fv3.nco.static
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
  scripts/exgfs_atmos_gempak_meta.sh
Labels: port
