Repository NOAA-EMC/global-workflow, pull requests merged in 2022-02, with the labels that each got.

#623 Analysis walltime adjustment and gempak script fix
  ecf/scripts/gdas/atmos/analysis/jgdas_atmos_analysis.ecf
  ecf/scripts/gfs/atmos/analysis/jgfs_atmos_analysis.ecf
  jobs/JGDAS_ATMOS_GEMPAK
Labels: port

#581 Stop archiving gfsarch.log as it is being written
  jobs/rocoto/arch.sh
  ush/hpssarch_gen.sh
Labels: bug

#637 Correct analysis walltimes in config.resources for WCOSS2
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
Labels: port

#663 Fold GFSv16.1.6 updates into GFSv16.2.0 package
  Externals.cfg
  docs/Release_Notes.gfs.v16.1.6.txt
  docs/Release_Notes.gfs.v16.2.0.md
  parm/config/config.anal
  ush/rocoto/setup_expt.py
  ush/rocoto/setup_expt_fcstonly.py
Labels: production update

#664 Update GLDAS tag to gldas_gfsv16_release.v.2.0.0
  Externals.cfg
  docs/Release_Notes.gfs.v16.2.0.md
  sorc/checkout.sh
Labels: port
