Repository NOAA-EMC/global-workflow, pull requests merged in 2022-05, with the labels that each got.

#773 Revert g2tmpl back to 1.10.0
  modulefiles/module_base.hera.lua
  modulefiles/module_base.orion.lua
  modulefiles/module_base.wcoss_dell_p3.lua
Labels: bug

#777 ecFlow Suite Generator Application
  ecf/defs/GFSApp.def
  workflow_generator/README.md
  workflow_generator/__init.py__
  workflow_generator/ecflow_build.yml
  workflow_generator/ecflow_setup/__init.py__
  workflow_generator/ecflow_setup/ecflow_definitions.py
  workflow_generator/ecflow_setup/ecflow_setup.py
  workflow_generator/prod.yml
  workflow_generator/setup_workflow.py
Labels: feature

#781 Add --init to GSI submodule command
  sorc/checkout.sh
Labels: bug

#779 Low resolution Orion testing updates for dev_v16
  Externals.cfg
  env/HERA.env
  env/ORION.env
  env/WCOSS2.env
  parm/config/config.base.emc.dyn
  parm/config/config.fv3.emc.dyn
  parm/config/config.prep
  parm/config/config.resources.emc.dyn
  versions/orion.ver
Labels: maintenance, port

#782 External package and serial enkf forecast updates
  parm/config/config.efcs
  parm/config/config.vrfy
  versions/hera.ver
  versions/orion.ver
  versions/wcoss2.ver
Labels: maintenance, port

#783 Update "excl" to "exclhost" for exclusive jobs on WCOSS2
  ecf/scripts/enkfgdas/analysis/create/jenkfgdas_select_obs.ecf
  ecf/scripts/enkfgdas/analysis/create/jenkfgdas_update.ecf
  ecf/scripts/enkfgdas/analysis/recenter/ecen/jenkfgdas_ecen.ecf
  ecf/scripts/enkfgdas/forecast/jenkfgdas_fcst.ecf
  ecf/scripts/enkfgdas/post/jenkfgdas_post_master.ecf
  ecf/scripts/gdas/atmos/analysis/jgdas_atmos_analysis.ecf
  ecf/scripts/gdas/atmos/analysis/jgdas_atmos_analysis_calc.ecf
  ecf/scripts/gdas/atmos/init/jgdas_atmos_gldas.ecf
  ecf/scripts/gdas/atmos/post/jgdas_atmos_post_master.ecf
  ecf/scripts/gdas/jgdas_forecast.ecf
  ecf/scripts/gfs/atmos/analysis/jgfs_atmos_analysis.ecf
  ecf/scripts/gfs/atmos/analysis/jgfs_atmos_analysis_calc.ecf
  ecf/scripts/gfs/atmos/post/jgfs_atmos_post_master.ecf
  ecf/scripts/gfs/atmos/post_processing/bufr_sounding/jgfs_atmos_postsnd.ecf
  ecf/scripts/gfs/jgfs_forecast.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_post_bndpnt.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_post_bndpntbll.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_postpnt.ecf
  ush/rocoto/workflow_utils.py
Labels: production update, maintenance

#792 Final pre-production freeze updates for GFSv16.2.0 package on WCOSS2
  docs/Release_Notes.gfs.v16.2.0.md
  ecf/scripts/gdas/atmos/analysis/jgdas_atmos_analysis_calc.ecf
  modulefiles/modulefile.fv3nc2nemsio.wcoss2.lua
  parm/config/config.analcalc
  parm/config/config.efcs
  parm/config/config.fv3.nco.static
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
  sorc/build_enkf_chgres_recenter.sh
  sorc/build_enkf_chgres_recenter_nc.sh
  sorc/fbwndgfs.fd/makefile.GENERIC
  sorc/gaussian_sfcanl.fd/makefile.sh
  sorc/supvit.fd/makefile
  ush/gfs_bufr.sh
  util/sorc/mkgfsawps.fd/makefile.wcoss2
  util/sorc/overgridid.fd/makefile
  util/sorc/rdbfmsua.fd/makefile.wcoss2
  util/sorc/webtitle.fd/makefile
Labels: bug, production update, maintenance

#693 Add continuous aerosols support
  jobs/rocoto/aerosol_init.sh
  jobs/rocoto/anal.sh
  jobs/rocoto/analcalc.sh
  jobs/rocoto/analdiag.sh
  jobs/rocoto/awips.sh
  jobs/rocoto/earc.sh
  jobs/rocoto/ecen.sh
  jobs/rocoto/echgres.sh
  jobs/rocoto/ediag.sh
  jobs/rocoto/efcs.sh
  jobs/rocoto/eobs.sh
  jobs/rocoto/eomg.sh
  jobs/rocoto/epos.sh
  jobs/rocoto/esfc.sh
  jobs/rocoto/eupd.sh
  jobs/rocoto/fcst.sh
  jobs/rocoto/gempak.sh
  jobs/rocoto/getic.sh
  jobs/rocoto/gldas.sh
  jobs/rocoto/init.sh
  jobs/rocoto/metp.sh
  jobs/rocoto/ocnpost.sh
  jobs/rocoto/post.sh
  jobs/rocoto/postsnd.sh
  jobs/rocoto/prep.sh
  jobs/rocoto/vrfy.sh
  jobs/rocoto/wafs.sh
  jobs/rocoto/wafsblending.sh
  jobs/rocoto/wafsblending0p25.sh
  jobs/rocoto/wafsgcip.sh
  jobs/rocoto/wafsgrib2.sh
  jobs/rocoto/wafsgrib20p25.sh
  jobs/rocoto/waveawipsbulls.sh
  jobs/rocoto/waveawipsgridded.sh
  jobs/rocoto/wavegempak.sh
  jobs/rocoto/waveinit.sh
  jobs/rocoto/wavepostbndpnt.sh
  jobs/rocoto/wavepostbndpntbll.sh
  jobs/rocoto/wavepostpnt.sh
  jobs/rocoto/wavepostsbs.sh
  jobs/rocoto/waveprep.sh
  modulefiles/module_base.hera.lua
  modulefiles/module_base.orion.lua
  modulefiles/module_base.wcoss_dell_p3.lua
  parm/chem/ExtData.gbbepx
  parm/config/config.aerosol_init
  parm/config/config.base.emc.dyn
  parm/config/config.fcst
  parm/config/config.resources
  scripts/exgfs_aero_init_aerosol.py
  scripts/run_regrid.sh
  sorc/checkout.sh
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
  ush/icepost.ncl
  ush/merge_fv3_aerosol_tile.py
  ush/ocnpost.ncl
  ush/rocoto/setup_workflow_fcstonly.py
Labels: feature

#794 Refactor some build scripts
  sorc/build_all.sh
  sorc/build_ufs.sh
  sorc/gfs_build.cfg
  sorc/partial_build.sh
Labels: feature

#799 WCOSS2 GFSv16.2.0 resource updates and NHC change
  docs/Release_Notes.gfs.v16.2.0.md
  ecf/scripts/gdas/atmos/gempak/jgdas_atmos_gempak.ecf
  ecf/scripts/gdas/atmos/post/jgdas_atmos_post_master.ecf
  ecf/scripts/gfs/atmos/post_processing/awips_20km_1p0/jgfs_atmos_awips_master.ecf
  ecf/scripts/gfs/atmos/post_processing/awips_g2/jgfs_atmos_awips_g2_master.ecf
  ecf/scripts/gfs/atmos/post_processing/bufr_sounding/jgfs_atmos_postsnd.ecf
  ecf/scripts/gfs/atmos/post_processing/bulletins/jgfs_atmos_fbwind.ecf
  env/WCOSS2.env
  jobs/JGLOBAL_ATMOS_TROPCY_QC_RELOC
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
Labels: production update

#801 Fix build script options
  sorc/build_all.sh
  sorc/partial_build.sh
Labels: bug

#806 Sync feature/ops-wcoss2 into dev_v16
  docs/Release_Notes.gfs.v16.2.0.md
  ecf/scripts/gdas/atmos/gempak/jgdas_atmos_gempak.ecf
  ecf/scripts/gdas/atmos/post/jgdas_atmos_post_master.ecf
  ecf/scripts/gfs/atmos/post_processing/awips_20km_1p0/jgfs_atmos_awips_master.ecf
  ecf/scripts/gfs/atmos/post_processing/awips_g2/jgfs_atmos_awips_g2_master.ecf
  ecf/scripts/gfs/atmos/post_processing/bufr_sounding/jgfs_atmos_postsnd.ecf
  ecf/scripts/gfs/atmos/post_processing/bulletins/jgfs_atmos_fbwind.ecf
  env/WCOSS2.env
  jobs/JGLOBAL_ATMOS_TROPCY_QC_RELOC
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
Labels: production update, maintenance

#805 Correct incorrect increment prefix variable
  ush/forecast_postdet.sh
Labels: bug

#795 Updated the geographical static data, ICs, SDFs and namelist settings in CCPP for p8c
  parm/config/config.coupled_ic
  parm/config/config.fcst
  parm/parm_fv3diag/diag_table
  parm/parm_fv3diag/diag_table_cpl
  parm/parm_fv3diag/diag_table_da
  parm/parm_fv3diag/diag_table_da_gsd
  parm/parm_fv3diag/diag_table_gsd
  parm/parm_fv3diag/diag_table_gsd_ruc
  sorc/build_ufs.sh
  sorc/checkout.sh
  ush/parsing_namelists_FV3.sh
Labels: feature
