Repository NOAA-EMC/global-workflow, pull requests merged in 2023-03, with the labels that each got.

#1363 Add options while setting up Rocoto XML that are useful for CI
  docs/source/setup.rst
  workflow/rocoto/workflow_xml.py
  workflow/setup_xml.py
Labels: feature

#1358 Add dependency on gdasanal job to gdasfcst and gdasgldas jobs
  ush/rocoto/setup_workflow.py
Labels: bug

#1369 Release/gfs.v16.3.7
  Externals.cfg
  docs/Release_Notes.gfs.v16.3.7.md
  sorc/checkout.sh
  versions/run.ver
Labels: production update

#1362 Add BASH scripts for initial CI testing system using GitHub Labels
  ci/driver.sh
  ci/hera.sh
  ci/orion.sh
  ci/run_ci.sh
Labels: Hera-Passed

#1376 Update initial condition documentation and Orion BASE_CPLIC path
  docs/source/init.rst
  parm/config/config.coupled_ic
Labels: documentation, maintenance

#1407 GFSv16.3.7 - EUMETSAT switch from Meteosat-10 for Meteosat-11
  Externals.cfg
  docs/Release_Notes.gfs.v16.3.7.md
  sorc/checkout.sh
  versions/run.ver
Labels: production update

#1414 Created branch to clean up some minor things in pygw/yaml_file.py.
  ush/python/pygw/src/pygw/yaml_file.py
Labels: feature

#1417 Update state of operations in RTD to GFSv16.3.7
  docs/source/index.rst
Labels: documentation, production update

#1424 Have aerostat tar file extract to basename only
  ush/python/pygfs/task/aero_analysis.py
Labels: bug

#1404 GFSv16.3.5[6] GSI updates
  Externals.cfg
  scripts/exglobal_atmos_analysis.sh
  sorc/build_gsi_enkf.sh
  sorc/checkout.sh
Labels: production update, maintenance

#1437 Remove para module paths for ncdiag on WCOSS2
  Externals.cfg
  modulefiles/module_base.wcoss2.lua
  sorc/checkout.sh
Labels: production update, maintenance
