Repository NOAA-EMC/global-workflow, pull requests merged in 2023-01, with the labels that each got.

#1208 Fix bugs in forecast-only mode (GFSv16)
  jobs/rocoto/arch.sh
  parm/config/config.base.emc.dyn
  ush/hpssarch_gen.sh
  ush/rocoto/setup_expt.py
  ush/rocoto/setup_expt_fcstonly.py
Labels: bug

#1261 Remove incorrect/misleading comments in config.base
  parm/config/config.base.emc.dyn
  parm/config/config.base.nco.static
Labels: bug

#1267 Retire ecf versions files in develop
  ecf/versions/gfs.ver
  ecf/versions/obsproc.ver
  ecf/versions/obsproc_global.ver
Labels: maintenance

#1268 Retire ecf versions files in v16 branch
  ecf/versions/gfs.ver
  ecf/versions/obsproc.ver
  ecf/versions/obsproc_global.ver
Labels: maintenance

#1203 Make needed updates to run forecast from GEFS
  parm/config/config.base.emc.dyn
  parm/config/config.resources
  scripts/exgdas_enkf_fcst.sh
  scripts/exglobal_forecast.sh
  ush/forecast_det.sh
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
  workflow/rocoto/workflow_tasks.py
Labels: feature, GEFS

#1285 Correct issue in linking final restart files
  ush/forecast_predet.sh
Labels: bug

#1287 Updates to RTD documentation based on full review
  docs/source/clone.rst
  docs/source/components.rst
  docs/source/configure.rst
  docs/source/development.rst
  docs/source/errors_faq.rst
  docs/source/hpc.rst
  docs/source/index.rst
  docs/source/init.rst
  docs/source/jobs.rst
  docs/source/monitor_rocoto.rst
  docs/source/run.rst
  docs/source/setup.rst
  docs/source/start.rst
  docs/source/view.rst
Labels: maintenance

#1293 Update obsproc package version to v1.1.2
  parm/config/config.base.emc.dyn
  parm/config/config.base.nco.static
Labels: maintenance
