Repository NOAA-EMC/global-workflow, pull requests merged in 2023-07, with the labels that each got.

#1726 Updates for deprecated numpy versions.
  workflow/rocoto/tasks.py
Labels: bug

#1724 updating pythonpath in JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP to match changes to ioda
  jobs/JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP
Labels: CI-Hera-Passed, CI-Orion-Failed

#1731 Add GEFS atm-only fcst job support
  jobs/JGLOBAL_FORECAST
  parm/config/gefs/config.base.emc.dyn
  parm/config/gefs/config.efcs
  parm/config/gefs/config.fcst
  parm/config/gefs/config.resources
Labels: CI-Hera-Passed

#1719 Update fit2obs for COM refactor
  jobs/JGDAS_FIT2OBS
  parm/config/gfs/config.base.emc.dyn
  scripts/exglobal_archive.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1737 Move nems.configure templates to `parm/ufs`
  .gitignore
  parm/config/gefs/config.resources
  parm/config/gefs/config.ufs
  parm/config/gfs/config.resources
  parm/config/gfs/config.ufs
  parm/ufs/nems.configure.atm.IN
  parm/ufs/nems.configure.atm_aero.IN
  parm/ufs/nems.configure.blocked_atm_wav.IN
  parm/ufs/nems.configure.cpld.IN
  parm/ufs/nems.configure.cpld_aero.IN
  parm/ufs/nems.configure.cpld_aero_outerwave.IN
  parm/ufs/nems.configure.cpld_aero_wave.IN
  parm/ufs/nems.configure.cpld_outerwave.IN
  parm/ufs/nems.configure.cpld_wave.IN
  parm/ufs/nems.configure.leapfrog_atm_wav.IN
  scripts/exglobal_forecast.sh
  sorc/link_workflow.sh
  ush/forecast_postdet.sh
  ush/nems_configure.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1740 GitHub Workflow Pipeline
  .github/workflows/globalworkflow-ci.yaml
  ci/scripts/run-check_ci.sh
Labels: CI/CD

#1757 Fix CI driver
  ci/scripts/driver.sh
Labels: CI-Orion-Passed, CI/CD

#1753 Fix `SDATE_GFS` issue in cycled and forecast-only modes
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#1687 Update snow DA cycling for the fractional grid setting.
  Externals.cfg
  jobs/rocoto/preplandobs.sh
  parm/config/gfs/config.landanl
  sorc/checkout.sh
  ush/python/pygfs/task/land_analysis.py
Labels: CI-Orion-Passed

#1759 Add atm-only test for CI
  ci/cases/C48_ATM.yaml
Labels: CI-Hera-Passed, CI-Orion-Passed

#1755 Support coupled GEFS forecast, use mem000 for GEFS control
  jobs/rocoto/ocnpost.sh
  parm/config/gefs/config.aero
  parm/config/gefs/config.base.emc.dyn
  parm/config/gefs/config.defaults.s2sw
  parm/config/gefs/config.efcs
  parm/config/gefs/config.ice
  parm/config/gefs/config.ocn
  parm/config/gefs/config.wave
  parm/config/gfs/config.aero
  parm/config/gfs/config.defaults.s2sw
  scripts/exgdas_enkf_earc.sh
  scripts/exgdas_enkf_fcst.sh
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1761 Prepare GTS snow depth observations for JEDI-based Land DA
  Externals.cfg
  parm/config/gfs/config.preplandobs
  scripts/exglobal_prep_land_obs.py
  sorc/checkout.sh
  sorc/link_workflow.sh
  ush/python/pygfs/task/land_analysis.py
  workflow/rocoto/gfs_cycled_xml.py
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#1763 Small changes to get (aerosol) cycling going at C384
  parm/config/gfs/config.resources
  parm/config/gfs/config.ufs
  ush/python/pygfs/task/aero_analysis.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#1697 Add soil color data and change the way to read in Noah-MP parameter table
  .gitignore
  Externals.cfg
  parm/ufs/fix/gfs/land.fixed_files.yaml
  sorc/build_ufs.sh
  sorc/checkout.sh
  sorc/link_workflow.sh
  ush/forecast_postdet.sh
  ush/parsing_namelists_FV3.sh
  versions/fix.ver
Labels: CI-Hera-Passed, CI-Orion-Passed

#1767 Move UFS parm directories into `parm/ufs/`
  parm/config/gefs/config.fcst
  parm/config/gfs/config.aero
  parm/config/gfs/config.efcs
  parm/config/gfs/config.fcst
  parm/ufs/chem/AERO.rc
  parm/ufs/chem/AERO_HISTORY.rc
  parm/ufs/chem/AGCM.rc
  parm/ufs/chem/CA2G_instance_CA.bc.rc
  parm/ufs/chem/CA2G_instance_CA.br.rc
  parm/ufs/chem/CA2G_instance_CA.oc.rc
  parm/ufs/chem/CAP.rc
  parm/ufs/chem/DU2G_instance_DU.rc
  parm/ufs/chem/ExtData.gbbepx
  parm/ufs/chem/ExtData.none
  parm/ufs/chem/ExtData.other
  parm/ufs/chem/ExtData.qfed
  parm/ufs/chem/GOCART2G_GridComp.rc
  parm/ufs/chem/NI2G_instance_NI.rc
  parm/ufs/chem/SS2G_instance_SS.rc
  parm/ufs/chem/SU2G_instance_SU.rc
  parm/ufs/chem/gocart_tracer.list
  parm/ufs/fv3/data_table
  parm/ufs/fv3/diag_table
  parm/ufs/fv3/diag_table.aero
  parm/ufs/fv3/diag_table_aod
  parm/ufs/fv3/diag_table_da
  parm/ufs/fv3/diag_table_da_orig
  parm/ufs/fv3/field_table
  parm/ufs/fv3/field_table.aero
  parm/ufs/fv3/field_table_gfdl
  parm/ufs/fv3/field_table_gfdl_progsigma
  parm/ufs/fv3/field_table_gfdl_satmedmf
  parm/ufs/fv3/field_table_gfdl_satmedmf_progsigma
  parm/ufs/fv3/field_table_thompson
  parm/ufs/fv3/field_table_thompson_aero_tke
  parm/ufs/fv3/field_table_thompson_noaero_tke
  parm/ufs/fv3/field_table_thompson_noaero_tke_progsigma
  parm/ufs/fv3/field_table_thompson_satmedmf
  parm/ufs/fv3/field_table_wsm6
  parm/ufs/fv3/field_table_wsm6_progsigma
  parm/ufs/fv3/field_table_wsm6_satmedmf
  parm/ufs/fv3/field_table_wsm6_satmedmf_progsigma
  parm/ufs/fv3/field_table_zhaocarr
  parm/ufs/fv3/field_table_zhaocarr_progsigma
  parm/ufs/fv3/field_table_zhaocarr_satmedmf
  parm/ufs/fv3/field_table_zhaocarr_satmedmf_progsigma
  parm/ufs/fv3/variable_table.txt
  parm/ufs/fv3/variable_table_da.txt
  parm/ufs/fv3/variable_table_da_nonsst.txt
  parm/ufs/mom6/MOM_input_template_025
  parm/ufs/mom6/MOM_input_template_050
  parm/ufs/mom6/MOM_input_template_100
  parm/ufs/mom6/MOM_input_template_500
  ush/forecast_predet.sh
  ush/parsing_namelists_FV3.sh
  ush/parsing_namelists_MOM6.sh
Labels: CI-Hera-Passed, CI-Orion-Passed
