Repository NOAA-EMC/global-workflow, pull requests merged in 2023-09, with the labels that each got.

#1834 Fix bufr sounding job
  Externals.cfg
  scripts/exgfs_atmos_postsnd.sh
  sorc/checkout.sh
  ush/gfs_bufr.sh
Labels: bug, CI-Hera-Passed, CI-Orion-Passed

#1835 Fix eupd after GSI PR 602
  Externals.cfg
  scripts/exgdas_enkf_update.sh
  sorc/checkout.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1844 Introducing weekly vs pr cases for CI
  ci/cases/pr/C48_ATM.yaml
  ci/cases/pr/C48_S2S.yaml
  ci/cases/pr/C48_S2SA_gefs.yaml
  ci/cases/pr/C96C48_hybatmDA.yaml
  ci/cases/pr/C96_atm3DVar.yaml
  ci/cases/weekly/C384C192_hybatmda.yaml
  ci/cases/weekly/C384_atm3DVar.yaml
  ci/scripts/driver.sh
Labels: CI-Orion-Passed, CI/CD

#1848 ARFC GFSv16.3.8 - add debug flag to resolve wave post runtimes
  docs/Release_Notes.gfs.v16.3.8.md
  ecf/scripts/gfs/wave/post/jgfs_wave_post_bndpnt.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_post_bndpntbll.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_postpnt.ecf
  versions/run.ver
Labels: production update

#1849 ARFC GFSv16.3.8 - add debug flag to resolve wave post runtimes
  docs/Release_Notes.gfs.v16.3.8.md
  ecf/scripts/gfs/wave/post/jgfs_wave_post_bndpnt.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_post_bndpntbll.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_postpnt.ecf
  versions/run.ver
Labels: production update

#1806 Convert IC staging job into a proper j-job
  jobs/JGLOBAL_STAGE_IC
  jobs/rocoto/stage_ic.sh
  parm/config/gfs/config.resources
  parm/config/gfs/config.stage_ic
  scripts/exglobal_stage_ic.sh
  workflow/applications/gfs_forecast_only.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#1852 GFSv16.3.9 - temporary satingest changes for NOAA-21
  Externals.cfg
  docs/Release_Notes.gfs.v16.3.9.md
  modulefiles/modulefile.storm_reloc_v6.0.0.wcoss2.lua
  sorc/build_tropcy_NEMS.sh
  sorc/checkout.sh
  versions/run.ver
Labels: production update

#1853 Update index.rst for new GFS version in operations
  docs/source/index.rst
Labels: production update

#1858 Update gsi analysis script and fix files with gfs v16.3.9 changes.
  scripts/exglobal_atmos_analysis.sh
  versions/fix.ver
Labels: CI-Hera-Passed, CI-Orion-Passed

#1822 Simplify downstream atmos product generation scripts
  env/HERA.env
  env/JET.env
  env/ORION.env
  env/S4.env
  env/WCOSS2.env
  jobs/JGLOBAL_ATMOS_POST
  ush/fv3gfs_downstream_nems.sh
  ush/fv3gfs_dwn_nems.sh
  ush/mod_icec.sh
  ush/run_mpmd.sh
  ush/trim_rh.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1859 Fix post octal bugs
  scripts/exgfs_atmos_post.sh
  ush/gfs_transfer.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1860 Create release notes and update version numbers for GFSv16.3.10 upgrade
  docs/Release_Notes.gfs.v16.3.10.md
  versions/hera.ver
  versions/orion.ver
  versions/run.ver
  versions/wcoss2.ver
Labels: production update

#1869 BASH GitHub CLI version of High Resolution cases used for CI weekly tests
  ci/cases/weekly/C384C192_hybatmda.yaml
  ci/cases/weekly/C384_atm3DVar.yaml
  ci/scripts/driver_weekly.sh
Labels: CI/CD

#1880 bugfixes to weekly_pr_CI PR
  ci/scripts/driver_weekly.sh
Labels: bug, CI/CD

#1883 Update main CI driver to remove previous RUNDIR
  ci/platforms/hera.sh
  ci/platforms/orion.sh
  ci/scripts/driver.sh
Labels: bug, CI/CD

#1885 Fix IC linking in setup_expt.py
  workflow/setup_expt.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#1886 Update aero analysis for new bump files and archive aero diags
  jobs/JGLOBAL_ARCHIVE
  scripts/exglobal_archive.sh
  ush/hpssarch_gen.sh
  ush/python/pygfs/task/aero_analysis.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#1888 Fix wavepostbndpntbll data dependency
  workflow/rocoto/gfs_tasks.py
Labels: bug

#1893 Fix a few bugs reported by devs
  jobs/JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT
  jobs/JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP
  jobs/JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY
  jobs/JGLOBAL_AERO_ANALYSIS_FINALIZE
  jobs/JGLOBAL_AERO_ANALYSIS_INITIALIZE
  jobs/JGLOBAL_ATMENS_ANALYSIS_INITIALIZE
  jobs/JGLOBAL_ATM_ANALYSIS_FINALIZE
  jobs/JGLOBAL_ATM_ANALYSIS_INITIALIZE
  jobs/JGLOBAL_FORECAST
  jobs/JGLOBAL_LAND_ANALYSIS
  jobs/JGLOBAL_PREP_LAND_OBS
  scripts/exglobal_stage_ic.sh
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
  ush/nems_configure.sh
  ush/parsing_namelists_FV3.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1891 Move product functions to separate script
  jobs/JGFS_ATMOS_AWIPS_20KM_1P0DEG
  jobs/rocoto/awips.sh
  scripts/exgdas_atmos_post.sh
  scripts/exgfs_atmos_awips_20km_1p0deg.sh
  scripts/exgfs_atmos_grib_awips.sh
  scripts/exgfs_atmos_nawips.sh
  scripts/exgfs_atmos_post.sh
  ush/fv3gfs_dwn_nems.sh
  ush/product_functions.sh
  ush/scale_dec.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1876 Merge S2S defaults config back into other configs
  parm/config/gefs/config.base.emc.dyn
  parm/config/gefs/config.defaults.s2sw
  parm/config/gfs/config.arch
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.defaults.s2sw
  parm/config/gfs/config.ice
  parm/config/gfs/config.ocnpost
  parm/config/gfs/config.wave
  ush/hpssarch_gen.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1896 Ci rename platform scripts
  ci/platforms/config.hera
  ci/platforms/config.orion
  ci/scripts/check_ci.sh
  ci/scripts/driver.sh
  ci/scripts/driver_weekly.sh
Labels: CI/CD

#1895 Add coupled forecast-only tests for S2S and S2SW
  ci/cases/pr/C48_S2SW.yaml
  ci/cases/weekly/C384_S2SWA.yaml
Labels: CI-Hera-Passed, CI-Orion-Passed

#1882 Update module loads to intel/2022 for jobs running gsi.x and enkf.x
  Externals.cfg
  jobs/rocoto/anal.sh
  jobs/rocoto/eobs.sh
  jobs/rocoto/eupd.sh
  sorc/checkout.sh
Labels: CI-Hera-Passed, CI-Orion-Passed
