Repository NOAA-EMC/global-workflow, pull requests merged in 2023-10, with the labels that each got.

#1901 Update vrfy.sh to only run MINMON in cycled mode
  jobs/rocoto/vrfy.sh
Labels: bug

#1894 Use deterministic marine resolutions for ensemble
  parm/config/gefs/config.base.emc.dyn
  parm/config/gefs/config.efcs
  parm/config/gfs/config.efcs
Labels: CI-Hera-Passed, CI-Orion-Passed

#1900 Change metp dependency
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#1899 CI driver_weekly bugfix deleting new branch if is already on repo
  ci/scripts/driver_weekly.sh
  ci/scripts/run_ci.sh
Labels: CI/CD

#1914 Update ufs-weather-model tag and add prelude to release notes for GFSv16.3.10
  Externals.cfg
  docs/Release_Notes.gfs.v16.3.10.md
  sorc/checkout.sh
Labels: production update

#1915 Updated cron bash ci script to remove weekly CI test PR on success
  ci/scripts/check_ci.sh
Labels: CI/CD

#1928 Update to new implementation version v16.3.11
  docs/Release_Notes.gfs.v16.3.11.md
  versions/run.ver
Labels: production update

#1926 Fix missing pipe in check_ci
  ci/scripts/check_ci.sh
Labels: bug, CI/CD

#1922 Marine DA configuration updates
  parm/config/gfs/config.resources
  parm/config/gfs/config.ufs
  parm/ufs/mom6/MOM_input_template_025
  parm/ufs/mom6/MOM_input_template_500
Labels: CI-Hera-Passed, CI-Orion-Passed

#1927 Update nth_eupd to 8 for Orion
  parm/config/gefs/config.resources
Labels: CI-Hera-Passed, CI-Orion-Passed

#1929 Remove SENDCOM
  jobs/JGDAS_ATMOS_GEMPAK
  jobs/JGDAS_ATMOS_GEMPAK_META_NCDC
  jobs/JGFS_ATMOS_AWIPS_20KM_1P0DEG
  jobs/JGFS_ATMOS_AWIPS_G2
  jobs/JGFS_ATMOS_CYCLONE_GENESIS
  jobs/JGFS_ATMOS_CYCLONE_TRACKER
  jobs/JGFS_ATMOS_FBWIND
  jobs/JGFS_ATMOS_FSU_GENESIS
  jobs/JGFS_ATMOS_GEMPAK
  jobs/JGFS_ATMOS_GEMPAK_META
  jobs/JGFS_ATMOS_GEMPAK_NCDC_UPAPGIF
  jobs/JGFS_ATMOS_GEMPAK_PGRB2_SPEC
  jobs/JGFS_ATMOS_PGRB2_SPEC_NPOESS
  jobs/JGFS_ATMOS_POSTSND
  jobs/JGLOBAL_WAVE_GEMPAK
  jobs/JGLOBAL_WAVE_INIT
  jobs/JGLOBAL_WAVE_PRDGEN_BULLS
  jobs/JGLOBAL_WAVE_PRDGEN_GRIDDED
  parm/config/gefs/config.base.emc.dyn
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.post
  parm/config/gfs/config.prep
  parm/config/gfs/config.waveawipsbulls
  parm/config/gfs/config.waveawipsgridded
  parm/config/gfs/config.wavegempak
  scripts/exgdas_atmos_nawips.sh
  scripts/exgdas_atmos_post.sh
  scripts/exgfs_atmos_awips_20km_1p0deg.sh
  scripts/exgfs_atmos_fbwind.sh
  scripts/exgfs_atmos_gempak_gif_ncdc_skew_t.sh
  scripts/exgfs_atmos_goes_nawips.sh
  scripts/exgfs_atmos_grib2_special_npoess.sh
  scripts/exgfs_atmos_grib_awips.sh
  scripts/exgfs_atmos_nawips.sh
  scripts/exgfs_atmos_post.sh
  scripts/exgfs_wave_nawips.sh
  scripts/exgfs_wave_prdgen_bulls.sh
  scripts/exgfs_wave_prdgen_gridded.sh
  ush/gfs_sndp.sh
  ush/syndat_qctropcy.sh
  ush/tropcy_relocate.sh
  ush/wave_grib2_sbs.sh
  ush/wave_grid_interp_sbs.sh
  ush/wave_prnc_ice.sh
  ush/wave_tar.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1950 Update GFS version and add release notes
  docs/Release_Notes.gfs.v16.3.10.md
  versions/run.ver
Labels: production update

#1962 Sync merge GFSv16.3.11 release branch with GFSv16.3.10 updates
  docs/Release_Notes.gfs.v16.3.10.md
Labels: production update

#1956 Optimize the checkout script
  sorc/checkout.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1971 Set SENDCOM=YES for tracker/genesis tasks
  parm/config/gfs/config.vrfy
Labels: bug

#1970 Updates for NOAA CSP AWS global-workflow related file paths.
  docs/source/noaa_csp.rst
Labels: bug, documentation

#1964 Build GDASapp for CI tests
  ci/scripts/check_ci.sh
  ci/scripts/clone-build_ci.sh
Labels: CI/CD

#1966 Fix path for marine products
  jobs/rocoto/ocnpost.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1976 Update GFS version in index.rst to v16.3.10
  docs/source/index.rst
Labels: documentation

#1933 Update ufs model to version from 10-12-23
  Externals.cfg
  env/WCOSS2.env
  jobs/rocoto/efcs.sh
  jobs/rocoto/fcst.sh
  jobs/rocoto/waveinit.sh
  jobs/rocoto/wavepostbndpnt.sh
  jobs/rocoto/wavepostbndpntbll.sh
  jobs/rocoto/wavepostpnt.sh
  jobs/rocoto/wavepostsbs.sh
  jobs/rocoto/waveprep.sh
  parm/config/gefs/config.base.emc.dyn
  parm/config/gfs/config.resources
  parm/ufs/chem/CAP.rc
  parm/ufs/chem/GOCART2G_GridComp.rc
  parm/ufs/nems.configure.cpld.IN
  parm/ufs/nems.configure.cpld_aero.IN
  parm/ufs/nems.configure.cpld_aero_outerwave.IN
  parm/ufs/nems.configure.cpld_aero_wave.IN
  parm/ufs/nems.configure.cpld_outerwave.IN
  parm/ufs/nems.configure.cpld_wave.IN
  scripts/exglobal_forecast.sh
  sorc/checkout.sh
  ush/forecast_postdet.sh
  ush/load_ufswm_modules.sh
  ush/nems_configure.sh
  ush/parsing_namelists_FV3.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1967 Test tarballs for rstprod before calling chgrp
  scripts/exgdas_enkf_earc.sh
  scripts/exglobal_archive.sh
Labels: CI-Hera-Passed

#1975 Update GDASApp hash
  Externals.cfg
  sorc/checkout.sh
Labels: CI-Hera-Passed

#1892 GEFS Staging in exglobal_stage_ic
  parm/config/gefs/config.base.emc.dyn
  parm/config/gefs/config.coupled_ic
  parm/config/gefs/config.resources
  parm/config/gefs/config.stage_ic
  parm/config/gfs/config.stage_ic
  scripts/exglobal_stage_ic.sh
  workflow/applications/gefs.py
  workflow/hosts/hera.yaml
  workflow/hosts/wcoss2.yaml
  workflow/rocoto/gefs_tasks.py
  workflow/rocoto/gfs_tasks.py
  workflow/setup_expt.py
Labels: CI-Hera-Passed, CI-Orion-Running

#1954 Make the early cycle work with the coupled UFS configured as S2S
  jobs/JGLOBAL_FORECAST
  jobs/JGLOBAL_STAGE_IC
  scripts/exglobal_stage_ic.sh
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Passed

#1985 Add ocean analysis files to HPSS archiving task
  jobs/JGLOBAL_ARCHIVE
  scripts/exglobal_archive.sh
  ush/hpssarch_gen.sh
Labels: CI-Hera-Passed

#1991 Add initial C96/1 deg coupled model support
  parm/config/gefs/config.ufs
  parm/config/gfs/config.ocn
  parm/config/gfs/config.resources
  parm/config/gfs/config.ufs
  parm/ufs/mom6/MOM_input_template_100
  ush/parsing_namelists_MOM6.sh
Labels: CI-Hera-Passed

#2001 Allow CI case to exclude running on certain platforms
  workflow/create_experiment.py
Labels: CI/CD

#1974 Add output error log to user for create_experiment.py on fail in CI
  ci/scripts/driver.sh
  workflow/create_experiment.py
Labels: CI/CD

#1998 Parallelize the build scripts
  sorc/build_all.sh
  sorc/build_gdas.sh
  sorc/build_gfs_utils.sh
  sorc/build_gsi_enkf.sh
  sorc/build_gsi_monitor.sh
  sorc/build_gsi_utils.sh
  sorc/build_ufs.sh
  sorc/build_ufs_utils.sh
  sorc/build_upp.sh
  sorc/build_ww3prepost.sh
  sorc/checkout.sh
  sorc/gfs_build.cfg
  sorc/partial_build.sh
Labels: CI-Hera-Passed, CI-Orion-Passed
