Repository NOAA-EMC/global-workflow, pull requests merged in 2023-04, with the labels that each got.

#1442 Add logging level to logger
  ush/python/pygw/src/pygw/logger.py
Labels: feature

#1456 Move Fit2Obs to stand-alone job
  env/HERA.env
  env/JET.env
  env/ORION.env
  env/S4.env
  env/WCOSS2.env
  jobs/JGDAS_FIT2OBS
  jobs/rocoto/fit2obs.sh
  jobs/rocoto/vrfy.sh
  parm/config/config.base.emc.dyn
  parm/config/config.fit2obs
  parm/config/config.resources
  parm/config/config.vrfy
  workflow/applications.py
  workflow/rocoto/workflow_tasks.py
Labels: feature, maintenance

#1301 Port the global workflow to Jet
  docs/note_fixfield.txt
  docs/source/components.rst
  docs/source/hpc.rst
  docs/source/init.rst
  docs/source/setup.rst
  env/JET.env
  jobs/rocoto/vrfy.sh
  modulefiles/module-setup.sh.inc
  modulefiles/module_base.jet.lua
  parm/config/config.aero
  parm/config/config.coupled_ic
  parm/config/config.metp
  parm/config/config.resources
  parm/config/config.vrfy
  sorc/build_all.sh
  sorc/checkout.sh
  ush/detect_machine.sh
  ush/load_fv3gfs_modules.sh
  workflow/hosts/jet.yaml
Labels: port

#1484 Fit2Obs updates for package reorganization and invocation via module
  jobs/JGDAS_FIT2OBS
  modulefiles/module_base.hera.lua
  modulefiles/module_base.jet.lua
  modulefiles/module_base.orion.lua
  modulefiles/module_base.wcoss2.lua
  parm/config/config.fit2obs
Labels: feature, maintenance

#1495 Create fix file issue template
  .github/ISSUE_TEMPLATE/fix_file.md
Labels: Fix Files

#1544 Fix ocean anl path in staging
  workflow/setup_expt.py
Labels: bug
