Repository NOAA-EMC/global-workflow, pull requests merged in 2023-06, with the labels that each got.

#1653 Add support for waves at low resolution
  docs/source/wave.rst
  parm/config/gefs/config.base.emc.dyn
  parm/config/gefs/config.ufs
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.ufs
  parm/config/gfs/config.wave
  parm/mom6/MOM_input_template_500
  parm/wave/ww3_grib2.glo_200.inp.tmpl
  parm/wave/ww3_grib2.glo_500.inp.tmpl
  scripts/exgfs_wave_post_gridded_sbs.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1661 Update pyenv on Hera and Orion
  modulefiles/module_base.hera.lua
  modulefiles/module_base.orion.lua
Labels: CI-Hera-Passed, CI-Orion-Passed

#1665 Correct dependencies for Ocean restarts at 0.25 degree and other resolutions
  workflow/rocoto/gfs_tasks.py
Labels: CI-Orion-Failed

#1676 Add new python-based offline UPP
  env/HERA.env
  env/JET.env
  env/ORION.env
  env/S4.env
  env/WCOSS2.env
  jobs/JGLOBAL_ATMOS_UPP
  jobs/rocoto/upp.sh
  parm/config/gfs/config.resources
  parm/config/gfs/config.upp
  parm/post/itag.jinja
  parm/post/upp.yaml
  scripts/exglobal_atmos_upp.py
  ush/python/pygfs/task/upp.py
  ush/python/pygw/src/pygw/file_utils.py
  ush/python/pygw/src/pygw/fsutils.py
  ush/python/pygw/src/pygw/jinja.py
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#1670 Use test cases from PR for CI
  ci/cases/C48_S2S.yaml
  ci/scripts/check_ci.sh
  ci/scripts/driver.sh
  ci/scripts/pr_list_database.py
  ci/scripts/run_ci.sh
Labels: CI-Hera-Passed, CI/CD

#1685 Update README.md badges based on PR CI Labels
  .github/workflows/hera.yaml
  .github/workflows/orion.yaml
  README.md
Labels: CI/CD

#1690 Update UFS hash and update compile signature
  .github/workflows/hera.yaml
  .github/workflows/orion.yaml
  Externals.cfg
  README.md
  sorc/build_ufs.sh
  sorc/build_upp.sh
  sorc/build_ww3prepost.sh
  sorc/checkout.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1689 Fix wave gridded post logic for glo_025
  parm/config/gfs/config.wave
Labels: CI-Hera-Passed, CI-Orion-Passed

#1708 Add AWS functionality to workflow setup and forecast job
  env/AWSPW.env
  jobs/rocoto/fcst.sh
  sorc/build_ufs.sh
  ush/detect_machine.sh
  ush/module-setup.sh
  workflow/hosts.py
  workflow/hosts/awspw.yaml
Labels: CI-Orion-Passed

#1705 Fix early-cycle analysis bug
  scripts/exgdas_enkf_ecen.sh
  scripts/exgdas_enkf_update.sh
Labels: CI-Hera-Passed

#1712 Fix octal bug in ocean post
  jobs/rocoto/ocnpost.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1700 Make consistent use of `restart_interval` across UFS applications
  ci/cases/C96C48_hybatmDA.yaml
  ci/cases/C96_atm3DVar.yaml
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.base.nco.static
  parm/config/gfs/config.efcs
  parm/config/gfs/config.fcst
  parm/config/gfs/config.fv3.nco.static
  parm/config/gfs/config.resources.nco.static
  parm/config/gfs/config.wave
  scripts/exgdas_enkf_fcst.sh
  scripts/exglobal_forecast.sh
  sorc/link_workflow.sh
  ush/cplvalidate.sh
  ush/forecast_det.sh
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
  ush/nems_configure.sh
  ush/parsing_model_configure_FV3.sh
Labels: CI-Hera-Passed, CI-Orion-Failed

#1715 Consolidate `BASE_CPLIC` by platform
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.coupled_ic
  workflow/hosts/awspw.yaml
  workflow/hosts/hera.yaml
  workflow/hosts/jet.yaml
  workflow/hosts/orion.yaml
  workflow/hosts/s4.yaml
  workflow/hosts/wcoss2.yaml
Labels: CI-Hera-Passed, CI-Orion-Passed

#1716 Fix ocean file locations in archive job
  jobs/JGLOBAL_ARCHIVE
  parm/config/gfs/config.com
  ush/hpssarch_gen.sh
Labels: CI-Hera-Passed

#1593 Add S2SA nems.configure template
  docs/source/setup.rst
  parm/chem/SU2G_instance_SU.rc
  parm/config/gfs/config.efcs
  ush/nems.configure.cpld_aero.IN
  workflow/applications/gfs_forecast_only.py
  workflow/setup_expt.py
Labels: feature, CI-Hera-Passed, CI-Orion-Passed
