Repository NOAA-EMC/global-workflow, pull requests merged in 2023-08, with the labels that each got.

#1772 Fix previous restart paths for ensemble
  jobs/JGDAS_ENKF_FCST
  scripts/exgdas_enkf_fcst.sh
Labels: CI-Hera-Passed

#1774 Add a gefs test
  ci/cases/C48_S2SA_gefs.yaml
  ci/platforms/gefs_ci_defaults.yaml
  parm/config/gefs/yaml/defaults.yaml
  workflow/setup_expt.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#1773 Move GDASApp to CRTM 2.4
  Externals.cfg
  parm/config/gfs/config.aeroanl
  parm/config/gfs/config.atmanl
  parm/config/gfs/config.atmensanl
  parm/gdas/aero_crtm_coeff.yaml
  parm/gdas/atm_crtm_coeff.yaml
  sorc/checkout.sh
  sorc/link_workflow.sh
  ush/python/pygfs/task/aero_analysis.py
  ush/python/pygfs/task/atm_analysis.py
  ush/python/pygfs/task/atmens_analysis.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#1781 Fix unbound PS1 message from module-setup
  ush/module-setup.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1782 Use GEFS post file for GEFS
  parm/config/gefs/config.base.emc.dyn
Labels: CI-Hera-Passed, CI-Orion-Passed

#1790 Fix f-o mode not sourcing postsnd when soundings are on
  workflow/applications/gfs_forecast_only.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#1802 Remove RUN_ENVIR from as many places as possible.
  jobs/JGFS_ATMOS_CYCLONE_GENESIS
  jobs/JGFS_ATMOS_CYCLONE_TRACKER
  jobs/JGFS_ATMOS_FSU_GENESIS
  jobs/JGLOBAL_ATMOS_EMCSFC_SFC_PREP
  jobs/JGLOBAL_ATMOS_SFCANL
  jobs/JGLOBAL_ATMOS_TROPCY_QC_RELOC
  jobs/rocoto/awips.sh
  jobs/rocoto/metp.sh
  jobs/rocoto/ocnpost.sh
  jobs/rocoto/prep.sh
  parm/config/gfs/config.prep
  scripts/exgdas_atmos_verfozn.sh
  scripts/exgdas_atmos_verfrad.sh
  scripts/exgdas_atmos_vminmon.sh
  scripts/exgfs_atmos_vminmon.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1814 Add mention of check-all fix in release notes
  docs/Release_Notes.gfs.v16.3.8.md
Labels: bug, production update

#1816 Replace full-path restart links with relative links
  ush/forecast_predet.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1823 Rename COM_ATMOS_GRIB_TMPL as COM_ATMOS_GRIB_GRID_TMPL.
  jobs/JGDAS_ATMOS_GEMPAK
  jobs/JGFS_ATMOS_AWIPS_20KM_1P0DEG
  jobs/JGFS_ATMOS_AWIPS_G2
  jobs/JGFS_ATMOS_CYCLONE_GENESIS
  jobs/JGFS_ATMOS_CYCLONE_TRACKER
  jobs/JGFS_ATMOS_GEMPAK
  jobs/JGFS_ATMOS_PGRB2_SPEC_NPOESS
  jobs/JGLOBAL_ARCHIVE
  jobs/JGLOBAL_ATMOS_POST
  parm/config/gfs/config.com
  ush/load_fv3gfs_modules.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1779 Feature/cloud rtd updates
  docs/source/_static/noaacsp_cluster_1.png
  docs/source/_static/noaacsp_cluster_2.png
  docs/source/_static/noaacsp_cluster_3.png
  docs/source/_static/noaacsp_cluster_4.png
  docs/source/_static/noaacsp_cluster_5.png
  docs/source/_static/noaacsp_cluster_6.png
  docs/source/_static/noaacsp_instance_1.png
  docs/source/_static/noaacsp_instance_2.png
  docs/source/_static/noaacsp_instance_3.png
  docs/source/_static/noaacsp_instance_4.png
  docs/source/_static/noaacsp_login.png
  docs/source/_static/noaacsp_using_1.png
  docs/source/_static/noaacsp_using_2.png
  docs/source/custom.css
  docs/source/hpc.rst
  docs/source/index.rst
  docs/source/noaa_csp.rst
Labels: documentation
