Repository NOAA-EMC/global-workflow, pull requests merged in 2023-05, with the labels that each got.

#1553 Remove gdas bump fix files
  sorc/link_workflow.sh
  versions/fix.ver
Labels: maintenance, Fix Files

#1562 Update init.rst cycled coupled IC info
  docs/source/init.rst
Labels: documentation

#1561 Replace `CDATE` with `PDYcyc` combo
  parm/config/config.anal
  parm/config/config.atmensanl
  parm/config/config.atmensanlfinal
  parm/config/config.atmensanlinit
  parm/config/config.atmensanlrun
  parm/config/config.base.emc.dyn
  parm/config/config.getic
  parm/config/config.init
  parm/config/config.landanl
  parm/config/config.landanlfinal
  parm/config/config.landanlinit
  parm/config/config.landanlrun
  parm/config/config.nsst
  parm/config/config.prep
Labels: CI-Orion-Passed

#1571 Update prepobs install copy for atm log filename fix
  modulefiles/module_base.hera.lua
  modulefiles/module_base.jet.lua
  modulefiles/module_base.orion.lua
  modulefiles/module_base.wcoss2.lua
Labels: bug

#1573 Update documentation for PR standards
  docs/source/development.rst
Labels: documentation

#1581 New UFS_UTILS hash for gdas_init COM reorg updates
  Externals.cfg
  sorc/checkout.sh
Labels: maintenance

#1535 Redo v16.3 GSI script updates to scripts/exglobal_atmos_analysis.sh
  parm/config/config.anal
  parm/config/config.base.emc.dyn
  parm/config/config.base.nco.static
  scripts/exglobal_atmos_analysis.sh
  versions/fix.ver
Labels: production update, maintenance

#1591 Add S2SA to the allowed app list in setup expt
  docs/source/setup.rst
  workflow/setup_expt.py
Labels: feature

#1620 Fix type of donst for sfcanl namelist
  ush/gaussian_sfcanl.sh
Labels: bug, CI-Orion-Passed

#1626 Fixes for enkf archival bugs in ush/hpssarch_gen.sh
  jobs/JGDAS_ENKF_ARCHIVE
  ush/hpssarch_gen.sh
Labels: bug

#1630 Cast dict as an AttDict to handle nested dicts properly in update_configs
  workflow/setup_expt.py
Labels: bug

#1642 Remove WAFS references from global-workflow
  Externals.cfg
  docs/source/clone.rst
  docs/source/components.rst
  docs/source/configure.rst
  docs/source/run.rst
  ecf/defs/gfs_00.def
  ecf/defs/gfs_06.def
  ecf/defs/gfs_12.def
  ecf/defs/gfs_18.def
  ecf/defs/prod00.def
  ecf/defs/prod06.def
  ecf/defs/prod12.def
  ecf/defs/prod18.def
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_blending.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_blending_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/grib_wafs/.gitignore
  ecf/scripts/gfs/atmos/post_processing/grib_wafs/jgfs_atmos_wafs_master.ecf
  ecf/scripts/gfs/atmos/post_processing/jgfs_atmos_wafs_gcip.ecf
  ecf/setup_ecf_links.sh
  env/WCOSS2.env
  fix/product/wafs_admin_msg
  jobs/JGLOBAL_ARCHIVE
  jobs/JGLOBAL_ATMOS_POST
  jobs/rocoto/wafs.sh
  jobs/rocoto/wafsblending.sh
  jobs/rocoto/wafsblending0p25.sh
  jobs/rocoto/wafsgcip.sh
  jobs/rocoto/wafsgrib2.sh
  jobs/rocoto/wafsgrib20p25.sh
  parm/config/gefs/config.base.emc.dyn
  parm/config/gefs/config.resources
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.base.nco.static
  parm/config/gfs/config.com
  parm/config/gfs/config.resources
  parm/config/gfs/config.resources.nco.static
  parm/config/gfs/config.wafs
  parm/config/gfs/config.wafsblending
  parm/config/gfs/config.wafsblending0p25
  parm/config/gfs/config.wafsgcip
  parm/config/gfs/config.wafsgrib2
  parm/config/gfs/config.wafsgrib20p25
  parm/product/transfer_gfs_1.list
  parm/product/transfer_gfs_7.list
  scripts/exgfs_atmos_post.sh
  scripts/exglobal_archive.sh
  sorc/build_all.sh
  sorc/build_gfs_wafs.sh
  sorc/checkout.sh
  sorc/gfs_build.cfg
  sorc/link_workflow.sh
  sorc/partial_build.sh
  ush/gfs_post.sh
  ush/hpssarch_gen.sh
  workflow/applications.py
  workflow/prod.yml
  workflow/rocoto/workflow_tasks.py
Labels: CI-Orion-Passed, CI-Hera-Running

#1656 Update DMPDIR for WCOSS2
  workflow/hosts/wcoss2.yaml
Labels: maintenance

#1644 Introduce version file support into develop branch
  .gitignore
  modulefiles/module_base.hera.lua
  modulefiles/module_base.jet.lua
  modulefiles/module_base.orion.lua
  modulefiles/module_base.s4.lua
  modulefiles/module_base.wcoss2.lua
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.vrfy
  sorc/build_all.sh
  sorc/link_workflow.sh
  ush/load_fv3gfs_modules.sh
  versions/build.hera.ver
  versions/build.jet.ver
  versions/build.orion.ver
  versions/build.s4.ver
  versions/build.wcoss2.ver
  versions/run.hera.ver
  versions/run.jet.ver
  versions/run.orion.ver
  versions/run.s4.ver
  versions/run.wcoss2.ver
  workflow/hosts/wcoss2.yaml
Labels: feature, CI-Hera-Passed, CI-Orion-Passed

#1648 Add support for forecast-only low resolution
  jobs/rocoto/coupled_ic.sh
  jobs/rocoto/ocnpost.sh
  parm/config/gfs/config.coupled_ic
  parm/config/gfs/config.ocnpost
  parm/config/gfs/config.resources
  ush/forecast_postdet.sh
  versions/fix.ver
  workflow/rocoto/workflow_tasks.py
Labels: CI-Orion-Passed

#1657 Explicitly define IAUFHRS for DOIAU=NO case
  parm/config/gfs/config.base.emc.dyn
Labels: CI-Orion-Passed
