Repository NOAA-EMC/global-workflow, pull requests merged in 2023-12, with the labels that each got.

#2084 Upgrade to spack-stack/1.5.1 and Intel 2022 on non-production machines
  jobs/rocoto/anal.sh
  jobs/rocoto/efcs.sh
  jobs/rocoto/eobs.sh
  jobs/rocoto/eupd.sh
  jobs/rocoto/fcst.sh
  jobs/rocoto/post.sh
  jobs/rocoto/prep.sh
  modulefiles/module_base.hera.lua
  modulefiles/module_base.jet.lua
  modulefiles/module_base.orion.lua
  modulefiles/module_base.s4.lua
  modulefiles/module_gwci.hera.lua
  modulefiles/module_gwci.orion.lua
  modulefiles/module_gwsetup.hera.lua
  modulefiles/module_gwsetup.jet.lua
  modulefiles/module_gwsetup.orion.lua
  modulefiles/module_gwsetup.s4.lua
  modulefiles/module_gwsetup.wcoss2.lua
  parm/config/gefs/config.base.emc.dyn
  parm/config/gfs/config.base.emc.dyn
  scripts/exgfs_atmos_awips_20km_1p0deg.sh
  scripts/exgfs_atmos_grib_awips.sh
  scripts/exglobal_diag.sh
  sorc/checkout.sh
  sorc/link_workflow.sh
  ush/getncdimlen
  ush/gsi_utils.py
  versions/build.hera.ver
  versions/build.jet.ver
  versions/build.orion.ver
  versions/build.s4.ver
  versions/build.spack.ver
  versions/run.hera.ver
  versions/run.jet.ver
  versions/run.orion.ver
  versions/run.s4.ver
  versions/run.spack.ver
Labels: CI-Hera-Passed, CI-Orion-Passed

#2093 Robust CI Restarts
  ci/platforms/config.orion
  ci/scripts/check_ci.sh
  ci/scripts/clone-build_ci.sh
  ci/scripts/driver.sh
  ci/scripts/utils/ci_utils.sh
Labels: CI/CD

#2088 Consolidate VMINMON and cleanup monitor scripts
  .gitignore
  fix/product/gfs_minmon_cost.txt
  fix/product/gfs_minmon_gnorm.txt
  jobs/JGDAS_ATMOS_VERFOZN
  jobs/JGDAS_ATMOS_VERFRAD
  jobs/JGDAS_ATMOS_VMINMON
  jobs/JGFS_ATMOS_VMINMON
  jobs/JGLOBAL_ATMOS_VMINMON
  jobs/rocoto/vminmon.sh
  parm/config/gfs/config.verfozn
  parm/config/gfs/config.verfrad
  parm/config/gfs/config.vminmon
  scripts/exgdas_atmos_verfozn.sh
  scripts/exgdas_atmos_verfrad.sh
  scripts/exgfs_atmos_vminmon.sh
  scripts/exglobal_atmos_vminmon.sh
  sorc/link_workflow.sh
  ush/ozn_xtrct.sh
  ush/radmon_diag_ck.sh
  ush/radmon_err_rpt.sh
  ush/radmon_verf_angle.sh
  ush/radmon_verf_bcoef.sh
  ush/radmon_verf_bcor.sh
  ush/radmon_verf_time.sh
Labels: maintenance, CI-Hera-Passed, CI-Orion-Passed

#2117 GFSv16.3.11 - Enable the monitoring of NOAA-21 and GOES-18 radiances
  Externals.cfg
  docs/Release_Notes.gfs.v16.3.11.md
  sorc/checkout.sh
  versions/build.ver
  versions/run.ver
Labels: production update

#2110 Separate offline UPP from interpolated grib2 product generation
  env/HERA.env
  env/JET.env
  env/ORION.env
  env/S4.env
  env/WCOSS2.env
  jobs/JGLOBAL_ATMOS_POST
  jobs/JGLOBAL_ATMOS_PRODUCTS
  jobs/rocoto/atmos_products.sh
  jobs/rocoto/post.sh
  jobs/rocoto/postanl.sh
  jobs/rocoto/upp.sh
  parm/config/gefs/config.resources
  parm/config/gfs/config.atmos_products
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.ocnpost
  parm/config/gfs/config.post
  parm/config/gfs/config.resources
  parm/config/gfs/config.upp
  parm/post/upp.yaml
  scripts/exgdas_atmos_post.sh
  scripts/exgfs_atmos_post.sh
  scripts/exglobal_atmos_products.sh
  sorc/link_workflow.sh
  ush/fv3gfs_downstream_nems.sh
  ush/gfs_post.sh
  ush/gfs_transfer.sh
  ush/inter_flux.sh
  ush/interp_atmos_master.sh
  ush/interp_atmos_sflux.sh
  ush/python/pygfs/task/upp.py
  versions/build.hera.ver
  versions/build.jet.ver
  versions/build.orion.ver
  versions/build.s4.ver
  versions/build.spack.ver
  versions/run.hera.ver
  versions/run.jet.ver
  versions/run.orion.ver
  versions/run.s4.ver
  workflow/applications/applications.py
  workflow/applications/gfs_cycled.py
  workflow/applications/gfs_forecast_only.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/rocoto.py
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#2145 Fix module load typo in jobs/rocoto/upp.sh
  jobs/rocoto/upp.sh
Labels: bug

#2143 Enable radar reflectivity output
  parm/config/gefs/config.fcst
  parm/config/gfs/config.fcst
  parm/ufs/fv3/diag_table
  ush/parsing_namelists_FV3.sh
Labels: CI-Hera-Passed

#2148 Add MOS jobs to rocoto mesh
  env/WCOSS2.env
  jobs/rocoto/mos_ext_grd_fcst.sh
  jobs/rocoto/mos_ext_grd_prdgen.sh
  jobs/rocoto/mos_ext_grd_prep.sh
  jobs/rocoto/mos_ext_stn_fcst.sh
  jobs/rocoto/mos_ext_stn_prdgen.sh
  jobs/rocoto/mos_ext_stn_prep.sh
  jobs/rocoto/mos_grd_fcst.sh
  jobs/rocoto/mos_grd_prdgen.sh
  jobs/rocoto/mos_grd_prep.sh
  jobs/rocoto/mos_stn_fcst.sh
  jobs/rocoto/mos_stn_prdgen.sh
  jobs/rocoto/mos_stn_prep.sh
  jobs/rocoto/mos_wx_ext_prdgen.sh
  jobs/rocoto/mos_wx_prdgen.sh
  modulefiles/module_base.wcoss2.lua
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.mos
  parm/config/gfs/config.mos_ext_grd_fcst
  parm/config/gfs/config.mos_ext_grd_prdgen
  parm/config/gfs/config.mos_ext_grd_prep
  parm/config/gfs/config.mos_ext_stn_fcst
  parm/config/gfs/config.mos_ext_stn_prdgen
  parm/config/gfs/config.mos_ext_stn_prep
  parm/config/gfs/config.mos_grd_fcst
  parm/config/gfs/config.mos_grd_prdgen
  parm/config/gfs/config.mos_grd_prep
  parm/config/gfs/config.mos_stn_fcst
  parm/config/gfs/config.mos_stn_prdgen
  parm/config/gfs/config.mos_stn_prep
  parm/config/gfs/config.mos_wx_ext_prdgen
  parm/config/gfs/config.mos_wx_prdgen
  parm/config/gfs/config.resources
  versions/run.wcoss2.ver
  workflow/applications/applications.py
  workflow/applications/gfs_cycled.py
  workflow/applications/gfs_forecast_only.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: feature

#2167 GFSv16.3.12 - Turn on active assimilation of NOAA-21 radiances
  Externals.cfg
  docs/Release_Notes.gfs.v16.3.12.md
  ecf/scripts/enkfgdas/analysis/create/jenkfgdas_diag.ecf
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
  sorc/checkout.sh
  versions/run.ver
Labels: production update

#2169 Update GFS version to v16.3.12 in RTD index.rst
  docs/source/index.rst
Labels: production update

#2170 Fix handling of excluded hosts list
  workflow/create_experiment.py
Labels: CI-Hera-Passed, CI-Orion-Passed, CI/CD

#2172 Stop calling ufs-utils link script
  sorc/link_workflow.sh
Labels: CI-Hera-Passed, CI-Orion-Passed
