Repository NOAA-EMC/global-workflow, pull requests merged in 2023-11, with the labels that each got.

#2014 Add skeleton release notes and tentative version for WAFS update
  docs/Release_Notes.gfs.v16.3.11.md
  versions/run.ver
Labels: production update

#2000 No longer write archive lists COM
  scripts/exglobal_archive.sh
  ush/hpssarch_gen.sh
Labels: CI-Hera-Passed

#1870 Add run script to prep ocean obs task jjob
  jobs/JGLOBAL_PREP_OCEAN_OBS
  parm/config/gfs/config.prepoceanobs
  sorc/link_workflow.sh
Labels: CI-Hera-Failed

#2023 Corrects missing local variable reference
  ush/hpssarch_gen.sh
Labels: bug

#1979 Remove `anl` from post task and replace with new task
  jobs/JGLOBAL_ATMOS_POST
  jobs/rocoto/post.sh
  jobs/rocoto/postanl.sh
  workflow/applications/gfs_cycled.py
  workflow/hosts/awspw.yaml
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Passed

#1983 Create separate GSI monitor jobs and remove from vrfy job
  jobs/JGDAS_ATMOS_VERFOZN
  jobs/JGDAS_ATMOS_VERFRAD
  jobs/JGDAS_ATMOS_VMINMON
  jobs/JGFS_ATMOS_VMINMON
  jobs/JGLOBAL_ARCHIVE
  jobs/rocoto/verfozn.sh
  jobs/rocoto/verfrad.sh
  jobs/rocoto/vminmon.sh
  jobs/rocoto/vrfy.sh
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.com
  parm/config/gfs/config.resources
  parm/config/gfs/config.verfozn
  parm/config/gfs/config.verfrad
  parm/config/gfs/config.vminmon
  parm/config/gfs/config.vrfy
  ush/hpssarch_gen.sh
  ush/minmon_xtrct_costs.pl
  ush/minmon_xtrct_gnorms.pl
  ush/minmon_xtrct_reduct.pl
  workflow/applications/applications.py
  workflow/applications/gfs_cycled.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: feature, CI-Hera-Passed

#2028 Fix staging of MOM data
  scripts/exglobal_stage_ic.sh
Labels: CI-Hera-Passed

#1944 Implement IAU Cycling Type with Marine Data Assimilation Enabled
  parm/config/gfs/config.resources
  parm/ufs/fv3/diag_table_da
  parm/ufs/mom6/MOM_input_template_025
  parm/ufs/mom6/MOM_input_template_100
  parm/ufs/mom6/MOM_input_template_500
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
Labels: CI-Hera-Passed

#2018 Update WAFS package
  docs/Release_Notes.gfs.v16.3.11.md
  ecf/defs/gfs_v16_3.def
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_blending_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/jgfs_atmos_wafs_gcip.ecf
Labels: production update

#2034 Update GSI upgrade version to v16.3.12
  docs/Release_Notes.gfs.v16.3.12.md
  versions/run.ver
Labels: production update

#2035 Merge GSI update into WAFS update release branch for ops GFSv16.3.11
  Externals.cfg
  docs/Release_Notes.gfs.v16.3.11.md
  sorc/checkout.sh
  versions/build.ver
  versions/run.ver
Labels: production update

#2026 Streamline CI reporting to PRs
  ci/platforms/config.hera
  ci/platforms/config.orion
  ci/scripts/check_ci.sh
  ci/scripts/clone-build_ci.sh
  ci/scripts/driver.sh
  workflow/create_experiment.py
Labels: CI/CD

#2036 Reduce GDASApp default build jobs to 8
  sorc/build_all.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#1989 Update UFS for dust fix and remove nitrates by default
  Externals.cfg
  parm/ufs/chem/AERO_HISTORY.rc
  parm/ufs/chem/CAP.rc
  parm/ufs/chem/DU2G_instance_DU.rc
  parm/ufs/chem/ExtData.gbbepx
  parm/ufs/chem/ExtData.other
  parm/ufs/chem/ExtData.qfed
  parm/ufs/chem/GOCART2G_GridComp.rc
  parm/ufs/chem/gocart_tracer.list
  parm/ufs/fv3/diag_table.aero
  parm/ufs/fv3/field_table.aero
  sorc/checkout.sh
Labels: CI-Hera-Passed

#2042 Hack UPP version
  sorc/checkout.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#2045 Update WAFS tag and increase number of tasks for wafs_grib2_0p25
  Externals.cfg
  docs/Release_Notes.gfs.v16.3.11.md
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2_0p25.ecf
  sorc/checkout.sh
Labels: production update

#2046 Fix analysis and post on Orion
  env/ORION.env
  jobs/rocoto/post.sh
  ush/module-setup.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#2050 Update release notes for one WAFS job
  docs/Release_Notes.gfs.v16.3.11.md
Labels: production update

#2057 Update `upp_ver` to `8.3.0` for GFSv16.3.11
  docs/Release_Notes.gfs.v16.3.11.md
  versions/build.ver
Labels: production update

#2037 Add `waveinit` and `waveprep` to half-cycle.
  workflow/rocoto/gfs_tasks.py
Labels: bug, CI-Hera-Passed, CI-Orion-Passed

#2031 Enable warm starting of the model for forecast-only mode
  ci/cases/pr/C48_S2SA_gefs.yaml
  parm/config/gefs/config.base.emc.dyn
  scripts/exglobal_stage_ic.sh
  workflow/setup_expt.py
Labels: CI-Hera-Running, CI-Orion-Building

#2058 Separate tracker and genesis jobs from vrfy job
  jobs/JGFS_ATMOS_CYCLONE_GENESIS
  jobs/JGFS_ATMOS_CYCLONE_TRACKER
  jobs/JGFS_ATMOS_FSU_GENESIS
  jobs/rocoto/genesis.sh
  jobs/rocoto/genesis_fsu.sh
  jobs/rocoto/tracker.sh
  jobs/rocoto/vrfy.sh
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.genesis
  parm/config/gfs/config.genesis_fsu
  parm/config/gfs/config.resources
  parm/config/gfs/config.tracker
  parm/config/gfs/config.tropcy
  parm/config/gfs/config.vrfy
  versions/run.hera.ver
  versions/run.jet.ver
  versions/run.orion.ver
  versions/run.s4.ver
  versions/run.wcoss2.ver
  workflow/applications/applications.py
  workflow/applications/gfs_cycled.py
  workflow/applications/gfs_forecast_only.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: feature, maintenance, CI-Hera-Passed, CI-Orion-Passed

#2065 Replace ARCH_LIST with DATA in earc script to resolve bug
  scripts/exgdas_enkf_earc.sh
Labels: bug

#2062 Save the required CICE history for the sea-ice DA
  ush/forecast_postdet.sh
Labels: CI-Hera-Passed

#1987 Update functionality for Prototype HR3 UGWP
  parm/config/gefs/config.base.emc.dyn
  parm/config/gefs/config.fcst
  parm/config/gefs/config.ufs
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.fcst
  parm/config/gfs/config.ufs
  sorc/build_ufs.sh
  sorc/checkout.sh
  ush/forecast_postdet.sh
  ush/parsing_namelists_FV3.sh
Labels: CI-Hera-Passed, CI-Orion-Running

#1973 Update UPP products for GFS v17
  parm/post/global_1x1_paramlist_g2
  parm/post/global_1x1_paramlist_g2.f000
  scripts/exgfs_atmos_post.sh
  versions/build.hera.ver
  versions/build.jet.ver
  versions/build.s4.ver
  versions/build.wcoss2.ver
  versions/run.hera.ver
  versions/run.jet.ver
  versions/run.s4.ver
  versions/run.wcoss2.ver
Labels: CI-Hera-Passed, CI-Orion-Passed

#2071 Update ufs-weather-model and remove upp hack
  Externals.cfg
  parm/config/gefs/config.base.emc.dyn
  parm/config/gefs/config.fcst
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.fcst
  parm/ufs/fix/gfs/atmos.fixed_files.yaml
  parm/ufs/ufs.configure.atm.IN
  parm/ufs/ufs.configure.atm_aero.IN
  parm/ufs/ufs.configure.blocked_atm_wav.IN
  parm/ufs/ufs.configure.cpld.IN
  parm/ufs/ufs.configure.cpld_aero.IN
  parm/ufs/ufs.configure.cpld_aero_outerwave.IN
  parm/ufs/ufs.configure.cpld_aero_wave.IN
  parm/ufs/ufs.configure.cpld_outerwave.IN
  parm/ufs/ufs.configure.cpld_wave.IN
  parm/ufs/ufs.configure.leapfrog_atm_wav.IN
  scripts/exglobal_forecast.sh
  sorc/checkout.sh
  sorc/link_workflow.sh
  test/diff_UFS_rundir.sh
  ush/cplvalidate.sh
  ush/forecast_postdet.sh
  ush/load_ufswm_modules.sh
  ush/parsing_model_configure_FV3.sh
  ush/parsing_namelists_FV3.sh
  ush/ufs_configure.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#2079 Adjust modules in post.sh hack for WCOSS2
  jobs/rocoto/post.sh
Labels: bug

#2077 Add --cpus-per-task to srun commands for Hera and Orion
  env/HERA.env
  env/ORION.env
  scripts/exglobal_diag.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#2030 Enable different coupled settings for ensemble
  parm/config/gefs/config.base.emc.dyn
  parm/config/gefs/config.efcs
  parm/config/gefs/config.fcst
  parm/config/gefs/config.ufs
  parm/config/gfs/config.aero
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.efcs
  parm/config/gfs/config.fcst
  parm/config/gfs/config.ufs
  parm/ufs/gocart/AERO.rc
  parm/ufs/gocart/AERO_HISTORY.rc
  parm/ufs/gocart/AGCM.rc
  parm/ufs/gocart/CA2G_instance_CA.bc.rc
  parm/ufs/gocart/CA2G_instance_CA.br.rc
  parm/ufs/gocart/CA2G_instance_CA.oc.rc
  parm/ufs/gocart/CAP.rc
  parm/ufs/gocart/DU2G_instance_DU.rc
  parm/ufs/gocart/ExtData.gbbepx
  parm/ufs/gocart/ExtData.none
  parm/ufs/gocart/ExtData.other
  parm/ufs/gocart/ExtData.qfed
  parm/ufs/gocart/GOCART2G_GridComp.rc
  parm/ufs/gocart/NI2G_instance_NI.rc
  parm/ufs/gocart/SS2G_instance_SS.rc
  parm/ufs/gocart/SU2G_instance_SU.rc
  parm/ufs/gocart/gocart_tracer.list
  scripts/exglobal_forecast.sh
  ush/cplvalidate.sh
  ush/ufs_configure.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#2080 Retire vrfy job
  docs/source/configure.rst
  docs/source/jobs.rst
  env/AWSPW.env
  env/CONTAINER.env
  env/HERA.env
  env/JET.env
  env/ORION.env
  env/S4.env
  env/WCOSS2.env
  jobs/rocoto/vrfy.sh
  parm/config/gefs/config.base.emc.dyn
  parm/config/gefs/config.resources
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.resources
  parm/config/gfs/config.vrfy
  ush/hpssarch_gen.sh
  workflow/applications/applications.py
  workflow/applications/gfs_cycled.py
  workflow/applications/gfs_forecast_only.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#2083 Adds NPOESS support to global-workflow
  jobs/rocoto/npoess.sh
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.npoess
  parm/config/gfs/config.resources
  workflow/applications/applications.py
  workflow/applications/gfs_cycled.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: feature, CI-Hera-Passed

#2082 Adds FBWINDS support to global-workflow
  jobs/rocoto/fbwinds.sh
  workflow/applications/gfs_cycled.py
  workflow/applications/gfs_forecast_only.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/rocoto.py
  workflow/rocoto/tasks.py
Labels: feature, CI-Hera-Passed

#2095 Fix permissions for jobs/JGFS_ATMOS_VERIFICATION
  jobs/JGFS_ATMOS_VERIFICATION
Labels: bug

#2098 Add missing cut to VDATE setting in JGFS_ATMOS_VERIFICATION
  jobs/JGFS_ATMOS_VERIFICATION
Labels: bug

#2100 Remove WAFS updates from GFSv16.3.11 release branch
  Externals.cfg
  docs/Release_Notes.gfs.v16.3.11.md
  ecf/defs/gfs_v16_3.def
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_blending_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/jgfs_atmos_wafs_gcip.ecf
  sorc/checkout.sh
Labels: production update

#2102 Use new GSI tag to turn on data
  Externals.cfg
  docs/Release_Notes.gfs.v16.3.12.md
  sorc/checkout.sh
  versions/run.ver
Labels: production update
