Repository NOAA-EMC/global-workflow, pull requests merged in 2024-06, with the labels that each got.

#2610 Add IAU to snow DA (and its test)
  ci/cases/yamls/atmaerosnowDA_defaults_ci.yaml
  jobs/JGLOBAL_ATMOS_SFCANL
  scripts/exglobal_atmos_sfcanl.sh
  ush/python/pygfs/task/snow_analysis.py
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2653 Fix for ValueError
  ush/wdqms.py
Labels: production update

#2644 Add links to the ocean insitu obs processing tools
  sorc/link_workflow.sh
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed

#2661 Parameterize some things in config.atmanl and config.atmensanl
  parm/config/gfs/config.atmanl
  parm/config/gfs/config.atmensanl
  parm/config/gfs/yaml/defaults.yaml
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2636 Update RDHPCS Hera resource for `eupd` task
  parm/config/gfs/config.resources
Labels: CI-Hera-Passed

#2676 Add overwrite to creat experiment in BASH CI
  ci/scripts/driver.sh
Labels: CI/CD

#2649 Update cleanup job to use COMIN/COMOUT
  scripts/exglobal_cleanup.sh
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2561 Add ability to process ocean/ice products specific to GEFS
  parm/archive/gdasice.yaml.j2
  parm/archive/gdasocean.yaml.j2
  parm/archive/ice_grib2.yaml.j2
  parm/archive/ocean_grib2.yaml.j2
  parm/config/gefs/config.base
  parm/config/gefs/config.fcst
  parm/config/gefs/config.oceanice_products
  parm/config/gfs/config.base
  parm/config/gfs/config.fcst
  parm/post/oceanice_products_gefs.yaml
  parm/ufs/fv3/diag_table
  scripts/exglobal_archive.py
  ush/check_ice_netcdf.sh
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
  ush/parsing_namelists_CICE.sh
  ush/python/pygfs/task/oceanice_products.py
  workflow/rocoto/gefs_tasks.py
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2586 Replace `sleep` with `wait_for_file`
  env/HERA.env
  scripts/exgfs_atmos_awips_20km_1p0deg.sh
  scripts/exgfs_atmos_postsnd.sh
  scripts/exgfs_wave_nawips.sh
  scripts/exgfs_wave_post_gridded_sbs.sh
  scripts/exgfs_wave_prdgen_gridded.sh
  ush/gfs_bufr.sh
  ush/gfs_bufr_netcdf.sh
  ush/wave_tar.sh
  versions/run.hera.ver
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2559 Add ability to use GEFS replay ICs
  parm/config/gefs/config.base
  parm/config/gefs/config.efcs
  parm/config/gefs/config.fcst
  parm/config/gefs/config.stage_ic
  parm/config/gefs/config.ufs
  parm/config/gefs/yaml/defaults.yaml
  parm/config/gfs/config.base
  scripts/exgfs_wave_post_pnt.sh
  scripts/exglobal_stage_ic.sh
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
  ush/parsing_namelists_WW3.sh
  ush/wave_outp_spec.sh
  workflow/rocoto/gefs_tasks.py
  workflow/setup_expt.py
Labels: CI-Hera-Passed, CI-Wcoss2-Passed

#2685 Add Hercules-EMC to the Jenkins configurable parameter list
  ci/Jenkinsfile
Labels: CI/CD

#2657 Optimize wavepostpnt
  parm/config/gefs/config.resources
  parm/config/gefs/config.wave
  parm/config/gfs/config.resources
  parm/config/gfs/config.wave
  scripts/exgfs_wave_post_pnt.sh
  ush/wave_outp_spec.sh
  workflow/rocoto/gefs_tasks.py
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hercules-Failed

#2679 Turn on high-frequency output in extended test
  ci/cases/yamls/gfs_extended_ci.yaml
  parm/config/gefs/config.base
  parm/config/gefs/yaml/defaults.yaml
  parm/config/gfs/config.base
  parm/config/gfs/yaml/defaults.yaml
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2668 Update archive job to use COMIN/COMOUT
  jobs/JGDAS_ENKF_ARCHIVE
  jobs/JGLOBAL_ARCHIVE
  parm/archive/arcdir.yaml.j2
  parm/archive/chem.yaml.j2
  parm/archive/enkf.yaml.j2
  parm/archive/enkf_grp.yaml.j2
  parm/archive/enkf_restarta_grp.yaml.j2
  parm/archive/enkf_restartb_grp.yaml.j2
  parm/archive/gdas.yaml.j2
  parm/archive/gdas_restarta.yaml.j2
  parm/archive/gdas_restartb.yaml.j2
  parm/archive/gdasice.yaml.j2
  parm/archive/gdasice_restart.yaml.j2
  parm/archive/gdasocean.yaml.j2
  parm/archive/gdasocean_analysis.yaml.j2
  parm/archive/gdasocean_restart.yaml.j2
  parm/archive/gdaswave.yaml.j2
  parm/archive/gdaswave_restart.yaml.j2
  parm/archive/gfs_downstream.yaml.j2
  parm/archive/gfs_flux.yaml.j2
  parm/archive/gfs_flux_1p00.yaml.j2
  parm/archive/gfs_netcdfa.yaml.j2
  parm/archive/gfs_netcdfb.yaml.j2
  parm/archive/gfs_pgrb2b.yaml.j2
  parm/archive/gfs_restarta.yaml.j2
  parm/archive/gfsa.yaml.j2
  parm/archive/gfsb.yaml.j2
  parm/archive/gfswave.yaml.j2
  parm/archive/ice_6hravg.yaml.j2
  parm/archive/ice_grib2.yaml.j2
  parm/archive/master_enkf.yaml.j2
  parm/archive/ocean_6hravg.yaml.j2
  parm/archive/ocean_grib2.yaml.j2
  scripts/exgdas_enkf_earc.py
  scripts/exglobal_archive.py
  ush/python/pygfs/task/archive.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2688 Removes misleading "No such file or directory" syntax errors from output files
  scripts/exglobal_diag.sh
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2667 Eliminate post groups
  .gitignore
  jobs/rocoto/atmos_ensstat.sh
  jobs/rocoto/atmos_products.sh
  jobs/rocoto/oceanice_products.sh
  jobs/rocoto/upp.sh
  parm/config/gefs/config.base
  scripts/exgdas_enkf_earc.py
  workflow/rocoto/gefs_tasks.py
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2687 Fix and simplify online archiving
  .gitignore
  parm/archive/arcdir.yaml.j2
  parm/archive/gdas.yaml.j2
  parm/config/gfs/yaml/defaults.yaml
  ush/python/pygfs/task/archive.py
Labels: CI-Hera-Failed, CI-Hercules-Passed, CI-Wcoss2-Running

#2672 Assign machine- and RUN-specific resources
  env/AWSPW.env
  env/CONTAINER.env
  env/GAEA.env
  env/HERA.env
  env/HERCULES.env
  env/JET.env
  env/ORION.env
  env/S4.env
  env/WCOSS2.env
  modulefiles/module_gwsetup.hercules.lua
  parm/config/gefs/config.resources
  parm/config/gfs/config.anal
  parm/config/gfs/config.analcalc
  parm/config/gfs/config.resources
  parm/config/gfs/config.resources.GAEA
  parm/config/gfs/config.resources.HERA
  parm/config/gfs/config.resources.HERCULES
  parm/config/gfs/config.resources.JET
  parm/config/gfs/config.resources.S4
  parm/config/gfs/config.resources.WCOSS2
  parm/config/gfs/config.ufs
  ush/forecast_postdet.sh
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2643 Update wave jobs to use COMIN/COMOUT
  jobs/JGLOBAL_WAVE_INIT
  jobs/JGLOBAL_WAVE_POST_BNDPNT
  jobs/JGLOBAL_WAVE_POST_BNDPNTBLL
  jobs/JGLOBAL_WAVE_POST_PNT
  jobs/JGLOBAL_WAVE_POST_SBS
  jobs/JGLOBAL_WAVE_PRDGEN_BULLS
  jobs/JGLOBAL_WAVE_PRDGEN_GRIDDED
  jobs/JGLOBAL_WAVE_PREP
  scripts/exgfs_wave_init.sh
  scripts/exgfs_wave_post_gridded_sbs.sh
  scripts/exgfs_wave_post_pnt.sh
  scripts/exgfs_wave_prdgen_bulls.sh
  scripts/exgfs_wave_prdgen_gridded.sh
  scripts/exgfs_wave_prep.sh
  ush/wave_grib2_sbs.sh
  ush/wave_grid_interp_sbs.sh
  ush/wave_grid_moddef.sh
  ush/wave_prnc_ice.sh
  ush/wave_tar.sh
Labels: CI-Hercules-Passed, CI-Wcoss2-Passed

#2681 Update logic for MOM6 number of layers/exception values
  parm/config/gefs/config.ufs
  parm/config/gfs/config.ufs
Labels: CI-Hercules-Passed, CI-Wcoss2-Passed

#2719 Cleanup of stale RUNDIRS from an experiment
  parm/config/gefs/config.base
  parm/config/gfs/config.base
  scripts/exglobal_cleanup.sh
Labels: CI-Wcoss2-Passed

#2720 Activate snow DA test on WCOSS
  ci/cases/pr/C96_atmaerosnowDA.yaml
Labels: CI-Wcoss2-Running

#2692 updated Finalize in Jenkinsfile and added try block around scm checkout
  ci/Jenkinsfile
  ci/scripts/check_ci.sh
  ci/scripts/run-check_ci.sh
Labels: CI-Hera-Failed, CI/CD
