Repository NOAA-EMC/global-workflow, pull requests merged in 2024-07, with the labels that each got.

#2671 Update gempak job to run one fcst hour per task
  ecf/scripts/gdas/atmos/gempak/jgdas_atmos_gempak.ecf
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_gempak.ecf
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_pgrb2_spec_gempak.ecf
  jobs/JGDAS_ATMOS_GEMPAK
  jobs/JGFS_ATMOS_GEMPAK
  jobs/JGFS_ATMOS_GEMPAK_PGRB2_SPEC
  jobs/rocoto/gempak.sh
  jobs/rocoto/gempakgrb2spec.sh
  parm/config/gfs/config.base
  parm/config/gfs/config.resources
  scripts/exgdas_atmos_nawips.sh
  scripts/exgfs_atmos_goes_nawips.sh
  scripts/exgfs_atmos_grib2_special_npoess.sh
  scripts/exgfs_atmos_nawips.sh
  workflow/rocoto/gfs_tasks.py
Labels: CI-Wcoss2-Passed

#2728 Add fcst dependency to ocnanalprep
  workflow/rocoto/gfs_tasks.py
Labels: CI-Wcoss2-Passed

#2635 Adds contents of constructor and initialize methods to marine LETKF class
  env/HERA.env
  env/ORION.env
  jobs/JGLOBAL_MARINE_ANALYSIS_LETKF
  jobs/rocoto/marineanalletkf.sh
  parm/config/gfs/config.marineanalletkf
  parm/config/gfs/config.ocnanal
  parm/config/gfs/config.ocnanalletkf
  parm/config/gfs/config.resources
  ush/python/pygfs/task/marine_letkf.py
Labels: CI-Hera-Passed, CI-Wcoss2-Passed

#2758 Updated prepobs and fit2obs versions for Orion Rocky9
  modulefiles/module_base.hera.lua
  modulefiles/module_base.hercules.lua
  modulefiles/module_base.jet.lua
  modulefiles/module_base.orion.lua
  modulefiles/module_base.wcoss2.lua
  versions/run.spack.ver
  versions/run.wcoss2.ver
Labels: CI-Hera-Passed, CI-Hercules-Failed, CI-Wcoss2-Passed

#2757 Address issues in creating XML for GFS forecast-only with app S2SWA
  workflow/applications/applications.py
  workflow/applications/gfs_forecast_only.py
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Passed

#2680 Add task to process reforecast variables to save on WCOSS2
  jobs/JGLOBAL_EXTRACTVARS
  jobs/rocoto/extractvars.sh
  parm/config/gefs/config.base
  parm/config/gefs/config.extractvars
  parm/config/gefs/config.resources
  parm/config/gefs/yaml/defaults.yaml
  parm/product/gefs_ice_shortparmlist.parm
  parm/product/gefs_ocn_shortparmlist.parm
  parm/product/gefs_shortparmlist_2d.parm
  parm/product/gefs_shortparmlist_3d_d.parm
  parm/product/gefs_shortparmlist_3d_h.parm
  parm/product/gefs_wav_shortparmlist.parm
  scripts/exglobal_extractvars.sh
  ush/atmos_extractvars.sh
  ush/extractvars_tools.sh
  ush/ocnice_extractvars.sh
  ush/wave_extractvars.sh
  workflow/applications/applications.py
  workflow/applications/gefs.py
  workflow/rocoto/gefs_tasks.py
Labels: CI-Hercules-Passed

#2775 Use replace_tmpl Jinja filter instead of namespaces in archiving
  .github/workflows/ci_unit_tests.yaml
  parm/archive/master_enkf.yaml.j2
  workflow/hosts/awspw.yaml
  workflow/hosts/container.yaml
  workflow/hosts/gaea.yaml
  workflow/hosts/hera.yaml
  workflow/hosts/hercules.yaml
  workflow/hosts/jet.yaml
  workflow/hosts/orion.yaml
  workflow/hosts/s4.yaml
  workflow/hosts/wcoss2.yaml
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2778 Remove f000 from atmos rocoto tasks for replay cases
  scripts/exglobal_stage_ic.sh
  workflow/rocoto/gefs_tasks.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Running, CI-Hercules-Passed
