Repository NOAA-EMC/global-workflow, pull requests merged in 2024-12, with the labels that each got.

#3112 Fix wave restart for cold start and add ic version file
  ci/cases/pr/C48mx500_3DVarAOWCDA.yaml
  ci/cases/pr/C48mx500_hybAOWCDA.yaml
  ci/cases/pr/C96C48_hybatmDA.yaml
  ci/cases/pr/C96C48_hybatmaerosnowDA.yaml
  ci/cases/pr/C96C48_ufs_hybatmDA.yaml
  ci/cases/pr/C96_atm3DVar.yaml
  ci/cases/pr/C96_atm3DVar_extended.yaml
  ci/cases/weekly/C384C192_hybatmda.yaml
  ci/cases/weekly/C384_atm3DVar.yaml
  parm/config/gefs/config.stage_ic
  parm/config/gfs/config.stage_ic
  parm/stage/master_gfs.yaml.j2
  ush/forecast_postdet.sh
  versions/ic.ver
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#3149 Enable traditional threading as an option
  parm/config/gefs/config.resources
  parm/config/gfs/config.resources
  ush/parsing_model_configure_FV3.sh
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#3098 Allow building of the ufs-weather-model, WW3 pre/post execs for GFS, GEFS, SFS in the same clone of global-workflow
  ci/Jenkinsfile
  ci/cases/pr/C48_S2SWA_gefs.yaml
  ci/cases/pr/C96_S2SWA_gefs_replay_ics.yaml
  ci/cases/yamls/build.yaml
  ci/scripts/utils/ci_utils_wrapper.sh
  parm/config/gefs/config.fcst
  parm/config/gfs/config.fcst
  scripts/exgfs_wave_post_pnt.sh
  sorc/build_all.sh
  sorc/build_ufs.sh
  sorc/build_ww3prepost.sh
  sorc/link_workflow.sh
  ush/wave_grib2_sbs.sh
  ush/wave_grid_interp_sbs.sh
  ush/wave_grid_moddef.sh
  ush/wave_outp_spec.sh
  ush/wave_prnc_cur.sh
  ush/wave_prnc_ice.sh
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#3144 Reduce scope to annual CO2 update and PlanetIQ assimilation
  Externals.cfg
  docs/Release_Notes.md
  ecf/scripts/enkfgdas/analysis/create/jenkfgdas_update.ecf
  ecf/scripts/enkfgdas/analysis/recenter/jenkfgdas_sfc.ecf
  ecf/scripts/gdas/atmos/obsproc/prep/jgdas_atmos_emcsfc_sfc_prep.ecf
  ecf/scripts/gdas/wave/post/jgdas_wave_postpnt.ecf
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_gempak.ecf
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_gempak_meta.ecf
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_gempak_ncdc_upapgif.ecf
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_npoess_pgrb2_0p5deg.ecf
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_pgrb2_spec_gempak.ecf
  ecf/scripts/gfs/atmos/obsproc/prep/jgfs_atmos_emcsfc_sfc_prep.ecf
  ecf/scripts/gfs/atmos/post_processing/awips_20km_1p0/jgfs_atmos_awips_master.ecf
  ecf/scripts/gfs/atmos/post_processing/awips_g2/jgfs_atmos_awips_g2_master.ecf
  ecf/scripts/gfs/atmos/post_processing/bulletins/jgfs_atmos_fbwind.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_blending_0p25.ecf
  ecf/scripts/gfs/wave/gempak/jgfs_wave_gempak.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_post_bndpnt.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_post_bndpntbll.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_postpnt.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_postsbs.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_prdgen_gridded.ecf
  modulefiles/module_base.wcoss2.lua
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
  sorc/checkout.sh
  versions/run.ver
Labels: production update

#3175 Change orog gravity wave drag scheme for grid sizes less than 10km
  parm/config/gefs/config.ufs
  parm/config/gfs/config.ufs
Labels: CI-Hera-Passed

#3186 Create compute build option
  .github/CODEOWNERS
  .gitignore
  ci/Jenkinsfile
  docs/source/clone.rst
  sorc/build_all.sh
  sorc/build_compute.sh
  sorc/build_upp.sh
  workflow/build_compute.py
  workflow/build_opts.yaml
  workflow/generate_workflows.sh
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#3167 Fix mod_icec bug in atmos_prod
  ush/interp_atmos_master.sh
Labels: CI-Hera-Passed

#3185 Remove early-cycle EnKF forecast
  parm/archive/enkf.yaml.j2
  parm/archive/enkf_grp.yaml.j2
  parm/archive/enkf_restartb_grp.yaml.j2
  scripts/exgdas_enkf_earc.py
  workflow/applications/gfs_cycled.py
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hercules-Passed
