Repository NOAA-EMC/global-workflow, pull requests merged in 2024-10, with the labels that each got.

#2969 Add corrections to the variable names for GEFS
  parm/product/gefs.0p25.fFFF.paramlist.b.txt
Labels: CI-Hera-Passed, CI-Hercules-Failed

#2788 Adding a CI for using Replay ICs with an offset hour of 3
  ci/cases/pr/C48_S2SWA_gefs.yaml
  ci/cases/pr/C96_S2SWA_gefs_replay_ics.yaml
  ci/cases/yamls/gefs_defaults_ci.yaml
  ci/cases/yamls/gefs_replay_ci.yaml
  jobs/JGLOBAL_WAVE_POST_PNT
  parm/archive/gefs_arcdir.yaml.j2
  parm/config/gefs/config.atmos_products
  parm/config/gefs/config.base
  parm/config/gefs/config.efcs
  parm/config/gefs/config.extractvars
  parm/config/gefs/yaml/defaults.yaml
  parm/product/gefs.0p25.fFFF.paramlist.a.txt
  parm/product/gefs.0p25.fFFF.paramlist.b.txt
  parm/stage/atmosphere_ens_perturbations.yaml.j2
  parm/stage/master_gefs.yaml.j2
  parm/stage/ocean_ens_perturbations.yaml.j2
  scripts/exgfs_wave_post_pnt.sh
  ush/extractvars_tools.sh
  ush/ocnice_extractvars.sh
  ush/parsing_namelists_MOM6.sh
  workflow/rocoto/gefs_tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Passed

#2981 Update rocoto task names
  parm/archive/enkf.yaml.j2
  parm/archive/gdas.yaml.j2
  parm/archive/gfsa.yaml.j2
  workflow/rocoto/gefs_tasks.py
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#3033 Quick updated to Jenkins (health check) launch script
  ci/scripts/utils/launch_java_agent.sh
Labels: CI/CD

#3038 CI jekninsfile update hotfix
  ci/Jenkinsfile
Labels: CI-Orion-Passed, CI/CD

#3018 GitHub Actions Pipeline Updates for Self-Hosted Runners on PW
  .github/workflows/pw_aws_ci.yaml
Labels: CI/CD

#2965 Disabling hyper-threading
  env/HERA.env
  env/HERCULES.env
  env/ORION.env
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#3009 Fix wave restarts and GEFS FHOUT/FHMAX
  parm/config/gefs/config.efcs
  parm/config/gefs/config.fcst
  parm/config/gfs/config.fcst
  parm/stage/wave.yaml.j2
  ush/forecast_det.sh
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
Labels: CI-Hercules-Passed

#2944 Add run and finalize methods to marine LETKF task
  ci/cases/pr/C48mx500_hybAOWCDA.yaml
  env/HERA.env
  env/ORION.env
  env/WCOSS2.env
  jobs/JGLOBAL_MARINE_ANALYSIS_LETKF
  jobs/rocoto/marineanlletkf.sh
  parm/config/gfs/config.com
  parm/config/gfs/config.marineanalletkf
  parm/config/gfs/config.marineanlletkf
  parm/config/gfs/config.resources
  parm/stage/ocean_ens_perturbations.yaml.j2
  scripts/exglobal_marine_analysis_letkf.py
  ush/forecast_postdet.sh
  ush/python/pygfs/task/marine_bmat.py
  ush/python/pygfs/task/marine_letkf.py
  workflow/applications/gfs_cycled.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2959 Update global jdas enkf diag job with COMIN/COMOUT for COM prefix
  jobs/JGDAS_ATMOS_ANALYSIS_DIAG
  jobs/JGDAS_ENKF_DIAG
  scripts/exglobal_diag.sh
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#3008 Make wxflow links static instead of from link_workflow
  .gitignore
  ci/scripts/wxflow
  sorc/link_workflow.sh
  ush/python/wxflow
  workflow/wxflow
Labels: CI-Hera-Passed, CI-Wcoss2-Passed

#3030 Fix the name of the TC tracker filenames in archive.py
  ush/python/pygfs/task/archive.py
Labels: CI-Wcoss2-Passed

#3051 Auto provisioning of PW clusters from GitHub CI added
  .github/workflows/pw_aws_ci.yaml
Labels: CI/CD
