Repository NOAA-EMC/global-workflow, pull requests merged in 2024-03, with the labels that each got.

#2360 Sort list of coupler restart files for restart time determination
  ush/forecast_det.sh
Labels: CI-Hera-Passed

#2370 Reduce Jenkins messaging to GitHub
  ci/Jenkinsfile
Labels: CI/CD

#2401 GitHub message error paths
  ci/Jenkinsfile
Labels: CI-Orion-Failed, CI/CD

#2405 re-enable ci/cases/pr/C48mx500_3DVarAOWCDA.yaml
  ci/cases/pr/C48mx500_3DVarAOWCDA.yaml
  parm/config/gfs/yaml/defaults.yaml
Labels: CI-Hera-Ready

#2385 Add GEFS Ocean Perturbation Options
  parm/config/gefs/config.base
  parm/config/gefs/config.efcs
  parm/config/gefs/yaml/defaults.yaml
  scripts/exglobal_stage_ic.sh
  ush/forecast_postdet.sh
  ush/parsing_namelists_FV3.sh
  ush/parsing_namelists_MOM6.sh
Labels: CI-Orion-Passed

#2425 hotfix to update full path to error logs on CI case fail
  ci/Jenkinsfile
Labels: CI/CD

#2424 Fix *earc jobs where the number of members isn't a multiple of 10
  ush/hpssarch_gen.sh
Labels: CI-Orion-Passed

#2435 Correct GDASApp paths
  jobs/JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP
  jobs/rocoto/prepatmiodaobs.sh
  jobs/rocoto/prepsnowobs.sh
  ush/preamble.sh
Labels: CI-Orion-Passed

#2429 Uploading error logs to GitHub from Jenkins CI Runs
  ci/Jenkinsfile
  ci/cases/yamls/build.yaml
  ci/scripts/utils/githubpr.py
  ci/scripts/utils/publish_logs.py
  sorc/build_all.sh
Labels: CI/CD

#2427 Add a rotating subset of members for early-cycle enkf
  jobs/JGLOBAL_FORECAST
  parm/config/gfs/config.base
  parm/config/gfs/yaml/defaults.yaml
  scripts/exgdas_enkf_ecen.sh
  scripts/exgdas_enkf_post.sh
  scripts/exgdas_enkf_sfc.sh
  scripts/exgdas_enkf_update.sh
  workflow/rocoto/tasks.py
Labels: CI-Orion-Passed

#2413 Modify APP based on RUN
  parm/config/gfs/config.base
  parm/config/gfs/config.efcs
  workflow/setup_expt.py
Labels: CI-Hera-Passed, CI-Orion-Passed
