Repository NOAA-EMC/global-workflow, pull requests merged in 2024-01, with the labels that each got.

#2183 Remove HIRS from GSI processing
  scripts/exglobal_atmos_analysis.sh
  scripts/exglobal_diag.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#2166 Reorganize NPOESS scripts
  jobs/JGFS_ATMOS_PGRB2_SPEC_NPOESS
  scripts/exgfs_atmos_grib2_special_npoess.sh
Labels: maintenance

#2200 Update Release_Notes.gfs.v16.3.13 with additional information
  docs/Release_Notes.gfs.v16.3.13.md
Labels: production update

#2198 Update fix versions
  versions/fix.ver
Labels: CI-Hera-Passed, CI-Orion-Passed

#2203 Enable UPP for GOES processing
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/yaml/defaults.yaml
  workflow/applications/applications.py
  workflow/applications/gfs_cycled.py
  workflow/applications/gfs_forecast_only.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#2207 Add Hercules as valid machine in CI scripts
  ci/scripts/check_ci.sh
  ci/scripts/driver.sh
  ci/scripts/driver_weekly.sh
  ci/scripts/run_ci.sh
Labels: CI/CD

#2217 Update version and module files
  modulefiles/module_base.hera.lua
  modulefiles/module_base.hercules.lua
  modulefiles/module_base.jet.lua
  modulefiles/module_base.orion.lua
  modulefiles/module_base.s4.lua
  modulefiles/module_base.wcoss2.lua
  versions/build.spack.ver
  versions/build.wcoss2.ver
  versions/run.orion.ver
  versions/run.spack.ver
Labels: CI-Hera-Passed, CI-Orion-Passed

#2214 Add ocean resolution to setup_expt invocation and retire/reduce COMROT/ROTDIR usage
  ci/cases/pr/C48_ATM.yaml
  ci/cases/pr/C48_S2SW.yaml
  ci/cases/pr/C48_S2SWA_gefs.yaml
  ci/cases/pr/C96C48_hybatmDA.yaml
  ci/cases/pr/C96_atm3DVar.yaml
  ci/cases/weekly/C384C192_hybatmda.yaml
  ci/cases/weekly/C384_S2SWA.yaml
  ci/cases/weekly/C384_atm3DVar.yaml
  ci/platforms/gefs_ci_defaults.yaml
  ci/platforms/gfs_defaults_ci.yaml
  ci/scripts/check_ci.sh
  ci/scripts/run-check_ci.sh
  docs/doxygen/mainpage.h
  docs/source/errors_faq.rst
  docs/source/init.rst
  docs/source/setup.rst
  docs/source/start.rst
  docs/source/view.rst
  jobs/JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT
  jobs/JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT_VRFY
  jobs/JGFS_ATMOS_FSU_GENESIS
  jobs/JGLOBAL_ATMOS_POST_MANAGER
  parm/config/gefs/config.base.emc.dyn
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.com
  scripts/exglobal_atmos_pmgr.sh
  scripts/exglobal_forecast.sh
  test/README.md
  workflow/hosts/awspw.yaml
  workflow/hosts/container.yaml
  workflow/hosts/hera.yaml
  workflow/hosts/hercules.yaml
  workflow/hosts/jet.yaml
  workflow/hosts/orion.yaml
  workflow/hosts/s4.yaml
  workflow/hosts/wcoss2.yaml
  workflow/setup_expt.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#2221 Apply fixes to archiving jobs
  jobs/JGLOBAL_ARCHIVE
  scripts/exglobal_atmos_products.sh
  ush/hpssarch_gen.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#2051 Use ufs.configure, model_configure, MOM_input, data_table, and ice_in templates from UFS-weather-model
  .gitignore
  parm/config/gefs/config.fcst
  parm/config/gefs/config.ufs
  parm/config/gfs/config.fcst
  parm/config/gfs/config.ice
  parm/config/gfs/config.ocn
  parm/config/gfs/config.ufs
  parm/ufs/fv3/data_table
  parm/ufs/mom6/MOM_input_template_025
  parm/ufs/mom6/MOM_input_template_050
  parm/ufs/mom6/MOM_input_template_100
  parm/ufs/mom6/MOM_input_template_500
  parm/ufs/ufs.configure.atm.IN
  parm/ufs/ufs.configure.atm_aero.IN
  parm/ufs/ufs.configure.blocked_atm_wav.IN
  parm/ufs/ufs.configure.cpld.IN
  parm/ufs/ufs.configure.cpld_aero.IN
  parm/ufs/ufs.configure.cpld_aero_outerwave.IN
  parm/ufs/ufs.configure.cpld_aero_wave.IN
  parm/ufs/ufs.configure.cpld_outerwave.IN
  parm/ufs/ufs.configure.cpld_wave.IN
  parm/ufs/ufs.configure.leapfrog_atm_wav.IN
  scripts/exglobal_forecast.sh
  sorc/link_workflow.sh
  ush/forecast_postdet.sh
  ush/parsing_model_configure_DATM.sh
  ush/parsing_model_configure_FV3.sh
  ush/parsing_namelists_CICE.sh
  ush/parsing_namelists_FV3.sh
  ush/parsing_namelists_MOM6.sh
  ush/parsing_ufs_configure.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#2233 Add option to create WGNE atmosphere products
  parm/config/gfs/config.atmos_products
  scripts/exglobal_atmos_products.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#2235 Add `POSTAMBLE_CMD` into preamble postamble
  env/HERA.env
  ush/preamble.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#2201 GOCART Emission updates for GEFSv13 and GDAS
  parm/ufs/gocart/ExtData.other
  parm/ufs/gocart/SU2G_instance_SU.rc
Labels: CI-Hera-Passed, CI-Orion-Passed

#2238 Update List in tasks.py for python error on WCOSS2
  workflow/rocoto/tasks.py
Labels: bug

#2245 Simplify and extend load_ufsda_modules to hercules
  ush/load_ufsda_modules.sh
Labels: CI-Hera-Passed, CI-Orion-Passed

#2253 GOCART ExtData biogenic climatology fix
  parm/ufs/gocart/ExtData.other
Labels: CI-Hera-Passed, CI-Orion-Passed

#2261 Set shared for non-exclusive jobs on WCOSS2 (GFSv16)
  docs/Release_Notes.gfs.v16.3.13.md
  ecf/scripts/enkfgdas/analysis/create/jenkfgdas_diag.ecf
  ecf/scripts/enkfgdas/analysis/recenter/jenkfgdas_sfc.ecf
  ecf/scripts/gdas/atmos/analysis/jgdas_atmos_analysis_diag.ecf
  ecf/scripts/gdas/atmos/gempak/jgdas_atmos_gempak.ecf
  ecf/scripts/gdas/atmos/gempak/jgdas_atmos_gempak_meta_ncdc.ecf
  ecf/scripts/gdas/atmos/obsproc/dump/jgdas_atmos_tropcy_qc_reloc.ecf
  ecf/scripts/gdas/atmos/obsproc/prep/jgdas_atmos_emcsfc_sfc_prep.ecf
  ecf/scripts/gdas/atmos/post/jgdas_atmos_post_manager.ecf
  ecf/scripts/gdas/atmos/post_processing/jgdas_atmos_chgres_forenkf.ecf
  ecf/scripts/gdas/atmos/verf/jgdas_atmos_verfozn.ecf
  ecf/scripts/gdas/atmos/verf/jgdas_atmos_verfrad.ecf
  ecf/scripts/gdas/atmos/verf/jgdas_atmos_vminmon.ecf
  ecf/scripts/gdas/wave/init/jgdas_wave_init.ecf
  ecf/scripts/gdas/wave/post/jgdas_wave_postpnt.ecf
  ecf/scripts/gdas/wave/post/jgdas_wave_postsbs.ecf
  ecf/scripts/gdas/wave/prep/jgdas_wave_prep.ecf
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_gempak.ecf
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_gempak_meta.ecf
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_gempak_ncdc_upapgif.ecf
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_npoess_pgrb2_0p5deg.ecf
  ecf/scripts/gfs/atmos/gempak/jgfs_atmos_pgrb2_spec_gempak.ecf
  ecf/scripts/gfs/atmos/obsproc/dump/jgfs_atmos_tropcy_qc_reloc.ecf
  ecf/scripts/gfs/atmos/obsproc/prep/jgfs_atmos_emcsfc_sfc_prep.ecf
  ecf/scripts/gfs/atmos/post/jgfs_atmos_post_manager.ecf
  ecf/scripts/gfs/atmos/post_processing/awips_20km_1p0/jgfs_atmos_awips_master.ecf
  ecf/scripts/gfs/atmos/post_processing/awips_g2/jgfs_atmos_awips_g2_master.ecf
  ecf/scripts/gfs/atmos/post_processing/bulletins/jgfs_atmos_fbwind.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_blending.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_blending_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/grib_wafs/jgfs_atmos_wafs_master.ecf
  ecf/scripts/gfs/atmos/post_processing/jgfs_atmos_wafs_gcip.ecf
  ecf/scripts/gfs/atmos/verf/jgfs_atmos_vminmon.ecf
  ecf/scripts/gfs/wave/gempak/jgfs_wave_gempak.ecf
  ecf/scripts/gfs/wave/init/jgfs_wave_init.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_postsbs.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_prdgen_bulls.ecf
  ecf/scripts/gfs/wave/post/jgfs_wave_prdgen_gridded.ecf
  ecf/scripts/gfs/wave/prep/jgfs_wave_prep.ecf
  ush/rocoto/setup_expt.py
  ush/rocoto/setup_expt_fcstonly.py
  ush/rocoto/workflow_utils.py
Labels: production update

#2267 Correct typos in GFS config.resources
  parm/config/gfs/config.resources
Labels: bug

#2264 Use seq to generate the list of times, instead of a bash for-loop
  ush/forecast_predet.sh
Labels: CI-Hera-Passed, CI-Orion-Passed
