Repository NOAA-EMC/global-workflow, pull requests merged in 2024-05, with the labels that each got.

#2542 Utilize scale-dependent localization for atmospheric analysis
  parm/config/gfs/config.resources
  scripts/exglobal_atmos_analysis.sh
Labels: CI-Hera-Passed, CI-Wcoss2-Passed

#2555 Updated GEMPAK version and APRUN launcher.
  env/HERA.env
  versions/run.hera.ver
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Wcoss2-Passed

#2545 Add the global nesting capability
  parm/config/gefs/config.base
  parm/config/gfs/config.base
  parm/config/gfs/config.fcst
  parm/config/gfs/config.resources
  parm/config/gfs/config.stage_ic
  parm/config/gfs/config.ufs
  scripts/exglobal_stage_ic.sh
  sorc/link_workflow.sh
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
  ush/parsing_model_configure_FV3.sh
  ush/parsing_namelists_FV3_nest.sh
  ush/python/pygfs/task/analysis.py
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Wcoss2-Passed

#2562 Add task to prepare emissions for GEFS
  env/HERA.env
  env/HERCULES.env
  env/JET.env
  env/ORION.env
  env/S4.env
  env/WCOSS2.env
  jobs/JGLOBAL_PREP_EMISSIONS
  jobs/rocoto/prep_emissions.sh
  parm/config/gefs/config.prep_emissions
  parm/config/gefs/config.resources
  scripts/exglobal_prep_emissions.py
  ush/python/pygfs/__init__.py
  ush/python/pygfs/task/aero_emissions.py
  workflow/applications/gefs.py
  workflow/rocoto/gefs_tasks.py
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Wcoss2-Passed

#2560 Updates for cold start half cycle, then continuing with IAU for WCDA
  jobs/JGLOBAL_FORECAST
  parm/config/gefs/config.fcst
  parm/config/gfs/config.fcst
  scripts/exglobal_archive.sh
  ush/forecast_det.sh
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
  ush/hpssarch_gen.sh
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Wcoss2-Passed

#2593 Do not use BUILT_semphore to force rebuilds when re-run
  ci/Jenkinsfile
Labels: CI/CD

#2588 Limit gfswavepostpnt to 40 PEs/node
  parm/config/gefs/config.resources
  parm/config/gfs/config.resources
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2600 Update CICE and MOM6 fix versions
  versions/fix.ver
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2573 Moving logic for skipping hosts in pr cases
  ci/scripts/driver.sh
  ci/scripts/utils/parse_yaml.py
  workflow/create_experiment.py
Labels: CI/CD

#2601 Remove existing EXPDIRs and COMROTs when CI is re-run
  ci/Jenkinsfile
Labels: CI/CD

#2604 Fix race condition in CI from cross mounted disks between Orion and Hercules
  ci/platforms/config.hercules
  ci/platforms/config.orion
Labels: CI/CD

#2605 Updating CI Machine configs with redundant PTMP
  ci/platforms/config.hera
  ci/platforms/config.hercules
  ci/platforms/config.orion
  ci/platforms/config.wcoss2
Labels: CI/CD

#2564 Adds jjob and other necessities for marine LETKF task
  env/HERA.env
  env/ORION.env
  jobs/JGDAS_GLOBAL_OCEAN_ANALYSIS_LETKF
  jobs/rocoto/ocnanalletkf.sh
  parm/config/gfs/config.ocnanalletkf
  parm/config/gfs/config.resources
  scripts/exgdas_global_marine_analysis_letkf.py
  ush/python/pygfs/task/marine_letkf.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2607 Add remove RUNDIRS step in CI before creating experements
  ci/scripts/utils/ci_utils.sh
Labels: CI/CD

#2614 Update STMP and PTMP settings in host file for Orion and Hercules
  ci/cases/yamls/atmaerosnowDA_defaults_ci.yaml
  ci/cases/yamls/gefs_ci_defaults.yaml
  ci/cases/yamls/gfs_defaults_ci.yaml
  ci/cases/yamls/gfs_extended_ci.yaml
  ci/cases/yamls/soca_gfs_defaults_ci.yaml
  ci/cases/yamls/ufs_hybatmDA_defaults.ci.yaml
  ci/platforms/config.hera
  ci/platforms/config.hercules
  ci/platforms/config.orion
  ci/platforms/config.wcoss2
  ci/scripts/run-check_ci.sh
  ci/scripts/utils/rocotostat.py
  workflow/hosts/hercules.yaml
  workflow/hosts/orion.yaml
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2611 Change GRIB2 parameter names and vertical levels for ocean/ice post
  parm/post/oceanice_products.yaml
  ush/oceanice_nc2grib2.sh
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2634 Script to keep Jenkins Agent persistent from cron
  ci/platforms/config.hera
  ci/platforms/config.hercules
  ci/platforms/config.orion
  ci/scripts/utils/launch_java_agent.sh
Labels: CI/CD

#2619 Update to add 1-deg global wave grid
  parm/config/gefs/config.base
  parm/config/gefs/config.ufs
  parm/config/gefs/config.wave
  parm/config/gfs/config.ufs
  parm/config/gfs/config.wave
  parm/wave/ww3_grib2.glo_100.inp.tmpl
  scripts/exgfs_wave_post_gridded_sbs.sh
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2622 Update forecast job to use COMIN/COMOUT
  jobs/JGLOBAL_FORECAST
  ush/forecast_det.sh
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2627 Add the capability to use slurm reservation nodes
  parm/config/gefs/config.base
  parm/config/gfs/config.base
  workflow/hosts/awspw.yaml
  workflow/hosts/container.yaml
  workflow/hosts/hera.yaml
  workflow/hosts/hercules.yaml
  workflow/hosts/jet.yaml
  workflow/hosts/orion.yaml
  workflow/hosts/s4.yaml
  workflow/hosts/wcoss2.yaml
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2608 Switch to Rocky 9 built external packages on Hercules
  jobs/JGFS_ATMOS_CYCLONE_GENESIS
  jobs/JGFS_ATMOS_CYCLONE_TRACKER
  jobs/JGFS_ATMOS_FSU_GENESIS
  workflow/hosts/hercules.yaml
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed
