Repository NOAA-EMC/global-workflow, pull requests merged in 2024-08, with the labels that each got.

#2784 Update ocean post-processing triggers
  ush/check_netcdf.sh
  workflow/rocoto/gefs_tasks.py
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Passed

#2803 Fix erroneous cdump addition
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Failed

#2762 Update Java Agent launching script for Jenkins connections
  ci/scripts/utils/launch_java_agent.sh
Labels: CI/CD

#2804 Run METplus serially and correct the name of prod tasks
  parm/config/gfs/config.resources
  workflow/rocoto/tasks.py
Labels: CI-Hera-Failed, CI-Wcoss2-Failed

#2787 land surface upgrades for hr4
  ush/parsing_namelists_FV3.sh
  ush/parsing_namelists_FV3_nest.sh
Labels: CI-Hera-Passed

#2753 Clean-up temporary rundirs - take 2.
  .github/pull_request_template.md
  jobs/JGFS_ATMOS_FBWIND
  jobs/JGFS_ATMOS_GEMPAK_META
  jobs/JGFS_ATMOS_GEMPAK_PGRB2_SPEC
  jobs/JGLOBAL_CLEANUP
  parm/config/gefs/config.base
  parm/config/gfs/config.base
  parm/config/gfs/config.fbwind
  parm/config/gfs/config.resources
  scripts/exglobal_cleanup.sh
  ush/jjob_header.sh
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2811 Revert MSU FIX_DIRs back to glopara
  sorc/link_workflow.sh
Labels: maintenance

#2772 Feature/get arch adds an empty archive job to GEFS system
  jobs/rocoto/arch_test.sh
  parm/config/gefs/config.arch
  parm/config/gefs/config.resources
  workflow/applications/gefs.py
  workflow/rocoto/gefs_tasks.py
Labels: CI-Hercules-Passed

#2755 Add fixes to products for when REPLAY IC's are used
  parm/config/gefs/config.extractvars
  parm/config/gefs/config.fcst
  parm/config/gefs/config.resources
  parm/post/oceanice_products_gefs.yaml
  parm/ufs/fv3/diag_table_replay
  ush/atmos_extractvars.sh
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
  ush/ocnice_extractvars.sh
  ush/parsing_model_configure_FV3.sh
  ush/parsing_namelists_FV3.sh
Labels: CI-Hera-Passed, CI-Hercules-Passed

#2815 Jenkins Pipeline Updates
  ci/Jenkinsfile
Labels: CI/CD, CI-Hercules-Passed

#2842 Fixed test on UNAVAILBLE in python Rocoto check
  ci/scripts/utils/rocotostat.py
Labels: bug, CI/CD

#2651 Convert staging job to python and yaml
  ci/cases/pr/C48mx500_3DVarAOWCDA.yaml
  ci/cases/pr/C96C48_hybatmDA.yaml
  ci/cases/pr/C96C48_ufs_hybatmDA.yaml
  ci/cases/pr/C96_atm3DVar.yaml
  ci/cases/pr/C96_atm3DVar_extended.yaml
  ci/cases/pr/C96_atmaerosnowDA.yaml
  docs/source/init.rst
  jobs/JGLOBAL_STAGE_IC
  parm/config/gefs/config.base
  parm/config/gefs/config.stage_ic
  parm/config/gfs/config.base
  parm/config/gfs/config.com
  parm/config/gfs/config.stage_ic
  parm/stage/analysis.yaml.j2
  parm/stage/atmosphere_cold.yaml.j2
  parm/stage/atmosphere_nest.yaml.j2
  parm/stage/atmosphere_perturbation.yaml.j2
  parm/stage/atmosphere_warm.yaml.j2
  parm/stage/ice.yaml.j2
  parm/stage/master_gefs.yaml.j2
  parm/stage/master_gfs.yaml.j2
  parm/stage/ocean.yaml.j2
  parm/stage/ocean_mediator.yaml.j2
  parm/stage/ocean_replay.yaml.j2
  parm/stage/ocean_rerun.yaml.j2
  parm/stage/wave.yaml.j2
  scripts/exgfs_aero_init_aerosol.py
  scripts/exglobal_stage_ic.py
  scripts/exglobal_stage_ic.sh
  ush/check_ice_netcdf.sh
  ush/python/pygfs/task/stage_ic.py
  workflow/applications/gfs_cycled.py
  workflow/hosts/awspw.yaml
  workflow/hosts/gaea.yaml
  workflow/hosts/hera.yaml
  workflow/hosts/hercules.yaml
  workflow/hosts/jet.yaml
  workflow/hosts/orion.yaml
  workflow/hosts/s4.yaml
  workflow/hosts/wcoss2.yaml
  workflow/rocoto/gefs_tasks.py
  workflow/rocoto/gfs_tasks.py
  workflow/setup_expt.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2849 Update prepobs to v1.1.0 in GFSv16.3.16
  docs/Release_Notes.gfs.v16.3.16.md
  versions/hera.ver
  versions/orion.ver
  versions/wcoss2.ver
Labels: production update

#2857 Fix gdas build on Gaea and add Gaea to available CI list
  ci/Jenkinsfile
  modulefiles/module_gwsetup.gaea.lua
Labels: CI/CD

#2868 Correct ocean `MOM.res_#` stage copy
  parm/stage/ocean.yaml.j2
  scripts/exglobal_stage_ic.py
Labels: CI-Wcoss2-Passed

#2876 Add 3 and 9 hr increment files to IC staging
  parm/stage/analysis.yaml.j2
Labels: CI-Hera-Passed
