Repository NOAA-EMC/global-workflow, pull requests merged in 2024-11, with the labels that each got.

#3056 GitHub CI Pipeline update for debugging forked PR support
  .github/workflows/pw_aws_ci.yaml
Labels: CI/CD

#3059 PW CI pipeline update5 ready for review so it can be merged and tested
  .github/workflows/pw_aws_ci.yaml
Labels: CI/CD

#3060 update to action workflow pipeline in default repo for development
  .github/workflows/pw_aws_ci.yaml
Labels: CI/CD

#3061 Update to action workflow pipeline in default repo for development
  .github/workflows/pw_aws_ci.yaml
Labels: CI/CD

#3062 Update to action workflow pipeline in default repo for development
  .github/workflows/pw_aws_ci.yaml
Labels: CI/CD

#3070 Update Release Notes with PlanetIQ
  docs/Release_Notes.md
Labels: production update

#3055 Update snow obs processing job
  env/HERA.env
  env/HERCULES.env
  env/JET.env
  env/ORION.env
  env/S4.env
  env/WCOSS2.env
  jobs/JGLOBAL_PREP_SNOW_OBS
  jobs/rocoto/prepsnowobs.sh
  jobs/rocoto/snowanl.sh
  parm/config/gfs/config.prepsnowobs
  parm/config/gfs/config.resources
  parm/config/gfs/config.snowanl
  scripts/exglobal_prep_snow_obs.py
  scripts/exglobal_snow_analysis.py
  workflow/applications/gfs_cycled.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Passed

#3050 Update JGDAS ENKF ECEN job
  jobs/JGDAS_ENKF_ECEN
  scripts/exgdas_enkf_ecen.sh
Labels: CI-Hera-Passed, CI-Hercules-Passed

#3084 CI GitHub pipeline (hotfix) update for fetching repo name
  .github/workflows/pw_aws_ci.yaml
Labels: CI/CD

#3076 Remove RUNDIRS before running CI cases to cover re-run events
  ci/Jenkinsfile
  ci/scripts/check_ci.sh
  ci/scripts/utils/ci_utils.sh
  ci/scripts/utils/get_config_var.py
Labels: CI-Hera-Passed, CI-Orion-Failed, CI/CD, CI-Hercules-Passed

#2960 SFS Runs at C96mx100
  .gitignore
  ci/cases/sfs/C96mx100_S2S.yaml
  ci/cases/yamls/gefs_defaults_ci.yaml
  ci/cases/yamls/gefs_replay_ci.yaml
  ci/cases/yamls/sfs_defaults.yaml
  parm/config/gefs/config.atmos_products
  parm/config/gefs/config.base
  parm/config/gefs/config.efcs
  parm/config/gefs/config.fcst
  parm/config/gefs/config.stage_ic
  parm/config/gefs/config.ufs
  parm/config/gefs/yaml/defaults.yaml
  parm/config/gfs/config.ocn
  parm/config/gfs/config.stage_ic
  parm/product/sfs.0p25.f000.paramlist.a.txt
  parm/product/sfs.0p25.fFFF.paramlist.a.txt
  parm/product/sfs.0p25.fFFF.paramlist.b.txt
  parm/stage/master_gefs.yaml.j2
  scripts/exglobal_stage_ic.py
  sorc/build_all.sh
  sorc/build_ufs.sh
  sorc/link_workflow.sh
  ush/forecast_det.sh
  ush/forecast_predet.sh
  ush/parsing_namelists_FV3.sh
Labels: CI-Hera-Passed, CI-Hercules-Passed

#3097 Enable tapering of atm ens perts at the model top
  parm/config/gfs/config.eupd
  scripts/exgdas_enkf_update.sh
Labels: CI-Hercules-Passed

#3107 Add new stations to GFS BUFR sounding products
  parm/product/bufr_ij_gfs_C1152.txt
  parm/product/bufr_ij_gfs_C768.txt
  parm/product/bufr_ij_gfs_C96.txt
  parm/product/bufr_stalist.meteo.gfs
Labels: CI-Wcoss2-Passed

#2982 Make aerosol output frequency variable
  parm/archive/gdas.yaml.j2
  parm/archive/gfs_arcdir.yaml.j2
  parm/archive/gfsa.yaml.j2
  parm/archive/master_gfs.yaml.j2
  parm/config/gefs/config.base
  parm/config/gefs/yaml/defaults.yaml
  parm/config/gfs/config.base
  parm/ufs/gocart/AERO_HISTORY.rc
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
  ush/parsing_namelists_GOCART.sh
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#3115 Speed up GSI analysis jobs in CI testing
  ci/cases/gfsv17/ocnanal.yaml
  ci/cases/yamls/atmaerosnowDA_defaults_ci.yaml
  ci/cases/yamls/gfs_defaults_ci.yaml
  ci/cases/yamls/gfs_extended_ci.yaml
  ci/cases/yamls/soca_gfs_defaults_ci.yaml
  parm/config/gefs/config.base
  parm/config/gefs/yaml/defaults.yaml
  parm/config/gfs/config.anal
  parm/config/gfs/config.base
  parm/config/gfs/yaml/defaults.yaml
Labels: CI-Hera-Passed, CI-Hercules-Passed

#2943 Allow APP to differ between RUNs
  ci/Jenkinsfile
  jobs/JGLOBAL_FORECAST
  parm/archive/gdas.yaml.j2
  parm/archive/gfs_arcdir.yaml.j2
  parm/archive/gfsa.yaml.j2
  parm/archive/master_gfs.yaml.j2
  parm/config/gefs/config.base
  parm/config/gefs/config.efcs
  parm/config/gefs/config.fcst
  parm/config/gefs/config.resources
  parm/config/gfs/config.base
  parm/config/gfs/config.efcs
  parm/config/gfs/config.fcst
  parm/config/gfs/config.resources
  scripts/exglobal_archive.py
  ush/python/pygfs/task/archive.py
  workflow/applications/applications.py
  workflow/applications/gefs.py
  workflow/applications/gfs_cycled.py
  workflow/applications/gfs_forecast_only.py
  workflow/rocoto/gefs_tasks.py
  workflow/rocoto/gefs_xml.py
  workflow/rocoto/gfs_cycled_xml.py
  workflow/rocoto/gfs_forecast_only_xml.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
  workflow/rocoto/workflow_xml.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#3014 Refactor gridded wave post
  parm/config/gefs/config.base
  parm/config/gfs/config.base
  scripts/exgfs_wave_post_gridded_sbs.sh
  workflow/rocoto/gefs_tasks.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed
