Repository NOAA-EMC/global-workflow, pull requests merged in 2024-02, with the labels that each got.

#2278 Retire cycle-specific FHMAX_GFS variables
  .gitignore
  parm/config/gefs/config.base.emc.dyn
  parm/config/gefs/yaml/defaults.yaml
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/yaml/defaults.yaml
  workflow/applications/gfs_cycled.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Orion-Passed

#2252 Update `detect_machine.sh` using that from UFS WM
  ush/detect_machine.sh
Labels: maintenance, CI-Hera-Passed, CI-Orion-Passed

#2281 Removes files module loading file no longer used by the GW
  modulefiles/module-setup.csh.inc
  modulefiles/module-setup.sh.inc
  ush/load_fv3gfs_modules.sh
  ush/load_ufsda_modules.sh
  ush/module-setup.sh
Labels: CI-Orion-Passed

#2289 Consolidate `npe_node_max`
  env/AWSPW.env
  env/CONTAINER.env
  env/HERA.env
  env/HERCULES.env
  env/JET.env
  env/ORION.env
  env/S4.env
  env/WCOSS2.env
  parm/config/gefs/config.ufs
  parm/config/gfs/config.ufs
Labels: CI-Hera-Passed, CI-Orion-Passed

#2295 Update JGLOBAL_FORECAST for octal error
  jobs/JGLOBAL_FORECAST
Labels: bug

#1963 Enable AO WCDA test
  ci/cases/pr/C48mx500_3DVarAOWCDA.yaml
  ci/cases/yamls/soca_gfs_defaults_ci.yaml
  env/HERA.env
  jobs/JGLOBAL_PREP_OCEAN_OBS
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.ocn
  parm/config/gfs/config.resources
  parm/config/gfs/yaml/defaults.yaml
  workflow/applications/gfs_cycled.py
  workflow/setup_expt.py
Labels: CI-Hera-Passed

#2246 Jenkins Declartive Pipeline for CI with gfs/gefs multibuilds
  Jenkinsfile
  ci/cases/yamls/build.yaml
  ci/scripts/run-check_ci.sh
  ci/scripts/utils/ci_utils.sh
  ci/scripts/utils/ci_utils_wrapper.sh
  modulefiles/module_gwsetup.hera.lua
Labels: CI/CD

#2302 Fix Jenkins success reporting
  Jenkinsfile
Labels: bug, CI/CD

#2304 Redo v16.3 config.base changes for DA increments
  parm/config/gfs/config.base.emc.dyn
Labels: CI-Orion-Passed

#2306 Updated pr case list for Jenkins
  Jenkinsfile
Labels: CI/CD

#2307 Jenkins Pipeline updates for Canceling Jobs
  Jenkinsfile
  ci/cases/pr/C48mx500_3DVarAOWCDA.yaml
  ci/scripts/run-check_ci.sh
  ci/scripts/utils/ci_utils.sh
Labels: CI-Hera-Failed, CI/CD

#2321 Set HOMEgfs for module_setup in CI driver
  ci/scripts/check_ci.sh
  ci/scripts/driver.sh
  ci/scripts/run_ci.sh
Labels: CI/CD

#2327 Add some flexibility for ocean/ice output
  parm/config/gefs/config.base.emc.dyn
  parm/config/gefs/config.fcst
  parm/config/gfs/config.base.emc.dyn
  parm/config/gfs/config.fcst
  parm/ufs/fv3/diag_table
  ush/forecast_predet.sh
  ush/parsing_namelists_CICE.sh
  ush/parsing_namelists_FV3.sh
  ush/python/pygfs/task/oceanice_products.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Orion-Failed

#2334 Jenkins updates
  Jenkinsfile
  ci/scripts/utils/get_host_case_list.py
  ci/scripts/utils/wxflow
Labels: CI/CD

#2351 Fix rocoto forecast hour determination for GEFS
  ci/cases/pr/C48_S2SWA_gefs.yaml
  parm/config/gfs/config.stage_ic
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed

#2362 Update gsd_prep_chem tag to gefs_v12.3.9
  sorc/checkout.sh
Labels: production update, GEFS

#2355 Move Jenkinsfile into ci subdirectory
  ci/Jenkinsfile
Labels: CI/CD
