Repository NOAA-EMC/global-workflow, pull requests merged in 2024-09, with the labels that each got.

#2888 Update aerosol climatology to 2013-2024 mean
  ush/forecast_predet.sh
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2893 Eliminate race conditions and remove DATAROOT last in cleanup
  scripts/exglobal_cleanup.sh
Labels: CI-Wcoss2-Passed

#2816 Add an archive task to GEFS system to archive files locally
  jobs/rocoto/arch_test.sh
  parm/archive/gefs_arcdir.yaml.j2
  parm/archive/gfs_arcdir.yaml.j2
  parm/config/gefs/yaml/defaults.yaml
  scripts/exgdas_enkf_earc.py
  scripts/exglobal_archive.py
  ush/python/pygfs/task/archive.py
  workflow/rocoto/gefs_tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2871 Replace APRUN with APRUN_default
  env/AWSPW.env
  env/AZUREPW.env
  env/GAEA.env
  env/GOOGLEPW.env
  env/HERA.env
  env/HERCULES.env
  env/JET.env
  env/ORION.env
  env/S4.env
  env/WCOSS2.env
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2904 Add new UPP links to .gitignore
  .gitignore
  sorc/link_workflow.sh
Labels: CI-Hera-Passed

#2914 Updates for HR4 tag
  parm/config/gefs/config.ufs
  parm/config/gfs/config.ufs
  ush/forecast_postdet.sh
  ush/parsing_model_configure_FV3.sh
Labels: CI-Hera-Running, CI-Orion-Building, CI-Wcoss2-Passed

#2917 Update config.resources for bufr sounding job postsnd
  env/WCOSS2.env
  parm/config/gfs/config.resources
Labels: CI-Wcoss2-Passed

#2867 Update global atmos upp job to use COMIN/COMOUT
  jobs/JGLOBAL_ATMOS_UPP
  parm/post/upp.yaml
  scripts/exglobal_atmos_upp.py
  ush/python/pygfs/task/upp.py
Labels: CI-Hera-Passed, CI-Orion-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2903 Update to obsproc/v1.2.0 and prepobs/v1.1.0
  modulefiles/module_base.gaea.lua
  modulefiles/module_base.hercules.lua
  modulefiles/module_base.jet.lua
  modulefiles/module_base.orion.lua
  modulefiles/module_base.wcoss2.lua
  parm/config/gfs/config.base
  versions/build.gaea.ver
  versions/build.hera.ver
  versions/build.hercules.ver
  versions/build.jet.ver
  versions/build.noaacloud.ver
  versions/build.orion.ver
  versions/build.s4.ver
  versions/build.spack.ver
  versions/run.gaea.ver
  versions/run.hera.ver
  versions/run.hercules.ver
  versions/run.jet.ver
  versions/run.noaacloud.ver
  versions/run.orion.ver
  versions/run.s4.ver
  versions/run.wcoss2.ver
  versions/spack.ver
  workflow/hosts/orion.yaml
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2939 Update global atmos vminmon job with COMIN/COMOUT for COM prefix
  jobs/JGLOBAL_ATMOS_VMINMON
Labels: CI-Wcoss2-Passed

#2809 Remove need for a ice_prod dependency check script
  ush/check_ice_netcdf.sh
  ush/forecast_predet.sh
  ush/python/pygfs/task/oceanice_products.py
  workflow/rocoto/gefs_tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#2895 Add an archive task to GEFS system to archive files in HPSS
  parm/archive/gefs_extracted_atmos.yaml.j2
  parm/archive/gefs_extracted_ice.yaml.j2
  parm/archive/gefs_extracted_ocean.yaml.j2
  parm/archive/gefs_extracted_wave.yaml.j2
  parm/archive/master_gefs.yaml.j2
  parm/config/gefs/yaml/defaults.yaml
  parm/config/gfs/config.resources
  parm/config/gfs/config.resources.GAEA
  parm/config/gfs/config.resources.HERA
  parm/config/gfs/config.resources.JET
  parm/config/gfs/config.resources.ORION
  parm/config/gfs/config.resources.S4
  scripts/exglobal_archive.py
  ush/python/pygfs/task/archive.py
  workflow/applications/gefs.py
  workflow/rocoto/gefs_tasks.py
Labels: CI-Hera-Passed, CI-Orion-Failed, CI-Hercules-Failed, CI-Wcoss2-Passed

#2875 Replace separate JEDI radiance bias correction files with tarball
  ci/cases/pr/C96C48_ufs_hybatmDA.yaml
  env/ORION.env
  parm/archive/gdas_restarta.yaml.j2
  parm/config/gfs/config.resources.ORION
  parm/stage/analysis.yaml.j2
  ush/python/pygfs/jedi/jedi.py
  ush/python/pygfs/task/analysis.py
  ush/python/pygfs/task/atm_analysis.py
  ush/python/pygfs/task/atmens_analysis.py
Labels: CI-Hera-Passed, CI-Hercules-Failed, CI-Wcoss2-Passed
