Repository NOAA-EMC/global-workflow, pull requests merged in 2024-04, with the labels that each got.

#2392 Add GEFS ENS Atmos options
  env/WCOSS2.env
  parm/config/gefs/config.base
  parm/config/gefs/config.efcs
  parm/config/gefs/config.fcst
  parm/config/gefs/yaml/defaults.yaml
  parm/config/gfs/config.fcst
  ush/forecast_postdet.sh
  ush/parsing_namelists_FV3.sh
Labels: CI-Hera-Passed

#2443 Fix rotating member bugs
  scripts/exgdas_enkf_ecen.sh
  scripts/exgdas_enkf_sfc.sh
  scripts/exgdas_enkf_update.sh
Labels: CI-Hera-Passed

#2447 Move bash utility functions out of preamble
  ush/bash_functions.sh
  ush/bash_utils.sh
  ush/preamble.sh
Labels: CI-Orion-Passed

#2456 Turn off reducedgrid in the EnKF
  scripts/exgdas_enkf_update.sh
Labels: CI-Hera-Passed

#2478 Add support for CADS IR cloud detection scheme in the GSI
  scripts/exglobal_atmos_analysis.sh
Labels: CI-Orion-Passed

#2486 Update parm files for atm product
  parm/product/gfs.anl.paramlist.a.txt
  parm/product/gfs.f000.paramlist.a.txt
  parm/product/gfs.fFFF.paramlist.a.txt
Labels: CI-Orion-Passed

#2481 Upadte and tested CI Bash for WCOSS2
  ci/cases/pr/C48_S2SWA_gefs.yaml
  ci/cases/pr/C48mx500_3DVarAOWCDA.yaml
  ci/cases/pr/C96C48_ufs_hybatmDA.yaml
  ci/cases/pr/C96_atmaerosnowDA.yaml
  ci/platforms/config.wcoss2
  ci/scripts/check_ci.sh
  ci/scripts/clone-build_ci.sh
  ci/scripts/driver.sh
  ci/scripts/driver_weekly.sh
  ci/scripts/run_ci.sh
  ci/scripts/utils/ci_utils.sh
  modulefiles/module_gwci.wcoss2.lua
Labels: CI/CD

#2484 Add rocoto `sh` tag, script to check netcdf file and apply this to check ocean output
  ush/bash_utils.sh
  ush/check_netcdf.sh
  ush/file_utils.sh
  ush/jjob_header.sh
  ush/preamble.sh
  workflow/rocoto/gefs_tasks.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/rocoto.py
Labels: CI-Wcoss2-Passed

#2488 CI Refactoring and STALLED case detection
  ci/Jenkinsfile
  ci/scripts/check_ci.sh
  ci/scripts/clone-build_ci.sh
  ci/scripts/driver.sh
  ci/scripts/run-check_ci.sh
  ci/scripts/run_ci.sh
  ci/scripts/utils/ci_utils.sh
  ci/scripts/utils/pr_list_database.py
  ci/scripts/utils/rocotostat.py
  workflow/rocoto_viewer.py
Labels: CI-Hera-Passed, CI-Orion-Passed, CI/CD, CI-Wcoss2-Passed

#2523 Hotfix to disable STALLED in CI as an error
  ci/Jenkinsfile
  ci/scripts/utils/rocotostat.py
Labels: CI-Hera-Building, CI/CD

#2521 Add CCPP suite and FASTER option to UFS build
  parm/config/gfs/config.ufs
  sorc/build_all.sh
  sorc/build_ufs.sh
Labels: CI-Hera-Passed

#2536 Hot fix for bash CI on WCOSS2
  ci/scripts/clone-build_ci.sh
  ci/scripts/utils/rocotostat.py
Labels: CI/CD, CI-Wcoss2-Passed

#2540 Add CADS use flexibility
  parm/config/gfs/config.anal
  scripts/exglobal_atmos_analysis.sh
Labels: CI-Wcoss2-Passed

#2532 Add option to link different orog/ugwd fix files for global nest
  sorc/link_workflow.sh
  versions/fix.nest.ver
Labels: CI-Wcoss2-Passed

#2548 Launch Multiple Platforms to Jenkins with polling
  ci/Jenkinsfile
Labels: CI-Hera-Passed, CI-Orion-Failed, CI/CD, CI-Hercules-Failed, CI-Wcoss2-Passed

#2553 Link ensemble analysis increment files to COMROOT for warm_start
  workflow/setup_expt.py
Labels: CI-Hera-Passed

#2541 Fixes sea ice archiving
  ush/hpssarch_gen.sh
Labels: CI-Wcoss2-Passed
