Repository NOAA-EMC/global-workflow, pull requests merged in 2025-08, with the labels that each got.

#3948 Hotfix: submodule updates for PR checkouts in GitLab pipeline
  .gitlab-ci.yml
Labels: bug, CI/CD

#3942 Re-enable the `MAKE_PREPBUFR` capability
  dev/jobs/prep.sh
  dev/parm/config/gcafs/config.base.j2
  dev/parm/config/gefs/config.base.j2
  dev/parm/config/gfs/config.base.j2
  dev/parm/config/gfs/config.prep
  dev/parm/config/sfs/config.base.j2
  dev/workflow/hosts/awspw.yaml
  dev/workflow/hosts/azurepw.yaml
  dev/workflow/hosts/container.yaml
  dev/workflow/hosts/gaeac5.yaml
  dev/workflow/hosts/gaeac6.yaml
  dev/workflow/hosts/googlepw.yaml
  dev/workflow/hosts/hera.yaml
  dev/workflow/hosts/hercules.yaml
  dev/workflow/hosts/orion.yaml
  dev/workflow/hosts/wcoss2.yaml
  jobs/JGDAS_ENKF_DIAG
  jobs/JGDAS_ENKF_SELECT_OBS
  jobs/JGLOBAL_ATMOS_ANALYSIS
Labels: CI-Gaeac6-Passed, Ready for CI

#3884 Update the maximum number of gempak tasks to 42
  dev/parm/config/gfs/config.gempak
  dev/workflow/rocoto/gfs_tasks.py
Labels: CI-Wcoss2-Passed

#3902 Bugfix for soil Increments archiving and staging
  dev/ci/cases/gfsv17/s2sw.yaml
  dev/ci/cases/pr/C96C48_hybatmsoilDA.yaml
  dev/ci/cases/yamls/atmsoilDA_defaults_ci.yaml
  dev/parm/config/gefs/config.base.j2
  dev/parm/config/sfs/config.base.j2
  parm/archive/enkf_grp.yaml.j2
  parm/archive/enkf_restarta_grp.yaml.j2
  parm/archive/gdas_restarta.yaml.j2
  parm/stage/analysis.yaml.j2
  scripts/exgdas_enkf_earc_tars.py
  scripts/exgdas_enkf_earc_vrfy.py
  scripts/exglobal_archive_tars.py
  scripts/exglobal_archive_vrfy.py
  scripts/exglobal_stage_ic.py
Labels: CI-Wcoss2-Passed, CI-Gaeac6-Passed, Ready for CI

#3991 Consolidate DOIBP_WAV to DOBNDPNT_WAV
  dev/parm/config/gcafs/config.base.j2
  dev/parm/config/gefs/config.base.j2
  dev/parm/config/gfs/config.base.j2
  dev/parm/config/sfs/config.base.j2
  parm/archive/gfswave.yaml.j2
  scripts/exglobal_archive_tars.py
Labels: CI-Gaeac6-Passed
