Repository NOAA-EMC/global-workflow, pull requests merged in 2025-01, with the labels that each got.

#3193 Add efcs and epos to ufs_hybatm xml (#3192)
  parm/archive/enkf_restartb_grp.yaml.j2
  workflow/applications/gfs_cycled.py
Labels: CI-Hera-Passed, CI-Hercules-Passed

#3171 Set runtime shell requirements within Jenkins Pipeline
  ci/Jenkinsfile
  ci/scripts/utils/launch_java_agent.sh
Labels: CI-Orion-Passed, CI/CD

#3199 Ensure OCNRES and ICERES have 3 digits in the archive script
  scripts/exglobal_archive.py
Labels: CI-Hera-Passed

#3119 Separate use of initial increment/perturbation file from REPLAY/+03 ICs
  ci/cases/yamls/gefs_defaults_ci.yaml
  ci/cases/yamls/sfs_defaults.yaml
  parm/config/gefs/config.base
  parm/config/gefs/config.efcs
  parm/config/gefs/config.fcst
  parm/config/gefs/config.nsst
  parm/config/gefs/config.resources
  parm/config/gefs/config.stage_ic
  parm/config/gefs/config.ufs
  parm/config/gefs/yaml/defaults.yaml
  parm/config/gfs/config.fcst
  ush/forecast_det.sh
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#3215 Turn IAU off during staging job for cold start experiments
  parm/config/gefs/config.stage_ic
  parm/config/gfs/config.stage_ic
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#3208 Reinstate product groups
  jobs/rocoto/atmos_ensstat.sh
  jobs/rocoto/atmos_products.sh
  jobs/rocoto/gempak.sh
  jobs/rocoto/oceanice_products.sh
  jobs/rocoto/wavepostsbs.sh
  parm/config/gefs/config.atmos_ensstat
  parm/config/gefs/config.atmos_products
  parm/config/gefs/config.oceanice_products
  parm/config/gefs/config.resources
  parm/config/gefs/config.wavepostsbs
  parm/config/gfs/config.atmos_products
  parm/config/gfs/config.gempak
  parm/config/gfs/config.oceanice_products
  parm/config/gfs/config.resources
  parm/config/gfs/config.wavepostsbs
  workflow/rocoto/gefs_tasks.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
  workflow/tests/__init__.py
  workflow/tests/test_configuration.py
  workflow/tests/test_hosts.py
  workflow/tests/test_tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Passed, CI-Wcoss2-Passed

#3224 Add bmat task dependency to marine LETKF task
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Passed

#3221 Add additional GEFS variables needed for AI/ML applications
  parm/product/gefs.0p25.fFFF.paramlist.a.txt
  parm/product/gefs.0p25.fFFF.paramlist.b.txt
  parm/ufs/fv3/diag_table
  parm/ufs/fv3/diag_table_replay
  scripts/exglobal_atmos_products.sh
  ush/forecast_predet.sh
  ush/parsing_namelists_FV3.sh
Labels: CI-Hercules-Passed

#3211 Adding a gefs_arch task to GEFS workflow
  parm/archive/gefs_extracted_atmos.yaml.j2
  parm/archive/gefs_extracted_ice.yaml.j2
  parm/archive/gefs_extracted_ocean.yaml.j2
  parm/archive/gefs_extracted_wave.yaml.j2
  parm/archive/master_gefs.yaml.j2
  workflow/applications/gefs.py
  workflow/rocoto/gefs_tasks.py
Labels: CI-Hera-Passed

#3236 Move WCOSS2 LD_LIBRARY_PATH patches to load_ufsda_modules.sh
  env/WCOSS2.env
  ush/load_ufsda_modules.sh
Labels: CI-Wcoss2-Passed

#3137 Add domain level to wave gridded COM path
  jobs/JGLOBAL_ARCHIVE
  jobs/JGLOBAL_EXTRACTVARS
  jobs/JGLOBAL_WAVE_GEMPAK
  jobs/JGLOBAL_WAVE_POST_SBS
  jobs/JGLOBAL_WAVE_PRDGEN_GRIDDED
  parm/archive/gfswave.yaml.j2
  parm/config/gfs/config.com
  parm/config/gfs/config.waveawipsgridded
  parm/config/gfs/config.wavegempak
  scripts/exgfs_wave_nawips.sh
  scripts/exgfs_wave_post_gridded_sbs.sh
  scripts/exgfs_wave_prdgen_gridded.sh
  scripts/exglobal_archive.py
  ush/wave_domain_grid.sh
  ush/wave_extractvars.sh
  ush/wave_grib2_sbs.sh
Labels: CI-Hera-Failed

#3141 Add fetch job and update stage_ic to work with fetched ICs
  ci/cases/yamls/gfs_defaults_ci.yaml
  jobs/JGLOBAL_FETCH
  jobs/rocoto/fetch.sh
  parm/config/gefs/config.base
  parm/config/gefs/config.fetch
  parm/config/gfs/config.base
  parm/config/gfs/config.fetch
  parm/config/gfs/config.resources
  parm/config/gfs/config.stage_ic
  parm/fetch/gfs_ATM_cold_forecast-only.yaml.j2
  parm/fetch/gfs_S2SW_cold_forecast-only.yaml.j2
  scripts/exglobal_fetch.py
  ush/python/pygfs/__init__.py
  ush/python/pygfs/task/fetch.py
  workflow/applications/applications.py
  workflow/applications/gfs_forecast_only.py
  workflow/hosts/azurepw.yaml
  workflow/hosts/s4.yaml
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: feature, CI-Hercules-Passed

#3249 Add gfs cycles to C48mx500_3DVarAOWCDA
  ci/cases/pr/C48mx500_3DVarAOWCDA.yaml
  ci/cases/yamls/soca_gfs_defaults_ci.yaml
  parm/archive/gdaswave.yaml.j2
  parm/archive/gfswave.yaml.j2
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Passed

#3281 GFSv16.3.21 - WAFS removal from GFS
  Externals.cfg
  docs/Release_Notes.md
  ecf/defs/gfs_v16_3.def
  ecf/scripts/enkfgdas/analysis/create/jenkfgdas_update.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_blending.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_blending_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2.ecf
  ecf/scripts/gfs/atmos/post_processing/grib2_wafs/jgfs_atmos_wafs_grib2_0p25.ecf
  ecf/scripts/gfs/atmos/post_processing/grib_wafs/.gitignore
  ecf/scripts/gfs/atmos/post_processing/grib_wafs/jgfs_atmos_wafs_master.ecf
  ecf/scripts/gfs/atmos/post_processing/jgfs_atmos_wafs_gcip.ecf
  ecf/setup_ecf_links.sh
  env/HERA.env
  env/ORION.env
  env/WCOSS2.env
  fix/product/wafs_admin_msg
  jobs/rocoto/arch.sh
  jobs/rocoto/wafs.sh
  jobs/rocoto/wafsblending.sh
  jobs/rocoto/wafsblending0p25.sh
  jobs/rocoto/wafsgcip.sh
  jobs/rocoto/wafsgrib2.sh
  jobs/rocoto/wafsgrib20p25.sh
  modulefiles/module_base.wcoss_dell_p3
  parm/config/config.base.emc.dyn
  parm/config/config.base.nco.static
  parm/config/config.resources.emc.dyn
  parm/config/config.resources.nco.static
  parm/config/config.wafs
  parm/config/config.wafsblending
  parm/config/config.wafsblending0p25
  parm/config/config.wafsgcip
  parm/config/config.wafsgrib2
  parm/config/config.wafsgrib20p25
  parm/product/transfer_gfs_1.list
  parm/product/transfer_gfs_7.list
  sorc/build_all.sh
  sorc/build_gfs_wafs.sh
  sorc/checkout.sh
  sorc/fv3gfs_build.cfg
  sorc/link_fv3gfs.sh
  sorc/partial_build.sh
  sorc/syndat_getjtbul.fd/getjtbul.f
  ush/ecflow/prod.yml
  ush/hpssarch_gen.sh
  ush/rocoto/setup_workflow.py
  ush/rocoto/setup_workflow_fcstonly.py
  versions/run.ver
Labels: production update

#3292 Update gsl-prep-chem to gefs_v12.3.12 for GEFSv12
  sorc/checkout.sh
Labels: production update, GEFS

#3283 Add esnowanl to enkfgfs cycle
  jobs/JGLOBAL_SNOWENS_ANALYSIS
  parm/gdas/snow_stage_ens_update.yaml.j2
  workflow/applications/gfs_cycled.py
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Passed
