Repository NOAA-EMC/global-workflow, pull requests merged in 2025-09, with the labels that each got.

#3981 Archive each gfs and gdas tarball via its own rocoto job
  dev/workflow/rocoto/gfs_tasks.py
  parm/archive/enkf_restarta_grp.yaml.j2
  parm/archive/enkf_restartb_grp.yaml.j2
  parm/archive/master_enkf.yaml.j2
  parm/archive/master_gdas.yaml.j2
  parm/archive/master_gfs.yaml.j2
  scripts/exglobal_archive_tars.py
  ush/python/pygfs/task/archive.py
Labels: CI-Gaeac6-Passed

#3956 GitLab pipeline support for the Hercules and Orion
  .github/workflows/trigger-gitlab-pipelines.yml
  .gitlab-ci.yml
  README.md
  dev/ci/gitlab-ci-hosts.yml
  dev/ci/platforms/config.hercules
  dev/ci/platforms/config.orion
  dev/ci/scripts/run_check_gitlab_ci.sh
  dev/ci/scripts/utils/ci_utils.sh
  dev/ci/scripts/utils/rocotostat.py
  dev/ctests/README.md
Labels: CI/CD, CI-Gaeac6-Failed, Ready for CI

#3970 Remove dependency of gfs_marineanlchkpt on enkfgfs_marineanlecen when early cycle EnKF is not run
  dev/workflow/rocoto/gfs_tasks.py
Labels: CI-Gaeac6-Passed

#4036 Quick Fix: added path in stack stack 1.9 for loading gh on gaeac6
  modulefiles/gw_setup.gaeac6.lua
Labels: CI/CD

#4059 Hotfix - pipeline profile for Hera needs HERA in GFS_CI_ROOT path
  dev/ci/platforms/config.hera
Labels: CI/CD

#4083 Updates from retrotests
  dev/parm/config/gfs/config.efcs
  dev/parm/config/gfs/config.fcst.j2
  dev/parm/config/gfs/config.resources
  dev/parm/config/gfs/config.resources.GAEAC6
  dev/parm/config/gfs/config.resources.WCOSS2
  parm/wave/bull_awips_gfswave.uglo_15km
  ush/forecast_postdet.sh
Labels: CI-Hercules-Running, CI-Hera-Passed (cm)

#4084 CI/CD Pipeline GitHub integration (updates checks info section in PR)
  .github/workflows/trigger-gitlab-pipelines.yml
  .gitlab-ci.yml
Labels: CI/CD

#4030 Write atmospheric history files at a different resolution than the model
  dev/ci/cases/gfsv17/s2sw.yaml
  dev/ci/cases/yamls/gfs_cyc_defaults_ci.yaml
  dev/parm/config/gcafs/config.base.j2
  dev/parm/config/gefs/config.base.j2
  dev/parm/config/gfs/config.base.j2
  dev/parm/config/gfs/config.efcs
  dev/parm/config/gfs/config.resources
  dev/parm/config/sfs/config.base.j2
  jobs/JGLOBAL_ATMOS_TROPCY_QC_RELOC
  scripts/exglobal_atmos_analysis.sh
  ush/forecast_predet.sh
  ush/gaussian_sfcanl.sh
  ush/gfs_bufr.sh
  ush/parsing_model_configure_FV3.sh
Labels: CI-Hera-Ready, CI-Gaeac6-Passed (cm)

#3846 Adding workflow infrastructure for wave_stat and wave_stat_pnt jobs
  dev/jobs/wave_stat.sh
  dev/jobs/wave_stat_pnt.sh
  dev/parm/config/gefs/config.resources
  dev/parm/config/gefs/config.wave_stat
  dev/parm/config/gefs/config.wave_stat_pnt
  dev/workflow/applications/gefs.py
  dev/workflow/rocoto/gefs_tasks.py
  dev/workflow/rocoto/tasks.py
  env/AWSPW.env
  env/AZUREPW.env
  env/GAEAC5.env
  env/GAEAC6.env
  env/GOOGLEPW.env
  env/HERA.env
  env/HERCULES.env
  env/ORION.env
  env/URSA.env
  env/WCOSS2.env
  jobs/JGEFS_WAVE_STAT
  jobs/JGEFS_WAVE_STAT_PNT
Labels: CI-Hera-Passed, CI-Wcoss2-Passed
