Repository NOAA-EMC/global-workflow, pull requests merged in 2025-02, with the labels that each got.

#3256 CTests extended validation for C48_ATM and staged C48_S2SW for gfs_fcst and gfs_atmos
  ci/platforms/config.orion
  ctests/CMakeLists.txt
  ctests/README.md
  ctests/cases/C48_ATM_gfs_fcst_seg0.yaml
  ctests/cases/C48_S2SW_gfs_atmos_prod_f000-f003.yaml
  ctests/cases/C48_S2SW_gfs_fcst_seg0.yaml
  ctests/scripts/execute.sh.in
  ctests/scripts/stage.py
  ctests/scripts/stage.sh.in
  ctests/scripts/validate.py
  ctests/scripts/validate.sh.in
Labels: CI/CD

#3242 Splitting up the archive task
  .github/CODEOWNERS
  docs/source/jobs.rst
  jobs/JGDAS_ENKF_ARCHIVE_TARS
  jobs/JGDAS_ENKF_ARCHIVE_VRFY
  jobs/JGLOBAL_ARCHIVE_TARS
  jobs/JGLOBAL_ARCHIVE_VRFY
  jobs/rocoto/arch_tars.sh
  jobs/rocoto/arch_vrfy.sh
  jobs/rocoto/earc_tars.sh
  jobs/rocoto/earc_vrfy.sh
  parm/archive/gfsa.yaml.j2
  parm/config/gefs/config.arch_tars
  parm/config/gefs/config.arch_vrfy
  parm/config/gefs/config.base
  parm/config/gefs/config.resources
  parm/config/gefs/config.resources.AWSPW
  parm/config/gfs/config.arch_tars
  parm/config/gfs/config.arch_vrfy
  parm/config/gfs/config.base
  parm/config/gfs/config.earc_tars
  parm/config/gfs/config.earc_vrfy
  parm/config/gfs/config.resources
  parm/config/gfs/config.resources.AWSPW
  parm/config/gfs/config.resources.WCOSS2
  scripts/exgdas_enkf_earc_tars.py
  scripts/exgdas_enkf_earc_vrfy.py
  scripts/exglobal_archive_tars.py
  scripts/exglobal_archive_vrfy.py
  ush/python/pygfs/task/archive.py
  workflow/applications/applications.py
  workflow/applications/gefs.py
  workflow/applications/gfs_cycled.py
  workflow/applications/gfs_forecast_only.py
  workflow/rocoto/gefs_tasks.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: CI-Hera-Passed, CI-Wcoss2-Passed

#3297 Capture build fail in Jenkins pipeline when no error logs are produced
  ci/Jenkinsfile
Labels: bug, CI/CD, triage

#3319 Add missing arch_tars dependencies
  env/HERA.env
  modulefiles/module_base.hera.lua
  versions/run.hera.ver
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Passed, CI-Hercules-Passed

#3333 Update jgdas enkf update job with COMIN or COMOUT prefix instead of COM
  jobs/JGDAS_ENKF_UPDATE
  scripts/exgdas_enkf_update.sh
Labels: CI-Wcoss2-Passed

#3303 Remove Direct Linking to COM from DATA for `wavepostsbs` Job
  ush/wave_grib2_sbs.sh
  ush/wave_grid_interp_sbs.sh
Labels: CI-Hera-Passed

#3351 Update bufr station list for GEFSv12 ops
  parm/product/bufr_stalist.meteo.gfs
  parm/product/bufr_stalist.meteo.gfs3
  sorc/checkout.sh
Labels: production update, GEFS

#3393 Update enkf archive jobs to use COMIN/COMOUT
  jobs/JGDAS_ENKF_ARCHIVE_TARS
  jobs/JGDAS_ENKF_ARCHIVE_VRFY
  scripts/exgdas_enkf_earc_tars.py
  scripts/exgdas_enkf_earc_vrfy.py
Labels: CI-Hercules-Passed
