Repository NOAA-EMC/global-workflow, pull requests merged in 2025-06, with the labels that each got.

#3725 Replace `NDATE` with `date`
  jobs/JGDAS_ATMOS_ANALYSIS_DIAG
  jobs/JGDAS_ENKF_DIAG
  jobs/JGDAS_ENKF_ECEN
  jobs/JGDAS_ENKF_SELECT_OBS
  jobs/JGDAS_ENKF_SFC
  jobs/JGDAS_ENKF_UPDATE
  jobs/JGDAS_FIT2OBS
  jobs/JGLOBAL_ATMOS_ANALYSIS
  jobs/JGLOBAL_ATMOS_ANALYSIS_CALC
  jobs/JGLOBAL_OFFLINE_ATMOS_ANALYSIS
  scripts/exgdas_atmos_chgres_forenkf.sh
  scripts/exgdas_enkf_sfc.sh
  scripts/exgfs_wave_post_pnt.sh
  scripts/exgfs_wave_prep.sh
  scripts/exglobal_atmos_analysis.sh
  scripts/exglobal_atmos_tropcy_qc_reloc.sh
  ush/getges.sh
  ush/tropcy_relocate.sh
  ush/tropcy_relocate_extrkr.sh
  ush/wave_outp_cat.sh
  ush/wave_outp_spec.sh
Labels: CI-Hercules-Passed, CI-Wcoss2-Passed

#3747 Fix archiving tasks failing on marine DA files with DOIAU="NO"
  parm/archive/enkf_marine_grp.yaml.j2
  parm/archive/enkf_restarta_grp.yaml.j2
  parm/archive/gdasocean.yaml.j2
  parm/archive/gdasocean_analysis.yaml.j2
Labels: CI-Hera-Passed

#3489 Save marine LETKF yaml
  jobs/JGLOBAL_MARINE_ANALYSIS_LETKF
  parm/archive/enkf_marine_grp.yaml.j2
  parm/archive/master_enkf.yaml.j2
  ush/python/pygfs/task/marine_letkf.py
Labels: JEDI, CI-Gaeac6-Passed

#3721 Add an Empty Task for the GEFS to Change Resolution of the Control Member IC
  dev/jobs/gen_control_ic.sh
  dev/parm/config/gefs/config.gen_control_ic
  dev/parm/config/gefs/config.resources
  dev/workflow/applications/applications.py
  dev/workflow/applications/gefs.py
  dev/workflow/rocoto/gefs_tasks.py
  dev/workflow/rocoto/tasks.py
  parm/stage/master_gefs_RT.yaml.j2
Labels: CI-Hera-Passed

#3751 Bug fix for IMS observation staging and madis_snow stats output
  parm/gdas/stat_base_config.yaml.j2
  ush/python/pygfs/task/snow_analysis.py
  ush/python/pygfs/task/snowens_analysis.py
Labels: CI-Hercules-Passed, CI-Gaeac6-Passed

#3815 Generate hourly wave gdas grib files
  .gitignore
  dev/parm/config/gcafs/config.base.j2
  dev/parm/config/gefs/config.base.j2
  dev/parm/config/gfs/config.base.j2
  dev/parm/config/gfs/yaml/defaults.yaml
  dev/parm/config/sfs/config.base.j2
  dev/workflow/rocoto/tasks.py
  parm/archive/gfswave.yaml.j2
  scripts/exglobal_archive_tars.py
  sorc/link_workflow.sh
Labels: CI-Hera-Passed

#3694 Handle bias correction files for aerosol DA
  dev/parm/config/gefs/config.base.j2
  dev/parm/config/sfs/config.base.j2
  jobs/JGLOBAL_AERO_ANALYSIS_INITIALIZE
  parm/gdas/aero_stage_variational.yaml.j2
  parm/stage/aero.yaml.j2
  parm/stage/master_gfs.yaml.j2
  scripts/exglobal_stage_ic.py
  ush/python/pygfs/task/aero_analysis.py
Labels: CI-Hercules-Passed

#3823 Fix bug in gempak walltime calculation
  dev/parm/config/gfs/config.resources
  dev/workflow/rocoto/gfs_tasks.py
  scripts/exgfs_atmos_nawips.sh
Labels: CI-Wcoss2-Passed

#3828 Testing Jenkins updates (hotfix)
  dev/ci/Jenkinsfile
Labels: bug, CI-Hera-Passed, CI/CD, CI-Gaeac6-Running
