Repository NOAA-EMC/global-workflow, pull requests merged in 2025-04, with the labels that each got.

#3517 Rename wave output and refactor some wave scripts to use MPMD, and fix some bugzillas along the way
  ci/cases/pr/C96C48_ufs_hybatmDA.yaml
  env/AWSPW.env
  env/AZUREPW.env
  env/GAEAC5.env
  env/GAEAC6.env
  env/GOOGLEPW.env
  env/HERA.env
  env/HERCULES.env
  env/JET.env
  env/ORION.env
  env/S4.env
  env/WCOSS2.env
  jobs/JGLOBAL_WAVE_GEMPAK
  jobs/JGLOBAL_WAVE_INIT
  jobs/JGLOBAL_WAVE_POST_BNDPNT
  jobs/JGLOBAL_WAVE_POST_BNDPNTBLL
  jobs/JGLOBAL_WAVE_POST_PNT
  jobs/JGLOBAL_WAVE_POST_SBS
  jobs/rocoto/wavegempak.sh
  jobs/rocoto/wavepostbndpnt.sh
  jobs/rocoto/wavepostbndpntbll.sh
  jobs/rocoto/wavepostpnt.sh
  jobs/rocoto/wavepostsbs.sh
  parm/archive/gdaswave.yaml.j2
  parm/archive/gfswave.yaml.j2
  parm/config/gfs/config.resources
  scripts/exgfs_wave_init.sh
  scripts/exgfs_wave_nawips.sh
  scripts/exgfs_wave_post_gridded_sbs.sh
  scripts/exgfs_wave_post_pnt.sh
  scripts/exglobal_atmos_products.sh
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
  ush/run_mpmd.sh
  ush/wave_domain_grid.sh
  ush/wave_grib2_sbs.sh
  ush/wave_grid_interp_sbs.sh
  ush/wave_grid_moddef.sh
  ush/wave_tar.sh
  workflow/rocoto/gefs_tasks.py
  workflow/rocoto/gfs_tasks.py
Labels: CI-Hera-Failed, CI-Hercules-Passed, CI-Wcoss2-Passed, CI-Gaeac6-Failed

#3400 Download subset fix data with python script
  .gitignore
  ush/fetch-fix-data.py
Labels: CI-Awsepicglobalworkflow-Passed

#3518 COMIN/COMOUT updates for enkf chgres and downstream product jobs
  .github/CODEOWNERS
  gempak/ush/gfs_meta_ak.sh
  gempak/ush/gfs_meta_bwx.sh
  gempak/ush/gfs_meta_comp.sh
  gempak/ush/gfs_meta_crb.sh
  gempak/ush/gfs_meta_hi.sh
  gempak/ush/gfs_meta_hur.sh
  gempak/ush/gfs_meta_mar_atl.sh
  gempak/ush/gfs_meta_mar_comp.sh
  gempak/ush/gfs_meta_mar_pac.sh
  gempak/ush/gfs_meta_mar_ql.sh
  gempak/ush/gfs_meta_mar_skewt.sh
  gempak/ush/gfs_meta_mar_ver.sh
  gempak/ush/gfs_meta_nhsh.sh
  gempak/ush/gfs_meta_opc_na_ver
  gempak/ush/gfs_meta_opc_np_ver
  gempak/ush/gfs_meta_precip.sh
  gempak/ush/gfs_meta_qpf.sh
  gempak/ush/gfs_meta_sa.sh
  gempak/ush/gfs_meta_sa2.sh
  gempak/ush/gfs_meta_trop.sh
  gempak/ush/gfs_meta_us.sh
  gempak/ush/gfs_meta_usext.sh
  gempak/ush/gfs_meta_ver.sh
  jobs/JGDAS_ATMOS_CHGRES_FORENKF
  jobs/JGDAS_ATMOS_GEMPAK
  jobs/JGFS_ATMOS_AWIPS_20KM_1P0DEG
  jobs/JGFS_ATMOS_GEMPAK
  jobs/JGFS_ATMOS_GEMPAK_META
  jobs/JGFS_ATMOS_GEMPAK_PGRB2_SPEC
  jobs/JGFS_ATMOS_PGRB2_SPEC_NPOESS
  jobs/JGFS_ATMOS_POSTSND
  jobs/JGLOBAL_ATMOS_POST_MANAGER
  jobs/JGLOBAL_ATMOS_PRODUCTS
  scripts/exgdas_atmos_chgres_forenkf.sh
  scripts/exgdas_atmos_nawips.sh
  scripts/exgfs_atmos_awips_20km_1p0deg.sh
  scripts/exgfs_atmos_gempak_meta.sh
  scripts/exgfs_atmos_goes_nawips.sh
  scripts/exgfs_atmos_grib2_special_npoess.sh
  scripts/exgfs_atmos_nawips.sh
  scripts/exgfs_atmos_postsnd.sh
  scripts/exglobal_atmos_pmgr.sh
  scripts/exglobal_atmos_products.sh
  ush/gfs_bfr2gpk.sh
  ush/gfs_bufr.sh
  ush/gfs_sndp.sh
Labels: CI-Wcoss2-Passed

#3558 Temporarily disable compute builds on C6
  ci/scripts/utils/ci_utils.sh
Labels: CI-Gaeac6-Running

#3537 Save snow and aerosol analysis increments (and logs and YAMLs) every cycle
  jobs/JGLOBAL_AERO_ANALYSIS_FINALIZE
  parm/archive/gdas.yaml.j2
  parm/archive/gdas_restarta.yaml.j2
  parm/gdas/aero_finalize_variational.yaml.j2
Labels: CI-Hera-Failed, CI-Gaeac6-Passed

#3549 Use err_chk in GSI J-Jobs and scripts
  jobs/JGDAS_ATMOS_ANALYSIS_DIAG
  jobs/JGDAS_ATMOS_CHGRES_FORENKF
  jobs/JGDAS_ATMOS_VERFOZN
  jobs/JGDAS_ATMOS_VERFRAD
  jobs/JGDAS_ENKF_DIAG
  jobs/JGDAS_ENKF_ECEN
  jobs/JGDAS_ENKF_POST
  jobs/JGDAS_ENKF_SELECT_OBS
  jobs/JGDAS_ENKF_SFC
  jobs/JGDAS_ENKF_UPDATE
  jobs/JGLOBAL_ARCHIVE_TARS
  jobs/JGLOBAL_ATMOS_ANALYSIS
  jobs/JGLOBAL_ATMOS_ANALYSIS_CALC
  jobs/JGLOBAL_ATMOS_SFCANL
  jobs/JGLOBAL_ATMOS_VMINMON
  jobs/JGLOBAL_ENS_ARCHIVE_TARS
  scripts/exgdas_atmos_chgres_forenkf.sh
  scripts/exgdas_atmos_verfozn.sh
  scripts/exgdas_atmos_verfrad.sh
  scripts/exgdas_enkf_ecen.sh
  scripts/exgdas_enkf_post.sh
  scripts/exgdas_enkf_sfc.sh
  scripts/exgdas_enkf_update.sh
  ush/jjob_header.sh
Labels: CI-Hercules-Passed

#3551 Create separate gists when multiple files are published on GitHub
  ci/Jenkinsfile
  ci/scripts/utils/githubpr.py
  ci/scripts/utils/publish_logs.py
Labels: CI/CD, CI-Hercules-Failed

#3471 Add initial capability to produce JEDI-based observation space summary stat files
  .github/CODEOWNERS
  .gitignore
  env/GAEAC6.env
  env/HERA.env
  env/HERCULES.env
  env/ORION.env
  env/WCOSS2.env
  jobs/JGLOBAL_ANALYSIS_STATS
  jobs/rocoto/anlstat.sh
  parm/config/gfs/config.anlstat
  parm/config/gfs/config.base.j2
  parm/config/gfs/config.com
  parm/config/gfs/config.resources
  parm/config/gfs/yaml/stat_base_config.yaml.j2
  parm/gdas/anlstat_jedi_config.yaml.j2
  scripts/exglobal_analysis_stats.py
  sorc/link_workflow.sh
  ush/python/pygfs/task/analysis_stats.py
  workflow/applications/applications.py
  workflow/applications/gfs_cycled.py
  workflow/rocoto/gfs_tasks.py
  workflow/rocoto/tasks.py
Labels: JEDI, CI-Gaeac6-Passed

#3578 Hotfix in GitLab pipline for Nightly (env MACHINE breaks build on head node)
  dev/ci/.gitlab-ci.yml
Labels: bug, CI/CD

#3572 Remove support for Jet and S4
  README.md
  dev/workflow/hosts.py
  dev/workflow/hosts/jet.yaml
  dev/workflow/hosts/s4.yaml
  docs/doxygen/compile
  docs/note_fixfield.txt
  docs/source/components.rst
  docs/source/hpc.rst
  docs/source/init.rst
  env/JET.env
  env/S4.env
  modulefiles/module_base.jet.lua
  modulefiles/module_base.s4.lua
  modulefiles/module_gwsetup.jet.lua
  modulefiles/module_gwsetup.s4.lua
  parm/config/gefs/config.resources
  parm/config/gfs/config.resources
  parm/config/gfs/config.resources.JET
  parm/config/gfs/config.resources.S4
  parm/config/sfs/config.resources
  sorc/link_workflow.sh
  ush/calcanl_gfs.py
  ush/load_fv3gfs_modules.sh
  ush/load_ufsda_modules.sh
  ush/module-setup.sh
  versions/build.jet.ver
  versions/build.s4.ver
  versions/run.jet.ver
  versions/run.s4.ver
Labels: CI-Wcoss2-Passed

#3571 Call err_chk/err_exit for fatal errors in post JJobs/ex-scripts
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/dump_request.yml
  dev/jobs/arch_tars.sh
  dev/jobs/arch_vrfy.sh
  dev/jobs/earc_tars.sh
  dev/jobs/earc_vrfy.sh
  dev/jobs/esnowanl.sh
  dev/jobs/globus_arch.sh
  dev/jobs/globus_earc.sh
  dev/jobs/marineanlletkf.sh
  dev/jobs/prep_emissions.sh
  dev/jobs/prepatmiodaobs.sh
  dev/jobs/prepoceanobs.sh
  dev/jobs/snowanl.sh
  jobs/JGDAS_ATMOS_GEMPAK
  jobs/JGDAS_ATMOS_GEMPAK_META_NCDC
  jobs/JGDAS_FIT2OBS
  jobs/JGFS_ATMOS_AWIPS_20KM_1P0DEG
  jobs/JGFS_ATMOS_FBWIND
  jobs/JGFS_ATMOS_GEMPAK
  jobs/JGFS_ATMOS_GEMPAK_META
  jobs/JGFS_ATMOS_GEMPAK_PGRB2_SPEC
  jobs/JGFS_ATMOS_PGRB2_SPEC_NPOESS
  jobs/JGFS_ATMOS_POSTSND
  jobs/JGLOBAL_ATMOS_POST_MANAGER
  jobs/JGLOBAL_ATMOS_PRODUCTS
  jobs/JGLOBAL_ATMOS_UPP
  jobs/JGLOBAL_CLEANUP
  jobs/JGLOBAL_OCEANICE_PRODUCTS
  scripts/exgdas_atmos_gempak_gif_ncdc.sh
  scripts/exgdas_atmos_nawips.sh
  scripts/exgfs_atmos_awips_20km_1p0deg.sh
  scripts/exgfs_atmos_fbwind.sh
  scripts/exgfs_atmos_gempak_meta.sh
  scripts/exgfs_atmos_goes_nawips.sh
  scripts/exgfs_atmos_grib2_special_npoess.sh
  scripts/exgfs_atmos_nawips.sh
  scripts/exgfs_atmos_postsnd.sh
  scripts/exglobal_atmos_pmgr.sh
  scripts/exglobal_atmos_products.sh
  ush/load_ufsda_modules.sh
Labels: CI-Wcoss2-Passed, CI-Gaeac6-Passed

#3608 COM variable updates for prep and some external downstream jobs
  dev/jobs/prep.sh
  jobs/JGDAS_FIT2OBS
  jobs/JGFS_ATMOS_CYCLONE_GENESIS
  jobs/JGFS_ATMOS_CYCLONE_TRACKER
  jobs/JGFS_ATMOS_FSU_GENESIS
  jobs/JGLOBAL_ATMOS_TROPCY_QC_RELOC
  jobs/JGLOBAL_OCEANICE_PRODUCTS
  parm/post/oceanice_products.yaml
  parm/post/oceanice_products_gefs.yaml
  scripts/exglobal_atmos_tropcy_qc_reloc.sh
  scripts/exglobal_oceanice_products.py
  ush/bash_utils.sh
  ush/syndat_qctropcy.sh
  ush/tropcy_relocate.sh
  versions/run.wcoss2.ver
  versions/spack.ver
Labels: CI-Wcoss2-Passed, CI-Gaeac6-Passed

#3615 Avoid parallel restart I/O on WCOSS2
  dev/ci/cases/weekly/C384_S2SWA.yaml
  sorc/build_all.sh
  sorc/build_ufs.sh
Labels: CI-Wcoss2-Passed

#3603 GitLab CI Framework for schedule PR cases and ctests on multi hosts
  .github/workflows/ci_unit_tests.yaml
  .github/workflows/pw_aws_ci.yaml
  .gitlab-ci.yml
  CMakeLists.txt
  dev/ci/.gitlab-ci.yml
  dev/ci/Jenkinsfile
  dev/ci/Jenkinsfile4AWS
  dev/ci/gitlab-ci-cases.yml
  dev/ci/gitlab-ci-ctests.yml
  dev/ci/gitlab-ci-hosts.yml
  dev/ci/platforms/config.gaeac6
  dev/ci/platforms/config.hera
  dev/ci/scripts/check_ci.sh
  dev/ci/scripts/clone-build_ci.sh
  dev/ci/scripts/driver.sh
  dev/ci/scripts/driver_weekly.sh
  dev/ci/scripts/run_check_ci.sh
  dev/ci/scripts/run_ci.sh
  dev/ci/scripts/unittests/test_create_experiment.py
  dev/ci/scripts/unittests/test_data/test_config.yaml
  dev/ci/scripts/unittests/test_find_homegfs.py
  dev/ci/scripts/unittests/test_parse_yaml.py
  dev/ci/scripts/unittests/test_rocotostat.py
  dev/ci/scripts/unittests/test_setup.py
  dev/ci/scripts/unittests/wxflow
  dev/ci/scripts/utils/ci_utils.sh
  dev/ci/scripts/utils/ci_utils_wrapper.sh
  dev/ci/scripts/utils/find_homegfs.py
  dev/ci/scripts/utils/get_host_case_list.py
  dev/ci/scripts/utils/gitlab/badge-updater-pipeline.yml
  dev/ci/scripts/utils/gitlab/docs/README.md
  dev/ci/scripts/utils/gitlab/launch_gitlab_runner.sh
  dev/ci/scripts/utils/launch_java_agent.sh
  dev/ci/scripts/utils/parallel_works/UserBootstrap_centos7.txt
  dev/ci/scripts/utils/parallel_works/provision_runner.sh
  dev/ci/scripts/utils/parse_yaml.py
  dev/ci/scripts/utils/pr_list_database.py
  dev/ctests/CMakeLists.txt
  dev/ctests/scripts/execute.sh.in
  dev/ctests/scripts/setup.sh.in
Labels: CI-Hera-Passed, CI/CD, CI-Hercules-Passed, CI-Gaeac6-Passed

#3617 Add a low resolution test to mimic GFSv17 cycling as much as possible
  dev/ci/cases/pr/C96C48mx500_S2SW_cyc_gfs.yaml
  dev/ci/cases/yamls/gfs_cyc_defaults_ci.yaml
  dev/workflow/rocoto/gfs_tasks.py
  parm/stage/ice.yaml.j2
Labels: CI-Hera-Passed, CI-Wcoss2-Passed, CI-Gaeac6-Passed
