Repository NOAA-EMC/global-workflow, pull requests merged in 2025-05, with the labels that each got.

#3017 Update scripts to use the GW-RT global namelist
  dev/ci/cases/yamls/sfs_defaults.yaml
  dev/ci/cases/yamls/sfs_full.yaml
  parm/config/gefs/config.efcs
  parm/config/gefs/config.fcst.j2
  parm/config/gefs/config.ufs
  parm/config/gefs/yaml/defaults.yaml
  parm/config/gfs/config.efcs
  parm/config/gfs/config.ufs
  parm/config/sfs/config.efcs
  parm/config/sfs/config.fcst.j2
  parm/config/sfs/yaml/defaults.yaml
  sorc/link_workflow.sh
  ush/forecast_predet.sh
  ush/parsing_namelists_FV3.sh
  ush/parsing_namelists_FV3_nest.sh
  ush/parsing_namelists_MOM6.sh
Labels: CI-Hera-Failed, CI-Hercules-Passed, CI-Wcoss2-Passed, CI-Gaeac6-Failed

#3640 Add err_chk to a few more jobs
  jobs/JGLOBAL_ATMOS_EMCSFC_SFC_PREP
  jobs/JGLOBAL_ATMOS_ENSSTAT
  jobs/JGLOBAL_ATMOS_TROPCY_QC_RELOC
  jobs/JGLOBAL_PREP_EMISSIONS
  jobs/JGLOBAL_PREP_OBS_AERO
  jobs/JGLOBAL_PREP_OCEAN_OBS
  scripts/exglobal_atmos_ensstat.sh
  scripts/exglobal_atmos_vminmon.sh
Labels: CI-Gaeac6-Failed

#3646 Resolve "No such" statement bugzillas and address wave log redirects
  dev/jobs/awips_20km_1p0deg.sh
  ecf/scripts/gfs/atmos/post_processing/awips_20km_1p0/jgfs_atmos_awips_master.ecf
  jobs/JGFS_ATMOS_AWIPS_20KM_1P0DEG
  jobs/JGLOBAL_CLEANUP
  parm/config/gefs/config.wave
  parm/config/gfs/config.resources
  parm/config/gfs/config.wave
  scripts/exgdas_enkf_ecen.sh
  scripts/exgdas_enkf_select_obs.sh
  scripts/exgdas_enkf_update.sh
  scripts/exgfs_atmos_awips_20km_1p0deg.sh
  scripts/exgfs_wave_post_pnt.sh
  scripts/exgfs_wave_prdgen_bulls.sh
  scripts/exgfs_wave_prdgen_gridded.sh
  scripts/exgfs_wave_prep.sh
  scripts/exglobal_atmos_analysis.sh
  scripts/exglobal_atmos_analysis_calc.sh
  scripts/exglobal_atmos_tropcy_qc_reloc.sh
  scripts/exglobal_cleanup.sh
  scripts/exglobal_diag.sh
  ush/jjob_header.sh
  ush/wave_extractvars.sh
  ush/wave_prnc_ice.sh
Labels: CI-Hercules-Passed, CI-Gaeac6-Passed

#3600 Update the default `IAUFHRS` value in some ex-scripts to a comma-delimited string
  scripts/exgdas_atmos_chgres_forenkf.sh
  scripts/exgdas_enkf_update.sh
  scripts/exglobal_atmos_analysis.sh
  scripts/exglobal_atmos_analysis_calc.sh
Labels: CI-Hercules-Passed, CI-Gaeac6-Passed

#3680 Restore RadMon's ability to automatically extract data from new data sources
  scripts/exgdas_atmos_verfrad.sh
Labels: CI-Gaeac6-Passed

#3654 Invoke err_chk for fatal errors in the wave J-Jobs and ex-scripts
  jobs/JGLOBAL_WAVE_GEMPAK
  jobs/JGLOBAL_WAVE_INIT
  jobs/JGLOBAL_WAVE_POST_BNDPNT
  jobs/JGLOBAL_WAVE_POST_BNDPNTBLL
  jobs/JGLOBAL_WAVE_POST_PNT
  jobs/JGLOBAL_WAVE_POST_SBS
  jobs/JGLOBAL_WAVE_PRDGEN_BULLS
  jobs/JGLOBAL_WAVE_PRDGEN_GRIDDED
  jobs/JGLOBAL_WAVE_PREP
  scripts/exgfs_wave_init.sh
  scripts/exgfs_wave_nawips.sh
  scripts/exgfs_wave_post_gridded_sbs.sh
  scripts/exgfs_wave_post_pnt.sh
  scripts/exgfs_wave_prdgen_bulls.sh
  scripts/exgfs_wave_prdgen_gridded.sh
  scripts/exgfs_wave_prep.sh
  ush/wave_outp_cat.sh
  ush/wave_outp_spec.sh
  ush/wave_prnc_ice.sh
  ush/wave_tar.sh
Labels: CI-Hera-Failed, CI-Wcoss2-Passed, CI-Gaeac6-Passed

#3634 Updates to resources and yaml files from GFS C1152 cycled testing
  dev/ci/cases/gfsv17/C1152mx025_S2SW.yaml
  dev/ci/cases/gfsv17/C1152mx025_S2SW_rdhpcs.yaml
  dev/ci/cases/gfsv17/s2sw.yaml
  dev/parm/config/gfs/config.resources
  dev/parm/config/gfs/config.resources.GAEAC6
  dev/parm/config/gfs/config.ufs
Labels: CI-Wcoss2-Passed, CI-Gaeac6-Failed

#3704 bug fix for IAU: move restart frequency calculation
  ush/forecast_postdet.sh
  ush/forecast_predet.sh
Labels: CI-Gaeac6-Failed

#3683 Clean compath usage and add prep_sfc job to rocoto mesh
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/static_data.yml
  .gitignore
  dev/jobs/prep.sh
  dev/jobs/prep_sfc.sh
  dev/parm/config/gfs/config.base.j2
  dev/parm/config/gfs/config.com
  dev/parm/config/gfs/config.prep
  dev/parm/config/gfs/config.prep_sfc
  dev/parm/config/gfs/config.resources
  dev/workflow/README_ecflow.md
  dev/workflow/applications/applications.py
  dev/workflow/applications/gfs_cycled.py
  dev/workflow/hosts/hera.yaml
  dev/workflow/hosts/wcoss2.yaml
  dev/workflow/prod.yml
  dev/workflow/rocoto/gfs_tasks.py
  dev/workflow/rocoto/tasks.py
  ecf/defs/gfs_00.def
  ecf/defs/gfs_06.def
  ecf/defs/gfs_12.def
  ecf/defs/gfs_18.def
  ecf/defs/gfs_v16_3.def
  ecf/defs/prod00.def
  ecf/defs/prod06.def
  ecf/defs/prod12.def
  ecf/defs/prod18.def
  ecf/scripts/gdas/atmos/obsproc/prep/jgdas_atmos_prep_sfc.ecf
  ecf/scripts/gfs/atmos/obsproc/prep/jgfs_atmos_prep_sfc.ecf
  gempak/ush/gdas_ukmet_meta_ver.sh
  gempak/ush/gfs_meta_crb.sh
  gempak/ush/gfs_meta_hur.sh
  jobs/JGDAS_ATMOS_GEMPAK
  jobs/JGDAS_ATMOS_GEMPAK_META_NCDC
  jobs/JGFS_ATMOS_CYCLONE_TRACKER
  jobs/JGFS_ATMOS_FSU_GENESIS
  jobs/JGFS_ATMOS_GEMPAK_META
  jobs/JGLOBAL_ATMOS_EMCSFC_SFC_PREP
  jobs/JGLOBAL_ATMOS_PREP_SFC
  jobs/JGLOBAL_WAVE_PREP
  parm/prep_sfc/snow2mdl.nml.tmpl
  scripts/exgfs_wave_prep.sh
  scripts/exglobal_prep_sfc.sh
  sorc/link_workflow.sh
  ush/getdump.sh
  ush/prep_sfc_ice_blend.sh
  ush/prep_sfc_snow.sh
  ush/syndat_getjtbul.sh
  ush/syndat_qctropcy.sh
Labels: CI-Hera-Failed, CI-Wcoss2-Passed

#3714 Cast output_fh as an interval when FHOUT_HF and FHOUT are the same
  dev/ci/cases/yamls/sfs_defaults.yaml
  dev/ci/cases/yamls/sfs_full.yaml
  dev/parm/config/sfs/yaml/defaults.yaml
  ush/forecast_predet.sh
Labels: CI-Gaeac6-Passed

#3719 Check for binary or netCDF WW3 restarts when staging
  parm/stage/wave.yaml.j2
  ush/python/pygfs/task/stage_ic.py
Labels: CI-Gaeac6-Passed

#3688 GitLab Pipeline updates for CTest Automation against Nightly Runs
  .github/workflows/trigger-gitlab-ctests.yml
  .gitlab-ci.yml
  dev/ci/gitlab-ci-cases.yml
  dev/ci/gitlab-ci-ctests.yml
  dev/ci/gitlab-ci-hosts.yml
  dev/ci/platforms/config.gaeac6
  dev/ci/platforms/config.hera
  dev/ci/platforms/config.hercules
  dev/ci/platforms/config.orion
  dev/ci/scripts/run_check_ci.sh
  dev/ci/scripts/utils/ci_utils.sh
  dev/ctests/CMakeLists.txt
  dev/ctests/README.md
  dev/ctests/cases/C48_ATM_gfs_fcst_seg0.yaml
  dev/ctests/cases/C48_S2SW_gfs_atmos_prod_f000-f003.yaml
  dev/ctests/cases/C48_S2SW_gfs_fcst_seg0.yaml
  dev/ctests/scripts/execute.sh.in
  dev/ctests/scripts/stage.sh.in
  dev/ctests/scripts/validate.sh.in
  modulefiles/module_gwsetup.gaeac6.lua
  modulefiles/module_gwsetup.hera.lua
Labels: CI-Hera-Passed, CI/CD, CI-Hercules-Passed, CI-Gaeac6-Passed

#3677 Update param files for GEFS
  parm/product/gefs.0p25.f000.paramlist.a.txt
  parm/product/gefs.0p25.f000.paramlist.b.txt
  parm/product/gefs.0p25.fFFF.paramlist.a.txt
  parm/product/gefs.0p25.fFFF.paramlist.b.txt
  parm/product/gefs.0p50.f000.paramlist.a.txt
  parm/product/gefs.0p50.f000.paramlist.b.txt
  parm/product/gefs.0p50.fFFF.paramlist.a.txt
  parm/product/gefs.0p50.fFFF.paramlist.b.txt
Labels: CI-Hera-Passed

#3717 Move default STMP, PTMP, and HOMEDIR paths to world-shared on C6
  dev/workflow/hosts/gaeac6.yaml
Labels: CI-Gaeac6-Passed

#3728 Hotfix: Updating ref value in GitHub dispatch action for triggering CTest on GitLab
  .github/workflows/trigger-gitlab-ctests.yml
Labels: CI/CD

#3730 Add cice analysis restart to ocean analysis archiving
  jobs/JGLOBAL_ARCHIVE_TARS
  parm/archive/gdasocean_analysis.yaml.j2
Labels: CI-Hera-Passed, CI-Gaeac6-Passed
